### ISSUE TITLE
4.2.0 binary not available

### ISSUE THREAD

**Issue by alixwar** [SonarSource/SonarJS#1030]
Hi,
4.2.0 is not available as a JAR file here: https://github.com/SonarSource/SonarJS/releases

Is the binary available somewhere else or is this a mistake?

Regards
Alix

**Comment by saberduck** [comment]
@alixwar oups, indeed I forgot to do it :) 

See release here https://github.com/SonarSource/SonarJS/releases/tag/4.2.0.6476 

thanks
