### ISSUE TITLE
Customize existing rules

### ISSUE THREAD

**Issue by gonzalocordero** [SonarSource/SonarJS#1052]
Hello:

Im new to the world of Sonar, this is awesome! great job you guys.

My questions are:
- is there an easy way to customize the existing rules you guys provide? if so, how?
- is everything Java based? (I come from a JS background)

Thank you!

**Comment by vilchik-elena** [comment]
SonarQube is java based, but some language analyzers use other languages (e.g. c# for .Net or typescript). Note that we plan to migrate the core of SonarJS analyzer to js/ts (https://jira.sonarsource.com/browse/MMF-1409).

You can customize some existing rules, if there is parameter available. For that you need to create your own custom profile (inheriting from default if you want)
