### ISSUE TITLE
Make CognitiveComplexity(S3776) eslint-based rule (cognitive-complexity) (TS/JS)

### ISSUE THREAD

**Issue by andrea-guarino-sonarsource** [SonarSource/SonarJS#1081]
Currently we don't have a way to support secondary issue locations for eslint-based rules.
Since those are fundamental for cognitive complexity, we will replace this rule when we will implement secondary locations for eslint-based rules.

**Comment by vilchik-elena** [comment]
When ESLint get's an issue, it keeps only required properties, thus everything provided above will be erased. The only way I see to push through ESLint properties required to SonarJS (like cost and secondary locations) is to patch ESLint. 
There is this package https://www.npmjs.com/package/patch-package allowing to do this. We will need to patch here:
https://github.com/eslint/eslint/blob/master/lib/report-translator.js#L271

and here:
https://github.com/eslint/eslint/blob/master/lib/report-translator.js#L198

**Comment by andrea-guarino-sonarsource** [comment]
Other two alternative options could be:
- Sharing data between eslint-bridge and eslint-plugin-sonarjs via global variable or an inline database (e.g. [lowdb](https://github.com/typicode/lowdb) )
- Writing secondary locations in the issue message, and parsing them

**Comment by vilchik-elena** [comment]
We decided to go for an extra info encoded inside message (e.g. in JSON format). We will introduce internal parameter for the rule so that outside SonarJS the message is standard.

**Comment by andrea-guarino-sonarsource** [comment]
Although we now support secondary issue locations for eslint-based rules, we decided to postpone migration of `cognitive-complexity` rule because the ruling results between the two implementations (Java based and ESLint based) were too different.
We would need more time and care to review those differences (for example regarding AMD modules, function nesting...).

**Comment by vilchik-elena** [comment]
I've reviewed the differences, and even if they are many, they are mostly making sense. Even if the new implementation is not taking into account some frameworks for modules (like AMD),  the new implementation is the only one we will have:
* for TS
* for JS
* for metric
* for rules
* for ESLint plugin

[The current implementation](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/b6b03ec6f4d9b430abea6459c95579ba8a8c0037/src/rules/cognitive-complexity.ts#L22) is ignoring nested function inside function if the outer function does not have any complexity (no `if`, loops etc), `&&` and `||` are allowed. In this case complexity of inner functions will be computed separately, not as part of inner function.
