### ISSUE TITLE
Rule S3626: Jump statements should not be redundant

### ISSUE THREAD

**Issue by andrea-guarino-sonarsource** [SonarSource/SonarJS#1083]
[RSPEC-3626](https://jira.sonarsource.com/browse/RSPEC-3626)

Depends on https://github.com/SonarSource/eslint-plugin-sonarjs/issues/80
To be integrated as eslint-based rule

**Comment by yassin-kammoun-sonarsource** [comment]
Fixed with #1510 and #1724.
