### ISSUE TITLE
Enable ESLint-based rules in SonarLint

### ISSUE THREAD

**Issue by andrea-guarino-sonarsource** [SonarSource/SonarJS#1095]
Since we are having some performance problem, we are not executing ESLint-based rules in SonarLint context so far.
In order to improve performance we should use ContextualServer as in SonarTS and activate ESLint-based analysis on SonarLint.

**Comment by vilchik-elena** [comment]
https://jira.sonarsource.com/browse/MMF-1520

**Comment by vilchik-elena** [comment]
Fixed in #1192
