### ISSUE TITLE
Redundant line in a SonarLint hint in WebStorm

### ISSUE THREAD

**Issue by dskuratovich** [SonarSource/SonarJS#1109]
Hey team! A bit ago I started to use this awesome plugin, so it really helps in preventing many sorts of issue, I love it, definitely! 

But there is one thing I don't like so much, the cause is in double-showing "error description" in SonarLint hint. Let me show that to you, just take a look at the screenshot I have attached.

![image](https://user-images.githubusercontent.com/4585857/46628477-5cceb500-cb46-11e8-96a2-9b626176714a.png)

At this you could see I have two the same lines, is there any possibility to get rid of it?

SonarLint version: 3.5.1.2759
WebStorm version: 2018.2.4

**Comment by vilchik-elena** [comment]
Follow https://jira.sonarsource.com/browse/SLI-318
