### ISSUE TITLE
Misleading warning for alert/confirm/prompt (AlertUseCheck / S1442)

### ISSUE THREAD

**Issue by acdha** [SonarSource/SonarJS#1182]
S1442 reports usage of alert, confirm, and prompt as a vulnerability:

> alert(...) as well as confirm(...) and prompt(...) can be useful for debugging during development, but in production mode this kind of pop-up could expose sensitive information to attackers, and should never be displayed. 

These are [standard features of the web platform](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-confirm) which not limited to debugging and in every case the second part of that sentence is dangerously misleading: if there is sensitive information which can be displayed in an alert, the same attacker can read that information using the browser's developer tools or over the network. Simply removing the pop-up does not change that fact but could lead people to believe that they had fixed a vulnerability by removing the statement and/or switching to a JS dialog implementation when actually doing so would require not giving sensitive information to the client in the first place.

Based on https://jira.sonarsource.com/browse/RSPEC-1442 I think this warning was an overly-broad application of http://cwe.mitre.org/data/definitions/489.html to front-end code and it should probably be a code-smell/accessibility suggestion that you confirm that usage is intentional and appropriate.

**Comment by saberduck** [comment]
@acdha thanks for feedback. I think you are right, we can possibly reclassify this as a hotspot rule https://jira.sonarsource.com/browse/RSPEC-4507 . We are going to discuss internally and change it.

**Comment by acdha** [comment]
Thanks!
