### ISSUE TITLE
My code is not linted by SonarJSLinter

### ISSUE THREAD

**Issue by AndonMitev** [SonarSource/SonarJS#1187]
My code is not linted by sonarjs-plugin-linter. I have been installed "eslint-plugin-sonarjs": "^0.2.0", also in my eslintrc.json at plugins i have been plugged "sonarjs" and in extends i have been imported "plugin:sonarjs/recommended", but still my code is not linted by sonarjs plugin linter

**Comment by vilchik-elena** [comment]
Do you see issues lint messages from other eslint rules, not part of eslint-plugin-sonarjs?
How do you launch analysis?

**Comment by AndonMitev** [comment]
Good morning. No i don't see any issues or messages from other eslint-rules

**Comment by vilchik-elena** [comment]
so why are you here then?:) probably there is some problem with your eslint set up. Try stackoverflow
