### ISSUE TITLE
Custom `confirm` function is improperly identified as `Window.confirm`

### ISSUE THREAD

**Issue by kaiyoma** [SonarSource/SonarJS#1206]
**I want to report a bug.**

**SonarJS version:** 5.2.0-SNAPSHOT (built from source as of 2/25/2019)
**SonarQube version:** 7.4.0.18908

**Rule key:** "alert(...)" should not be used

**Reproducer** 
```js
import { confirm } from 'my-library';
confirm(...); // False-positive here
```

**Expected behavior**
SonarQube should not identify the above code as a vulnerability.

**I want to provide the following feedback.**
The parser/linter should recognize that I'm invoking a different `confirm` function, not the one built into `Window`. I wouldn't be surprised if this also affects calls to custom `alert` and `prompt` functions.

**Comment by vilchik-elena** [comment]
will be fixed with https://github.com/SonarSource/SonarJS/issues/1078
