### ISSUE TITLE
i have an SonarJS 5.0.0.696 is it compatiable to scan .js files in Sonarqube with 6.7.1 version

### ISSUE THREAD

**Issue by saik54** [SonarSource/SonarJS#1226]
**SonarJS version:** <br> 5.0.0.696
**SonarQube version:** <br> 6.7.1
**SonarLint version:** <br> Don't know

I am trying to run the build with these gradle.properties: 

sonar.sources=.
sonar.language=js
sonar.javascript.file.suffixes=.js

I see the that build is success and in Sonarqube also i can see it. But, I can't see the >js files in Sonarqube code.

**Comment by vilchik-elena** [comment]
Please show logs of your analysis

**Comment by saik54** [comment]
> Please show logs of your analysis

Hi elena Thanksnfor reply. Just can you make sure that SonarJS 5.0.0 is compatible for sonarqube6.7.1 community version

**Comment by vilchik-elena** [comment]
it's compatible
