### ISSUE TITLE
"Add or update the header of this file" issue with Js

### ISSUE THREAD

**Issue by z07713** [SonarSource/SonarJS#1235]
Please help me deal with this isse, what would be the accepted format?
Thank you!
[https://imgur.com/a/AJVwUMu](https://imgur.com/a/AJVwUMu)

**Comment by saberduck** [comment]
@z07713 that depends on the configuration of the rule on your SonarQube instance. Its rule `javascript:S1451`  https://rules.sonarsource.com/javascript/RSPEC-1451
