### ISSUE TITLE
Custom JSX, expression on attribute value in *.jsx files crash JavaScript analysis

### ISSUE THREAD

**Issue by holblin** [SonarSource/SonarJS#1260]
**I want to request a feature.**

When we have a custom JSX with expression in the attribute value, the JavaScript analysis crash.
Eg: `<repeat collection={ MapObject } as={ key, value }>`

This is a following issue of: https://github.com/SonarSource/SonarJS/issues/1031

**Comment by vilchik-elena** [comment]
Hello,

Unfortunately we don't accept changes of our parser as we are gradually migrating to ESLint frontend (babel or espree). Now already some rules are executed based on ESLint frontend, more and more will be moved from java-based frontend.
