### ISSUE TITLE
Typescript S4328 - Some explanation

### ISSUE THREAD

**Issue by arnaudforaison** [SonarSource/SonarJS#1270]
**I want to understand why this rule only exist in Typescript rules and not in js, and reasons of this rule**

**S4328:** 
Some front-end library came with some sub dependencies, but if I use this sub-dependency, I have a major Sonar code smell (Sonar way recommended). 
Same case if my project set ts param _"baseUrl": "src"_ to use import with absolute path without useless _src_

**Example:**

In this example, I use emotion library, installed with `npm i @emotion/core`, and I must use theming feature (emotion-theming dependency) that came from devDependencies of @emotion/core

![Groupe 23](https://user-images.githubusercontent.com/1309516/60188254-44ffa400-982f-11e9-9fcf-09c6f2db2d3f.jpg)

Thanks for your help

**Comment by vilchik-elena** [comment]
As far as I can see no good reason.
In fact in TS analyser results for that rule are coming from TSLint (no-implicit-dependencies), so we didn't develop it ourself. 

For JS analyser we plan to migrate to use some ESLint rules under the hood, so if similar rule is available there, we might include it.

**Comment by arnaudforaison** [comment]
Maybe I must say a screw-up but TSLint migrate into ESLint. So maybe TS analyser must fit ESLint rules as soon you migrate JS Analyser.

This rule is a load for me, I will read some reason about it in TSLint discussion.

Have you a plan to communicate about your JS Analyser migration ?

**Comment by vilchik-elena** [comment]
I'm not sure what do you mean by "communicate".

Here are some next steps we foresee on this topic:
https://jira.sonarsource.com/browse/MMF-1521
and 
https://jira.sonarsource.com/browse/MMF-1682

**Comment by arnaudforaison** [comment]
After discussions, our team decide to explicit add dependencies into package.json but we have still a problem.

In tsconfig file, I set _baseUrl_ to _src_ and use Sonar use it tsconfig file but Sonar doesn't matter about this properties and detect absolute path into src as dependencies.
I can't explicit dependency into package.json in this case.

How sonar analyser use _baseUrl_ property during his analyze ?

**Comment by vilchik-elena** [comment]
@arnaudforaison if you have trouble using rule for TypeScript please create issue there

**Comment by arnaudforaison** [comment]
#https://github.com/palantir/tslint/issues/4679
