### ISSUE TITLE
Add static analyzer documentation

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/SonarJS#1272]
This is for migrating the plugin docs from the SQ repo inside each plugin. It should be an `md` file inside the `static` folder.

See [MMF-1770](https://jira.sonarsource.com/browse/MMF-1770) for more details.

Before doing that SonarQube has to be ready to read the documentation, i.e. [MMF-1668](https://jira.sonarsource.com/browse/MMF-1668) should be closed.

**Comment by vilchik-elena** [comment]
We need to update doc for TS:
* property for Node
* version of TypeScript

**Comment by nicolas-harraudeau-sonarsource** [comment]
@vilchik-elena Shouldn't this doc be in SonarTS? As mentioned earlier this will avoid having a ["Typescript" page](https://docs.sonarqube.org/latest/analysis/languages/typescript/) in SonarQube/SonarCloud + a Javascript/Typescript page. SonarQube only allows one page per plugin at the moment and there is already a Typescript page.

**Comment by vilchik-elena** [comment]
@nicolas-harraudeau-sonarsource it's an implementation detail, we will see later how to do it better.
There is one option we consider:
* SonarJS will provide doc for TS
* That way JS page will stay the same (and in fact nothing to update there), and TS page will be up to date
* documentation will not be added to legacy SonarTS, we don't want bring any new features to that artifact
