### ISSUE TITLE
Add support the "Optional catch binding" and other almost stable proposals

### ISSUE THREAD

**Issue by MrEfrem** [SonarSource/SonarJS#1274]
**I want to request a feature.**

Add support the `Optional catch binding` (It was `Stage 4` one year ago):
1. https://github.com/tc39/proposal-optional-catch-binding
2. https://github.com/tc39/proposals/blob/master/finished-proposals.md

Because currently I get an error on such syntax:
```
} catch {
...
```

Also I want to use https://github.com/tc39/proposal-optional-chaining which is `Stage 3`. How?

**Comment by MrEfrem** [comment]
ES2019 changes: https://blog.tildeloop.com/posts/javascript-what%E2%80%99s-new-in-es2019

**Comment by craigmiller160** [comment]
I would also be very interested in hearing what sonar plans to do about this.

**Comment by MrEfrem** [comment]
Can you estimate as soon we will be able to see support of these features?
When will be resolved this issue?
https://github.com/SonarSource/SonarJS/issues/1754
Now I use syntax `service?.is_static_id` and your parser skip so files: `ERROR: Unable to parse file: ...`

**Comment by MrEfrem** [comment]
I updated the sonarqube server to 8.2 and the sonarscanner and I don't see that error anymore. Great work, thanks.

**Comment by zshlomyz** [comment]
Hi,
My company use sonarqube server version 6.7.5 (build 38563).
How can I support the optional chaning using this version?
Thanks
