### ISSUE TITLE
Error parsing valid es2015 javascript

### ISSUE THREAD

**Issue by lukeapage** [SonarSource/SonarJS#1277]
**I want to report a bug.**

**SonarJS version:** 5.0.0.6962
**SonarQube version:** 7.6

**Reproducer** 
```
    const filterFunc = a.b(instrument)
        ? (v) => v
        : (v) => v >= 0;
```

**Expected behavior**

No parse error

**Comment by yassin-kammoun-sonarsource** [comment]
@lukeapage The recent SonarJS and SonarQube versions can parse the reproducer. Please upgrade your SonarQube setup.
