### ISSUE TITLE
Analyze TypeScript code inside Vue.js single file components

### ISSUE THREAD

**Issue by ndchelsea** [SonarSource/SonarJS#1281]
**I want to request a feature.**
Currently SonarJS supports Javascript in VUE files (single file components), but Typescript is explicitly ignored (see #981)

**Expected behavior**
Typescript should be supported in the same manner that JS is rather than being skipped.

**Comment by vilchik-elena** [comment]
Hi,
there is already this ticket to handle this feature https://jira.sonarsource.com/browse/MMF-1441
Yet I'm not sure when we will take care of it

**Comment by sirago** [comment]
Any update on this?

**Comment by saberduck** [comment]
no update yet, it's on our radar. Also, you don't need to ping us, if there is any update you will see it either here or on the linked JIRA ticket

**Comment by fergardi** [comment]
I'm looking forward this feature as well. We've got several VueJS + Typescript projects and more on the road, and this will be a life saver for our client's code quality requirements.

It has been a while since the last comment on this ticket.

Any news so far? Or any workaround I could take advantage of meanwhile?

Thanks in advance for your great work.

**Comment by yannick-milanetto** [comment]
@fergardi The only workaround i've found so far is to put the typescript code in a dedicated TS file, and to reference it from the Vue file with : `<script lang="ts" src="./myComponent.ts" />`

**Comment by Saganic** [comment]
> @fergardi The only workaround i've found so far is to put the typescript code in a dedicated TS file, and to reference it from the Vue file with : `<script lang="ts" src="./myComponent.ts" />`
> 
> Given the adoption of Typescript nowadays, it's a shame this has not been addressed by the Sonar team :(

This does bypass the issue with TypeScript SFCs but introduces warnings:
`07:52:44.788 DEBUG: Not enough content in 'src/modules/user/user-actions.vue' to have CPD blocks, it will not be part of the duplication detection`

The other thing with this approach is that it really does break the mantra of having SFCs in the first place. All of component's code in the same place etc.

Is there any update on when full support for TypeScript in SFCs will be supported?

**Comment by yassin-kammoun-sonarsource** [comment]
The support for TypeScript in Vue.js single file components is planned for [SonarJS 7.2](https://github.com/SonarSource/SonarJS/milestone/32).

**Comment by agigleux** [comment]
This feature is available on SonarCloud.io

**Comment by 304NotModified** [comment]
Is this also supported now in SonarQube (and which version?)

(I see its 7.2 - But I don't know where to find the plugin version in SonarQube enterprise. Is it somewhere in an admin panel or the logs)
