### ISSUE TITLE
Add S1105 (based on `brace-style`) for JS/TS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1404]
`brace-style` also reports on closing brace before else, we can extend our rule (update JS RSPEC)

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule
- Parameter added to select the enforced brace-style (1tbs, stroustrup or allman).

For default parameter (1tbs):
- **new issues** when the closing brace is not on the same line as the `else`, `if-else`, `catch` or `finally` keyword.
- **new issues** when a statements inside a brace appears at the same line as the opening or closing brace.
