### ISSUE TITLE
Add rule S1533 ('use-primitive-type' in tslint) for TS/JS 

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1426]

**Comment by saberduck** [comment]
`no-new-wrappers` doesn't support reporting usage of JS types like `String` instead of `string`. We have this specified in the RSPEC https://jira.sonarsource.com/browse/RSPEC-4408  , I suggest we implement our rule which supports both TS and JS. @vilchik-elena wdyt?
