### ISSUE TITLE
Add rule S1871 (based on 'eslint-plugin-sonarjs/no-duplicated-branches') for TS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1431]

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule
For TS:
* ignore comments
* correctly apply the exception stated in the [RSPEC](https://jira.sonarsource.com/browse/RSPEC-1871):  the rule is now reporting issues for single line of code in `if` chains without `else`.
