### ISSUE TITLE
Add rule S1874 ('deprecation') for TS 

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1432]
This is a tricky one, investigate rule implementation before applying it (does it work cross-file?)

**Comment by vilchik-elena** [comment]
The problem is that import/no-deprecated is able to detect only trivial cases, when deprecated symbol is imported. Still it's not able to resolve deprecated method calls. So we should write our own rule relying on type-checker. 
Later we can contribute this rule to typescript-plugin for eslint.

**Comment by webmaster128** [comment]
Nice work!

>  Later we can contribute this rule to typescript-plugin for eslint.

Would it be possible to port the rule to https://github.com/typescript-eslint/typescript-eslint? Or would the author and/or copyright holder give permission to directly port to to the BSD-2-Clause licensed typescript-eslint?

**Comment by gund** [comment]
@webmaster128 I've already asked that question in https://github.com/SonarSource/eslint-plugin-sonarjs/issues/150 a while ago but it seems they are not so active in engaging with OS community here...

To address your question - I've already ported this rule into [separate ESlint plugin](https://github.com/gund/eslint-plugin-deprecation) under LGPL 3 license, so you may want to check that out =)

**Comment by snebjorn** [comment]
@vilchik-elena I'm also very interested in
> Later we can contribute this rule to typescript-plugin for eslint.

**Comment by vilchik-elena** [comment]
We will try to contribute the rule to typescript-eslint plugin
