### ISSUE TITLE
Add rule S3512 (based on 'prefer-template') for TS/JS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1449]

**Comment by quentin-jaquier-sonarsource** [comment]
### Changes in the rule:

- Rule was in sonar-way-recommended for TS but not for JS: they are now present for both.

New issues when:

*For JS and TS:*
- more than 2 operands in concatenation expression.

*Only for JS:*
- litteral with less than 6 characters
- others specific cases not documented.
