### ISSUE TITLE
Add rule S4157 (based on '@typescript-eslint/no-unnecessary-type-arguments') for TS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1472]

**Comment by quentin-jaquier-sonarsource** [comment]
There is a Bug in typescript-eslint implementation that make the analysis fail, preventing the whole file from being analysed, we need to wait for an eventual fix, or implement it ourselves.

Problematic code:
`let a: A<number>;`

**Comment by quentin-jaquier-sonarsource** [comment]
Bug is fixed in @typescript-eslint master ([PR](https://github.com/typescript-eslint/typescript-eslint/pull/1007)), as soon as a new release of the plugin is available, we can retry to add this rule based on @typescript-eslint/no-unnecessary-type-arguments.
