### ISSUE TITLE
Stop analysis if TS version is  below 3.2.1

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#1583]
Otherwise we just print ERROR for every file, like here 

https://cirrus-ci.com/task/5738479914319872?command=analyze#L69

which doesn't make much sense for the user.

**Comment by quentin-jaquier-sonarsource** [comment]
In #1384, we decided to print a warning when the version isn't compatible.

However, the full warning contains:

> You may find that it works just fine, or you may not.

I agree that it's not ideal to have an error for every file, but it may happen that it "_works just fine_", do we want to stop the analysis in any case?

**Comment by saberduck** [comment]
with the lower version, it will always fail, `typescript-eslint` will use the API which doesn't exist. I agree that with the higher version it will most likely work
