### ISSUE TITLE
Unit test result does not show on SonarQube Dashboard for Angular Application

### ISSUE THREAD

**Issue by Anjireddy4246** [SonarSource/SonarJS#1619]
**Issue:** Could not able to see the unit tests in the Sonarqube. Coverage details are getting displayed.

**SonarQube Version:** 7.9.1 (With embedded database)
**SonarJS:** 5.2.1

**sonar-project.properties** file
sonar.projectKey=RAZE
sonar.projectVersion=1.0.0
sonar.projectName=RAZE-DS
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.ts.tslint.configPath=tslint.json
sonar.ts.coverage.lcovReportPath=coverage/raze/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml

**Karma.conf.js**
const isDocker = require('is-docker');
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma'),
      require('karma-sonarqube-unit-reporter')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, './coverage/angular-dockerized'),
      reports: ['html', 'lcovonly', 'text-summary'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml','sonarqubeUnit'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    sonarQubeUnitReporter: {
      sonarQubeVersion: 'LATEST',
      outputFile: 'coverage/test-report.xml',
      useBrowserName: false
    },
    customLaunchers: {
      'ChromeHeadless': {
        base: 'Chrome',
        flags: [
          //'--no-sandbox',
          
          isDocker ? '--no-sandbox' : '',
          '--headless',
          '--disable-gpu',
          '--remote-debugging-port=9222'
        ]
      }
    },
    singleRun: true,
    restartOnFileChange: true
  });
};

**test-report.xml file content**
`<testExecutions version="1">
<file path="AppComponent">
<testCase name="AppComponent should have as title 'rpa'" duration="46"/>
<testCase name="AppComponent should create the app" duration="13"/>
</file>
<file path="AppComponent">...</file>
</testExecutions>
<testExecutions version="1">...</testExecutions>`

**Sonar logs**
Injecting SonarQube environment variables using the configuration: sonarqube
[Pipeline] {
[Pipeline] sh
+ /var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarQubeScanner/bin/sonar-scanner
INFO: Scanner configuration file: /var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarQubeScanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /var/jenkins_home/workspace/raze@2/sonar-project.properties
INFO: SonarQube Scanner 4.1.0.1829
INFO: Java 1.8.0_171 Oracle Corporation (64-bit)
INFO: Linux 4.15.0-1047-aws amd64
INFO: User cache: /root/.sonar/cache
INFO: SonarQube server 7.9.1
INFO: Default locale: "en", source code encoding: "UTF-8"
WARN: SonarScanner will require Java 11+ to run starting in SonarQube 8.x
INFO: Load global settings
INFO: Load global settings (done) | time=145ms
INFO: Server id: BF41A1F2-AW1rUt22H5To7g9T7boz
INFO: User cache: /root/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=59ms
INFO: Load/download plugins (done) | time=106ms
INFO: Process project properties
INFO: Execute project builders
INFO: Execute project builders (done) | time=4ms
INFO: Project key: RAZE
INFO: Base dir: /var/jenkins_home/workspace/raze@2
INFO: Working dir: /var/jenkins_home/workspace/raze@2/.scannerwork
INFO: Load project settings for component key: 'RAZE'
INFO: Load project settings for component key: 'RAZE' (done) | time=68ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=120ms
INFO: Detected Jenkins
INFO: Load active rules
INFO: Load active rules (done) | time=4208ms
INFO: Indexing files...
INFO: Project configuration:
INFO:   Excluded sources: **/node_modules/**, **/*.spec.ts, **/*.spec.ts
INFO:   Included tests: **/*.spec.ts
INFO: Load project repositories
INFO: Load project repositories (done) | time=74ms
INFO: 82 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for css: Sonar way
INFO: Quality profile for ts: Sonar way
INFO: Quality profile for web: Sonar way
INFO: ------------- Run sensors on module RAZE-DS
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=108ms
INFO: Sensor SonarCSS Metrics [cssfamily]
INFO: Sensor SonarCSS Metrics [cssfamily] (done) | time=110ms
INFO: Sensor SonarCSS Rules [cssfamily]
INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=3518ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=5ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=15ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=359ms
INFO: Sensor SonarTS [typescript]
INFO: Analyzing 60 typescript file(s) with the following configuration file /var/jenkins_home/workspace/raze@2/tsconfig.json
INFO: 60 files analyzed out of 60
INFO: Sensor SonarTS [typescript] (done) | time=11100ms
INFO: Sensor Generic Test Executions Report
INFO: Parsing /var/jenkins_home/workspace/raze@2/coverage/test-report.xml
INFO: Imported test execution data for 0 files
INFO: Test execution data ignored for 1 unknown files, including:
AppComponent
INFO: Sensor Generic Test Executions Report (done) | time=26ms
INFO: ------------- Run sensors on project
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=28ms
INFO: 30 files had no CPD blocks
INFO: Calculating CPD for 42 files
INFO: CPD calculation finished
INFO: Analysis report generated in 200ms, dir size=202 KB
INFO: Analysis report compressed in 319ms, zip size=133 KB
INFO: Analysis report uploaded in 52ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://{hostname}/dashboard?id=RAZE
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://{hostname}/api/ce/task?id=AW2WCyyjH5To7g9T7dyV
INFO: Analysis total time: 26.247 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 28.201s
INFO: Final Memory: 18M/237M
INFO: ------------------------------------------------------------------------
[Pipeline] }
[Pipeline] // withSonarQubeEnv

Dashboard snapshot
![image](https://user-images.githubusercontent.com/18235636/66197962-080e3d80-e6b9-11e9-89d0-9780f660fdbf.png)

Any help would be greatly appreciated. Thanks in advance.

**Comment by vilchik-elena** [comment]
From your logs:
```
INFO: Sensor Generic Test Executions Report
INFO: Parsing /var/jenkins_home/workspace/raze@2/coverage/test-report.xml
INFO: Imported test execution data for 0 files
INFO: Test execution data ignored for 1 unknown files, including:
AppComponent
INFO: Sensor Generic Test Executions Report (done) | time=26ms
```

Looks like your report contains only 1 file and it's not part of the project

**Comment by Anjireddy4246** [comment]
@vilchik-elena : Thank you for the quick response. Yes, It is only one file. Tests are also being executed. But, Sensor Generic Test Executions Report is not pushing the data to Sonarqube.

Below is the test execution summary

HeadlessChrome 73.0.3683 (Linux 0.0.0): Executed 0 of 2 SUCCESS (0 secs / 0 secs)
[1A[2KHeadlessChrome 73.0.3683 (Linux 0.0.0): Executed 1 of 2 SUCCESS (0 secs / 0.054 secs)
[1A[2KHeadlessChrome 73.0.3683 (Linux 0.0.0): Executed 2 of 2 SUCCESS (0 secs / 0.068 secs)
[1A[2KHeadlessChrome 73.0.3683 (Linux 0.0.0): Executed 2 of 2 SUCCESS (0.084 secs / 0.068 secs)
TOTAL: 2 SUCCESS
TOTAL: 2 SUCCESS
TOTAL: 2 SUCCESS

As I am missing any configuration?

**Comment by vilchik-elena** [comment]
Indeed your report is invalid, SonarQube is not able to match a file by component name. Test execution has nothing to do with that, you should check how you generate this `test-report.xml` file. Check that `karma-sonarqube-unit-reporter` is configured correctly.

**Comment by everton-roliveira** [comment]
The problem is in `sonar.ts.lcov.reportPaths`, change to `sonar.typescript.lcov.reportPaths`
