### ISSUE TITLE
why can't use window.postMessage?

### ISSUE THREAD

**Issue by timmyz** [SonarSource/SonarJS#1675]
Hi,
i think the rule S2819 means we shouldn't make the `targetOrigin` to be `*`. but i checked the following lines, it seems it doesn't allow any `window` like code appear, what's that for? reasonable?
https://github.com/SonarSource/SonarJS/blob/5b92b212983ae11e1c502536642ad3fd43902396/javascript-checks/src/main/java/org/sonar/javascript/checks/PostMessageCheck.java#L52-L55

**Comment by vilchik-elena** [comment]
the code you quotes is just to detect code like `window.postMessage`.
Note that this rule reports [security hotspots](https://docs.sonarqube.org/latest/user-guide/security-hotspots/). We are not pointing at the actual problem but just at place which requires developer attention.
