### ISSUE TITLE
Error in ESLint-based sensor when project path contains special chars

### ISSUE THREAD

**Issue by TorstenKruse** [SonarSource/SonarJS#1684]
We are using Sonar 7.9 LTS. Analysis is triggered via Jenkins Sonar plugin.
When the jenkins job name contains special chars as "(" or space, the js plugin runs into an error.

Job name is "ASB Wartungsapp (develop)"
When we rename the job name, analysis is fine.

`INFO: Sensor ESLint-based SonarJS [javascript]
ERROR: /bin/sh: -c: line 0: syntax error near unexpected token `('
ERROR: /bin/sh: -c: line 0: `node /Users/jenkins/work/workspace/ASB Wartungsapp (develop)/.scannerwork/.sonartmp/eslint-bridge-bundle/node_modules/eslint-bridge/bin/server 62034'
ERROR: Failed to start server (10s timeout)
org.sonarsource.nodejs.NodeCommandException: Failed to start server (10s timeout)
	at org.sonar.plugins.javascript.eslint.EslintBridgeServerImpl.startServer(EslintBridgeServerImpl.java:111)`

**Comment by saberduck** [comment]
hello @TorstenKruse ,

which OS do you use? node process is launched via `/bin/sh -c` only on mac

**Comment by TorstenKruse** [comment]
Yes, it's running on macos.

**Comment by saberduck** [comment]
@TorstenKruse , thanks for reporting this issue, we will fix it in the upcoming release.
