### ISSUE TITLE
S1440 is reporting on entire line (eslint eqeqeq does not provide endColumn)

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1729]

**Comment by vilchik-elena** [comment]
fixed in ESLint 6.4 https://github.com/eslint/eslint/pull/12265

**Comment by vilchik-elena** [comment]
We can't rely on eslint 6.x as it makes analysis 2 times slower. We will keep this bug until we figure out how we can overcome this performance problem

**Comment by yassin-kammoun-sonarsource** [comment]
We have been using ESLint 7.x for a while now, which includes the aforementioned fixed.
