### ISSUE TITLE
S138 TooManyLinesInFunctionCheck: report on function signature, not entire function

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1750]
As we are relying on Eslint for this rule, it's reporting on the entire function, which looks ugly in SonarLint and SonarQube UI. We should probably implement our own rule reporting on function signature (name) only.

**Comment by p3k** [comment]
i am currently stumbling across the [same ugliness](https://community.sonarsource.com/t/reduce-number-of-lines-for-some-issues/18474) and was informed it was resolved in a recent version of the plugin – which seems questionable in view of this issue…

are there any updates on this?

**Comment by henryju** [comment]
Community thread: https://community.sonarsource.com/t/reduce-number-of-lines-for-some-issues/18474
