### ISSUE TITLE
Main README.md needs update?

### ISSUE THREAD

**Issue by milbrandt** [SonarSource/SonarJS#1759]
In the main [Readme](https://github.com/SonarSource/SonarJS/blob/master/README.md)  the reference "SonarTS, our analyzer for TypeScript" seems to be outdated. In the referenced [SonarTS Project](https://github.com/SonarSource/sonarts) we read:
"TypeScript analysis for SonarQube was migrated to SonarJS plugin. This is a legacy repository"

Both Readmes can't be valid at the same time.

Would be good, if a someone with more detailed knowledge could check and update at least the Readme and if possible the main documentation pages. Thanks.

**Comment by vilchik-elena** [comment]
Good point, thanks! I will take of that

**Comment by vilchik-elena** [comment]
done in https://github.com/SonarSource/SonarJS/pull/1761
