### ISSUE TITLE
Create UI warning when coverage report or external issue report file is not found

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1765]

**Comment by ilia-kebets-sonarsource** [comment]
When a coverage report is not found, we log a warning. The user can see on the SQ/SC UI that there is no coverage in the overview tab:
![Screenshot 2023-10-19 at 15 36 37](https://github.com/SonarSource/SonarJS/assets/104737176/4aa278a9-b4fe-4793-bfb8-2497eec86bbf)

**Comment by ilia-kebets-sonarsource** [comment]
this is a feature for SQ/SC, this is not the place for it.
