### ISSUE TITLE
FP S4798: function without body

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1768]
Functions without body should be excluded as it is not possible to add a parameter initializer.

**Reproducer** 
- Function overloads
```typescript
function foo(b?: boolean); // FP, it's not possible to add a parameter initializer here
function foo(b) {
  // ...
} 
```
- Abstract methods

```ts
abstract class A{
    abstract foo(p?: boolean): number; // FP
}
```

- Interface methods
```ts
interface I {
  foo: (b?:  boolean) => void; // FP
}
```

- Function Type
```ts
type Foo = (p?: boolean) => void; //A parameter initializer is only allowed in a function or constructor implementation
```

**Comment by iadcode** [comment]
Are the other two cases listed here related to this issue? https://github.com/SonarSource/SonarTS/issues/823

**Comment by quentin-jaquier-sonarsource** [comment]
> Are the other two cases listed here related to this issue? [SonarSource/SonarTS#823](https://github.com/SonarSource/SonarTS/issues/823)

Good catch @iadcode, I copied the others cases from SonarTS's ticket.
