### ISSUE TITLE
Fix FN S2077 (`sql-queries`): support of typeORM

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#1773]
Support of [typeORM](https://github.com/typeorm/typeorm) for [RSPEC-2077](https://jira.sonarsource.com/browse/RSPEC-2077) 

For both JS/TS

Related to this thread in the community forum:
https://community.sonarsource.com/t/vuln-nodejs-typeorm/17279

Code examples:
https://github.com/SonarSource/security-expected-issues/blob/master/javascript/rules/hotspots/RSPEC-2077/typeorm.ts

Complete list of methods that can accept sensitive string queries (formatted / concatenated):
https://docs.google.com/spreadsheets/d/1zx0UB1no7tRfXUGrmdMg9RnUAYVUCU5XrP4raxNb500/edit#gid=198743399

[RSPEC-2077]: https://sonarsource.atlassian.net/browse/RSPEC-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ilia-kebets-sonarsource** [comment]
this is a hotspot, we can close it
