### ISSUE TITLE
Rule S5542: Encryption algorithms should be used with secure mode and padding scheme

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#1782]
Implements [RSPEC-5542](https://jira.sonarsource.com/browse/RSPEC-5542)

For both JS/TS

Code examples: https://github.com/SonarSource/security-expected-issues/tree/master/javascript/vulnerabilities/RSPEC-5542

* Should raise when substring "CBC" or "ECB" are found in the first argument of crypto.createCipheriv() AND for some alias like AES192 (alias of AES-192-CBC)
* Case insensitive
* The complete list of incorrect algorithms could be found in security-expected-issues

**Comment by svenkubiak** [comment]
It looks like the current implementation does not consider higher hashing algorithms when using RSA. 

Current compliant solution are

```
// Recommended for RSA
Cipher c15 = Cipher.getInstance("RSA/None/OAEPWithSHA-1AndMGF1Padding"); // Compliant
Cipher c16 = Cipher.getInstance("RSA/None/OAEPWITHSHA-256ANDMGF1PADDING"); // Compliant
```

However

`Cipher.getInstance("RSA/None/OAEPWITHSHA-384ANDMGF1PADDING");`

and 

`Cipher.getInstance("RSA/None/OAEPWITHSHA-512ANDMGF1PADDING");`

are **not compliant** even though they use a higher hashing algorithm.

**Comment by eric-therond-sonarsource** [comment]
Hello @svenkubiak 
This rule is not yet implemented in Javascript.

In java the rule is implemented and that's right we are not considering all [the possible hashing algorithms](https://github.com/SonarSource/sonar-java/blob/2a8504690070195c4084ed97206afd10d7e05a1b/java-checks/src/main/java/org/sonar/java/checks/security/EncryptionAlgorithmCheck.java#L76) you describe, thus [a ticket](https://jira.sonarsource.com/browse/SONARJAVA-3316) has been created to fix this.

An issue will be raised when a transformation for the RSA cipher differs from "RSA/None/OAEP*".

Thank you for this relevant report.

Eric
