### ISSUE TITLE
Rule S3330 Creating cookies without the "HttpOnly" flag is security-sensitive

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#1788]
Implements [RSPEC-3330](https://jira.sonarsource.com/browse/RSPEC-3330)

For both JS/TS

Code examples: https://github.com/SonarSource/security-expected-issues/tree/master/javascript/hotspots/RSPEC-3330

**Comment by guillaume-dequenne-sonarsource** [comment]
Not raising issues on Peach on expected-issues, might be worth investigating why.
