### ISSUE TITLE
 Rule S2092 Creating cookies without the "secure" flag is security-sensitive

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#1789]
Implements [RSPEC-2092](https://jira.sonarsource.com/browse/RSPEC-2092)

For both JS/TS

Code examples: https://github.com/SonarSource/security-expected-issues/tree/master/javascript/hotspots/RSPEC-2092

**Comment by guillaume-dequenne-sonarsource** [comment]
Not raising issues on Peach on expected-issues, might be worth investigating why.
