### ISSUE TITLE
Add rule S1697 (NullDereferenceInConditional) for JS/TS

### ISSUE THREAD

**Issue by quentin-jaquier-sonarsource** [SonarSource/SonarJS#1806]
Add rule S1697 (NullDereferenceInConditional) for JS/TS

**Comment by quentin-jaquier-sonarsource** [comment]
See [MMF-1772](https://jira.sonarsource.com/browse/MMF-1772), S2259 might cover this rule.

**Comment by vilchik-elena** [comment]
S1697 is deprecated by null-dereference rule (S2259). So we should extend the rule S2259 to support this case.

**Comment by vilchik-elena** [comment]
Replaced by https://github.com/SonarSource/SonarJS/issues/3123
