### ISSUE TITLE
TypeScript location in SonarLint is not detected correctly in project mixing JS and TS

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#1820]
In SonarLint when project contains both JS and TS files, if the first analyzed file is JS file, we will not attempt to detect TypeScript location, and this detection will not be tried on any other analysis. If user subsequently opens TS file, he will receive the error about missing TypeScript dependency.

TypeScript location is detected on the start of eslint-bridge server, and it is not reattempted after the start. In SonarLint context we should retry detecting TypeScript on every analysis.

**Comment by henryju** [comment]
Is there any schedule to fix this issue? We would like to update SonarJS analyzer in SonarLint, but I think this issue is a blocker.
https://jira.sonarsource.com/browse/SLVSCODE-105

**Comment by vilchik-elena** [comment]
And btw when analyzing project with both JS and TS and JS sensor is executed first it's weird to see logs of TypeScript location there.

**Comment by vilchik-elena** [comment]
Note that when having multi-module project we might end up with the same problem! (see #1817)
