### ISSUE TITLE
Optional chaining introduced in TS 3.7 not supported?

### ISSUE THREAD

**Issue by schlundus** [SonarSource/SonarJS#1826]
Sonar raises an issue for optional chaining stuff introduced in TS 3.7

**SonarTS version:** 2.1 (build 4359)<br>
**TypeScript version:** 3.7.3<br>

**SonarQube version:** 7.9.1.27448
--

**Rule key:** typescript:S905

**Reproducer** 
```
// minimal reproducer if relevant
something like this
foo.bar?.addTo(map);
```

**Expected behavior**
No issue raised

**Comment by schlundus** [comment]
Thanks for your reply, we use SonarJS 6.1 (build 11503)

**Comment by schlundus** [comment]
Here is an example
```
class B {
    public addToMap() {
        // nop
    }
}
class A {
    protected b: B = new B();
    public deInit(): void {
        this.b?.addToMap();
    }
}

let x = {
    y: {
        z: {
            zz: 5,
            foo() {
                // nop
            },
        },
    },
};

let xxx = x?.y?.z?.zz;
x?.y?.z?.foo();
```
which leads to
![grafik](https://user-images.githubusercontent.com/17083185/71235884-bc555280-22fd-11ea-8dc0-5b32448d3b20.png)

**Comment by saberduck** [comment]
@schlundus no, both sonarts and sonarjs are required, although sonarts is just empty artifact needed to facilitate the upgrade (sonarjs declares artificially dependency on sonarts, so marketplace will upgrade both plugins automatically, this is to avoid someone upgrading just one plugin, which would fail).

I will have a look at the issue after holidays (unless someone else steps in)

**Comment by quentin-jaquier-sonarsource** [comment]
Hello @schlundus ,

This issue looks similar to [this one](https://community.sonarsource.com/t/typescript-3-7-2-null-conditional-operator-on-a-function-call-is-giving-a-false-positive/17791), I believe you will find an answer here.

**Comment by i-gk** [comment]
Hello,

Do we have a release candidate that resolve this issue?

**Comment by saberduck** [comment]
Yes, latest release should fix it, you can find the jar here https://github.com/SonarSource/SonarJS/releases/tag/6.3.0.12464 , it will be part of SonarQube 8.5 (eta end of september)
