### ISSUE TITLE
Change S1172 (UnusedFunctionArgument) to match TS compiler behavior (new rule for TS)

### ISSUE THREAD

**Issue by quentin-jaquier-sonarsource** [SonarSource/SonarJS#1832]
When migrating rule [S1172](https://jira.sonarsource.com/browse/RSPEC-1172) to the new front-end (#1822), we observed that the current rule scope is fine for JS, but not good enough to enable it for TS.

We also realized that TS compiler provides an option (noUnusedParameters), to report unused parameter. Ideally, our rule should match this behavior. Since we want to avoid having two implementations, and the fact that this also works well for JS, we should make it as the default one.

**When this behaviour is changed, we should add the rule to the recommended profile.**

_For reference, the behavior of TS compiler is the following:_
- Report any unused parameter, including ones that are before an other used parameter.
- Parameter prefixed with underscore are ignored.

**Comment by saberduck** [comment]
Once this is fixed, we should assign the rule to the SonarWay Recommended profile

**Comment by yassin-kammoun-sonarsource** [comment]
> Once this is fixed, we should assign the rule to the SonarWay Recommended profile

No longer true since we dropped the profile.
