### ISSUE TITLE
Is Node.js available during analysis?

### ISSUE THREAD

**Issue by UnderFenex** [SonarSource/SonarJS#1845]
Setup:

SonarQube 7.9.1
Code Analyzer for CSS: 1.1.1 (build 1010)
Code Analyzer for JS : 6.1 (build 11503)
When I run an analysis regarding CSS or JS code, I get the error that SonarQube can’t find Node.

I’ve installed nodejs
I’ve added this line: sonar.nodejs.executable=/usr/bin/node. At the end of /opt/sonarqube/conf/sonar.properties
Added node to path (~/.bashrc): PATH="$HOME/.local/bin:$HOME/bin:/usr/bin/node:$PATH"
However it keeps showing this error.

**Comment by vilchik-elena** [comment]
Please provide debug logs (run scanner with `-X`).
`sonar.nodejs.executable=/usr/bin/node` should be in project properties file `sonar-project.properties`

**Comment by UnderFenex** [comment]
Installing node in each of the running scanning PC's solved the issue.

Thanks @vilchik-elena
