### ISSUE TITLE
Add rule S2392 (WrongScopeDeclarationCheck) for JS/TS (new rule for TS)

### ISSUE THREAD

**Issue by quentin-jaquier-sonarsource** [SonarSource/SonarJS#1856]

**Comment by quentin-jaquier-sonarsource** [comment]
[block-scoped-var](https://github.com/eslint/eslint/blob/master/lib/rules/block-scoped-var.js) implementation in eslint core cover the case where a variable is used outside of the scope declaration, but not the other way, when a var should be declared in lower scope.

We have to implement our own rule.

**Comment by vilchik-elena** [comment]
The part of the rule with reports vars which should be declared in lower scope is really noisy and does not bring a lot of value.
We decided to limit the rule to cover only the case where a variable is used outside of the scope declaration, that way we can use eslint's block-scoped-var and activate rule in default profiles.

**Comment by vilchik-elena** [comment]
Eventually we implemented our rule based on `block-scoped-var` as it has some drawbacks: reporting on references (thus can be many for one variable), reporting twice in variable is declared twice.
