### ISSUE TITLE
Migrate rule S2432 (ReturnInSetterCheck) for JS

### ISSUE THREAD

**Issue by quentin-jaquier-sonarsource** [SonarSource/SonarJS#1858]
Double check with https://eslint.org/docs/rules/no-setter-return if possible to use eslint core implementation.

**Comment by andrea-guarino-sonarsource** [comment]
Note that the rule doesn't apply to TS because the compiler already report this as error

**Comment by saberduck** [comment]
Migration was reverted in because we had to revert to eslint 6.6 https://github.com/SonarSource/SonarJS/commit/983540cced53ae8a5489f360b75881902fba93b9
