### ISSUE TITLE
Add rule S2819 (PostMessageCheck) for JS/TS (new rule for TS)

### ISSUE THREAD

**Issue by quentin-jaquier-sonarsource** [SonarSource/SonarJS#1861]
Requires types, will be implemented during [MMF-1772](https://jira.sonarsource.com/browse/MMF-1772)

**Comment by eric-therond-sonarsource** [comment]
RSPEC-2819 description has been modified recently

Implementation ticket for TS/JS here: https://github.com/SonarSource/SonarJS/issues/1772

**Comment by yassin-kammoun-sonarsource** [comment]
Fixed with #2202
