### ISSUE TITLE
Rules yet relying on Java frontend

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1918]
1. - [x] Add rule RSPEC-3525 #1868
1. - [x] Add rule RSPEC-3533 #1869
1. - [x] Add rule RSPEC-3798 #1871
1. - [x] Add rule RSPEC-3827 #1872
1. - [x] Add rule RSPEC-135 #1875
1. - [x] Add rule RSPEC-2432 #1858 - an implementation exists in a new version of eslint core <- default profile
1. - [x] Add rule RSPEC-131 (https://eslint.org/docs/rules/default-case)
1. - [x] Add rule RSPEC-1186 (https://eslint.org/docs/rules/no-empty-function)
1. - [x] Add rule RSPEC-1321 (https://eslint.org/docs/rules/no-with) <- default profile
1. - [x] Add rule RSPEC-1534 (https://eslint.org/docs/rules/no-dupe-keys) <- default profile
1. - [x] Add rule RSPEC-1536 (https://eslint.org/docs/rules/no-dupe-args) <- default profile
1. - [x] Add rule RSPEC-1763 (https://eslint.org/docs/rules/no-unreachable)
1. - [ ] Add rule RSPEC-2189 #2278  (https://eslint.org/docs/rules/no-unmodified-loop-condition) <- default profile, make sure #674 will be fixed
1. - [x] Add rule RSPEC-2251 (https://eslint.org/docs/rules/for-direction) <- default profile
1. - [x] Add rule RSPEC-2376 (https://eslint.org/docs/rules/accessor-pairs)
1. - [x] Add rule RSPEC-2703 (https://eslint.org/docs/rules/no-undef) <- default profile
1. - [x] Add rule RSPEC-2990 (https://eslint.org/docs/rules/no-invalid-this) <- default profile
1. - [x] Add rule RSPEC-3001 (https://eslint.org/docs/rules/no-delete-var) <- default profile
1. - [x] Add rule RSPEC-3358 (https://eslint.org/docs/rules/no-nested-ternary) <- default profile
1. - [x] Add rule RSPEC-3500 (https://eslint.org/docs/rules/no-const-assign) <- default profile
1. - [x] Add rule RSPEC-3531 (https://eslint.org/docs/rules/require-yield) <- default profile
1. - [x] Add rule RSPEC-3796 (https://eslint.org/docs/rules/array-callback-return) <- default profile
1. - [x] Add rule RSPEC-3812 (https://eslint.org/docs/rules/no-unsafe-negation) <- default profile
1. - [x] Add rule RSPEC-3834 (https://eslint.org/docs/rules/no-new-symbol) <- default profile
1. - [ ] Add rule RSPEC-3854 #2279  https://eslint.org/docs/rules/constructor-super, https://eslint.org/docs/rules/no-this-before-super, there are two rules in eslint  <- default profile
1. - [x] Add rule RSPEC-1528 (https://eslint.org/docs/rules/no-array-constructor) <- default profile
1. - [x] Add rule RSPEC-2138 (https://eslint.org/docs/rules/no-undef-init) <- default profile
1. - [x] Add rule RSPEC-2424 (https://eslint.org/docs/rules/no-redeclare) <- default profile
1. - [x] Add rule RSPEC-3735 (https://eslint.org/docs/rules/no-void) <- default profile
1. - [x] Add rule RSPEC-3863 (https://eslint.org/docs/rules/no-duplicate-imports) <- default profile
1. - [x] Add rule RSPEC-139	(https://eslint.org/docs/rules/line-comment-position)
1. - [x] Add rule RSPEC-909 (https://eslint.org/docs/rules/no-continue)
1. - [x] Add rule RSPEC-1131 (https://eslint.org/docs/rules/no-trailing-spaces) <- default profile
1. - [ ] Add rule RSPEC-1314 #2119  (https://eslint.org/docs/rules/no-octal) <- default profile
1. - [x] Add rule RSPEC-1535 #2321 (https://eslint.org/docs/rules/guard-for-in)
1. - [x] Add rule RSPEC-1537 #2322 (https://eslint.org/docs/rules/comma-dangle)
1. - [x] Add rule RSPEC-1774 #2323 (https://eslint.org/docs/rules/no-ternary)
1. - [x] Add rule RSPEC-1788 (https://eslint.org/docs/rules/default-param-last) <- default profile
1. - [x] Add rule RSPEC-3523 #2329 (https://eslint.org/docs/rules/no-new-func)
1. - [x] Add rule RSPEC-3723 #2330 (https://eslint.org/docs/rules/comma-dangle)
1. - [x] Add rule RSPEC-2259 (NPE) #2331 <- default profile
1. - [x] Add rule RSPEC-4165 (redundant assignment) #2332 <- default profile

Require [MMF-1772](https://jira.sonarsource.com/browse/MMF-1772) to be implemented first
1. - [x] Add rule RSPEC-2201 (we already have TS impl) <- default profile
1. - [x] Add rule RSPEC-2870 (we already have TS impl) <- default profile
1. - [x] Add rule RSPEC-3981 (we already have TS impl)
1. - [x] Add rule RSPEC-4043 (we already have TS impl) <- default profile
1. - [x] Add rule RSPEC-2817 #2201 
1. - [x] Add rule RSPEC-2819 #1772 <- default profile
1. - [x] Add rule RSPEC-3403 #2203 <- default profile
1. - [x] Add rule RSPEC-3579 #2204 <- default profile
1. - [x] Add rule RSPEC-3782  #2205 <- default profile
1. - [x] Add rule RSPEC-3785 #2206 <- default profile
1. - [x] Add rule RSPEC-3800 #2207 <- default profile
1. - [x] Add rule RSPEC-3796 #2209 
1. - [ ] Add rule RSPEC-836 (Replace RSPEC-3757 and RSPEC-3758) #2239  <- default profile
1. - [x] Add rule RSPEC-3003 #2210  <- default profile
1. - [x] Add rule RSPEC-3525 #1868 
1. - [x] Add rule RSPEC-3533 #2240 
1. - [x] Add rule RSPEC-2999 #2211 <- default profile
1. - [x] Add rule RSPEC-1154 #1876 
1. - [ ] Add rule New rule  "Arithmetic and comparison operation involving different type should be avoided", see comment (replace RSPEC-3760 and RSPEC-3402)  <- default profile
1. - [x] Drop rule RSPEC-3759 #2208 (low value)

**Comment by saberduck** [comment]
Checking the codebase, following rules still use Java frontend as of now

```
S1314 org.sonar.javascript.checks.OctalNumberCheck ready
S1535 org.sonar.javascript.checks.ForInCheck ready
S1537 org.sonar.javascript.checks.TrailingCommaCheck ready
S1774 org.sonar.javascript.checks.ConditionalOperatorCheck ready
S2189 org.sonar.javascript.checks.LoopsShouldNotBeInfiniteCheck ready
S2259 org.sonar.javascript.checks.NullDereferenceCheck ready
S2260 org.sonar.javascript.checks.ParsingErrorCheck ready
S2432 org.sonar.javascript.checks.ReturnInSetterCheck ready
S3402 org.sonar.javascript.checks.StringConcatenatedWithNonStringCheck ready
S3723 org.sonar.javascript.checks.MissingTrailingCommaCheck ready
S3757 org.sonar.javascript.checks.ArithmeticOperationReturningNanCheck ready
S3758 org.sonar.javascript.checks.ValuesNotConvertibleToNumbersCheck ready
S3760 org.sonar.javascript.checks.NonNumberInArithmeticExpressionCheck ready
S3798 org.sonar.javascript.checks.DeclarationInGlobalScopeCheck ready
S3827 org.sonar.javascript.checks.ReferenceErrorCheck ready
S3854 org.sonar.javascript.checks.SuperInvocationCheck ready
S4165 org.sonar.javascript.checks.RedundantAssignmentCheck ready
```

Following rules use Java frontend, but are deprecated and could be deleted
```
S1145 org.sonar.javascript.checks.IfConditionalAlwaysTrueOrFalseCheck deprecated
S1531 org.sonar.javascript.checks.HtmlCommentsCheck deprecated
S1532 org.sonar.javascript.checks.ConditionalCommentCheck deprecated
S1697 org.sonar.javascript.checks.NullDereferenceInConditionalCheck deprecated
S2508 org.sonar.javascript.checks.SpaceInModelPropertyNameCheck deprecated
S2549 org.sonar.javascript.checks.BackboneChangedIsUsedCheck deprecated
S2550 org.sonar.javascript.checks.ModelDefaultsWithArrayOrObjectCheck deprecated
S2583 org.sonar.javascript.checks.ConditionalUnreachableCodeCheck deprecated
S2611 org.sonar.javascript.checks.UntrustedContentCheck deprecated
S2713 org.sonar.javascript.checks.JQueryVarNameConventionCheck deprecated
S2714 org.sonar.javascript.checks.ElementUsedWithClassSelectorCheck deprecated
S2715 org.sonar.javascript.checks.IdChildrenSelectorCheck deprecated
S2716 org.sonar.javascript.checks.UniversalSelectorCheck deprecated
S2762 org.sonar.javascript.checks.NotStoredSelectionCheck deprecated
S2769 org.sonar.javascript.checks.SelectionTestedWithoutLengthCheck deprecated
S2770 org.sonar.javascript.checks.DeprecatedJQueryAPICheck deprecated
S2873 org.sonar.javascript.checks.CallabilityCheck deprecated
S2898 org.sonar.javascript.checks.ElementTypeSelectorCheck deprecated
S3002 org.sonar.javascript.checks.UnaryPlusMinusWithObjectCheck deprecated
S3271 org.sonar.javascript.checks.LocalStorageCheck deprecated
S3509 org.sonar.javascript.checks.DefaultParameterSideEffectCheck deprecated
S3523 org.sonar.javascript.checks.FunctionConstructorCheck deprecated
S3828 org.sonar.javascript.checks.YieldOutsideGeneratorCheck deprecated
```

**Comment by jvasallo** [comment]
Was this issue resolved by a specific PR? I see the issue is now closed, but not sure if a PR was created/merged that resolves this or if this was closed in general. Thanks everyone for your work/support!
