### ISSUE TITLE
Prefer direct project TypeScript dependency to a transitive one 

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1928]
Project might have a direct TypeScript dependency (located in top level `node_modules`) and a transitive one (located in nested `node_modules`). In this case when searching for a TypeScript dependency we might first find the transitive dependency which has an old version and analysis will not be executed.

See https://github.com/SonarSource/SonarJS/blob/fdc6425a982d78ef9dd62feccdad884ea52a4497/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/eslint/EslintBridgeServerImpl.java#L327-L333

https://community.sonarsource.com/t/error-about-unsupported-ts-version-while-project-is-using-supported-version/15776/7

**Comment by sandro-h** [comment]
Hi @vilchik-elena,

Since this issue causes problems for a number of our projects, I took the liberty to suggest a fix in a PR -> #1970 

If you had more elaborate plans than such quick fix, feel free to decline my simplistic solution :)

**Comment by escalonn** [comment]
this is a blocker for our project

**Comment by vilchik-elena** [comment]
Removing from milestone as we decided to embed our own TypeScript so no need to search for the user-provided one (#2013 )
