### ISSUE TITLE
S4328: covering projects using "baseUrl" compiler option

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1929]
Check this thread for details https://community.sonarsource.com/t/typescript-baseurl-and-relative-paths-configuration-issue-dependencies-should-be-explicit-typescript-s4328/19135

Basically it's possible to say TS compiler the base URL for relative paths when importing and that way avoiding `./` in the import paths

```
import * as foo from "foo"; // here "foo" might be referencing project file "./foo.ts"
```

**Comment by n1kk** [comment]
Any update on this one? 

Also, there's more ways to resolve local modules beside base Url. There's also Typescripts [Path Mappings](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) and [Virtual Directories](https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs), and bundlers can have their own resolvers on top of that, like [Webpack aliases](https://webpack.js.org/configuration/resolve/#resolvealias).

Each project can be configured very uniquely so it can be quite challenging to create a rule that will correctly resolve them all. Maybe in the meantime ability to add some whitelist in `sonar-project.properties` can be implemented? With a list of modules to ignore or a regexp pattern.

**Comment by finnmerlett** [comment]
You can whitelist 'modules' in the settings now:
-> go to your organisation page
-> quality profiles
-> gear icon next to `sonar way` / `sonar way recommended` under TypeScript
-> copy and name your new profile
->  on profile details screen click `Activate More` or the number underneath 'Rules   Active'
-> search for `'dependancies explicit'`
-> click the rule name
-> click the `Change` button next to your new profile
-> type in your absolute root folders as a comma-separated list to make them whitelisted 'modules'.

Don't forget to activate your custom profile!

**Comment by vilchik-elena** [comment]
I see many users reacted with emojis on this old-and-not-yet-fixed issue. Could someone confirm (or confute) that the rule as it is, is usable with `whitelist` parameter specified (as @finnmerlett described)? If yes, I believe we can close this issue as won't fix.

**Comment by jeanphilippelingrand** [comment]
@vilchik-elena `whitelist` doesnt exist https://docs.sonarqube.org/latest/analysis/analysis-parameters/

**Comment by vilchik-elena** [comment]
@jeanphilippelingrand it's a rule parameter, you can change it only in SonarQube/SonarCloud UI

**Comment by vilchik-elena** [comment]
For the reference https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules
