### ISSUE TITLE
istanbul ignore should be a code smell

### ISSUE THREAD

**Issue by romuleald** [SonarSource/SonarJS#1933]
**I want to request a feature.**
I would like to flag as code smell usage of [istanbul ignore](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) that allow to cheat on code covreage

Thanks.

**Comment by vilchik-elena** [comment]
There is a template rule [javascript:S124](https://rules.sonarsource.com/javascript/RSPEC-124) which allows to report based on comment content

**Comment by romuleald** [comment]
I'll take a look on this option, it could be it, thanks @vilchik-elena

**Comment by romuleald** [comment]
Proposed solution is compliant 👍
