### ISSUE TITLE
Avoid deployment if NodeJS is not available

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1937]
Deployment of bundle takes around 30sec and it's a waste of time if later we discover that there is no NodeJS on the machine. It's better to first check for NodeJS

**Comment by saberduck** [comment]
30 seconds are rather abnormal, this happens on Windows due to antivirus settings. I think on linux machines it is much much faster, otherwise we should check how we could make it faster

**Comment by ilia-kebets-sonarsource** [comment]
we have bundled the runtime, so we won't invest efforts in fixing this.
