### ISSUE TITLE
Create one settings category for JS and TS

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1938]
Currently SonarJS analyzer defines 2 categories in the settings: JavaScript and TypeScript (https://github.com/SonarSource/SonarJS/blob/master/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/JavaScriptPlugin.java#L50-L51).

Yet most of settings listed in JavaScript belong to TypeScript as well. So it will make sense to have single `JavaScript / TypeScript` category.

**Comment by JanPretzel** [comment]
Is it possible to use both, JS and TS rules, on a TypeScript project in the meantime?

**Comment by vilchik-elena** [comment]
Hi,

This ticket concerns only UI of SonarQube.
And I don't understand your question

**Comment by JanPretzel** [comment]
> Hi,
> 
> This ticket concerns only UI of SonarQube.
> And I don't understand your question

Hey, thanks for clearing this up. I misunderstood the ticket completely, sorry! I thought it was regarding the quality profiles and the different rules that come with JS vs. TS while there are some rules in the JS set, that I would also like to use in TS.

Sorry again, I should have read that more carefully.

**Comment by vilchik-elena** [comment]
FYI in last release there are ~30 new rules for TS which before were available only for JS. And we plan to add more later. So basically TS/JS rule sets should be almost identical
