### ISSUE TITLE
Make it possible to rely on particular typescript dependency if many available

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1941]
If SQ projects contains several TypeScript dependencies inside with different versions, we are basically taking the random one, which might be older than required. 

Relates to #1817 and #1820

**Comment by colin-mueller-sonarsource** [comment]
Hey @vilchik-elena -- while working on a support ticket, it became clear that `NODE_PATH` is only checked if Typescript can't be found anywhere else. Maybe `NODE_PATH` can take higher precedence when searching for Typescript?

**Comment by vilchik-elena** [comment]
@colin-mueller-sonarsource it's not that easy as we have no control of that order. NODE_PATH is a part of standard dependency resolution in NodeJS.
I think we will eventually add a new property with the path to the typescript or we will package it ourself to not require it from the user.

**Comment by joe-tingsanchali-sonarsource** [comment]
Does #2010 close out this issue?

**Comment by yassin-kammoun-sonarsource** [comment]
@joe-tingsanchali-sonarsource Yes, it does. Thank you for pointing that out.
