### ISSUE TITLE
RSPEC-5750 Allowing HTTP responses caching is security-sensitive

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#1962]
Implements [RSPEC-5750](https://jira.sonarsource.com/browse/RSPEC-5750)

For both JS/TS

Code examples: https://github.com/SonarSource/security-expected-issues/tree/master/javascript/express.js/RSPEC-5750

**Comment by andrea-guarino-sonarsource** [comment]
> In Express.js application the code is sensitive if the helmet nocache middleware is not used

In order to know if helmet middleware is used, we need project level knowledge.

**Comment by eric-therond-sonarsource** [comment]
As discussed, there is no obvious way to detect that web caching is enabled or not for the moment, so the ticket should be closed.
