### ISSUE TITLE
Various improvements to rules

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#1966]
* S1192 (string literal duplicate) - ignore issues in test code, add secondary locations, ignore literals in type definition (e.g. `let x: 'Hello world' = 'Hello world'`) [#2463](https://github.com/SonarSource/SonarJS/issues/2463), [#2464](https://github.com/SonarSource/SonarJS/issues/2464), [#2465](https://github.com/SonarSource/SonarJS/issues/2465)
* ~~S3512 (prefer template) #1943 - ignore when 2 operands (which at least one string literal)~~
* S109 (magic numbers) - ignore TS enums `enum E {A = 37, B = 38  }`, ignore number `2` [#2462](https://github.com/SonarSource/SonarJS/issues/2462)
* S100 (function names) - ignore React components (in JS based on returned JSX, in TS based on returned type of function) [#2467](https://github.com/SonarSource/SonarJS/issues/2467)
* S103 (line length) - ignore jsx attributes which can't be split [#2461](https://github.com/SonarSource/SonarJS/issues/2461)
* S3402 for TS (`+` operands both nums or strings) - a lot of FPs [#2468](https://github.com/SonarSource/SonarJS/issues/2468)
* S3827: add `util` variable to `node` environment [#2466](https://github.com/SonarSource/SonarJS/issues/2466)

**Comment by jschuldes** [comment]
Is there any ETA for the following improvement?
_S109 (magic numbers) - ignore TS enums enum E {A = 37, B = 38 }, ignore number 2_

**Comment by saberduck** [comment]
I think we should break this issue into individual small issues, it would be easier to manage individual improvements

**Comment by yassin-kammoun-sonarsource** [comment]
> I think we should break this issue into individual small issues, it would be easier to manage individual improvements

@saberduck  I created corresponding tickets and added them in milestone [7.3](https://github.com/SonarSource/SonarJS/milestone/33). I will close this meta ticket and remove it from the milestone.

> Is there any ETA for the following improvement?
> _S109 (magic numbers) - ignore TS enums enum E {A = 37, B = 38 }, ignore number 2_

@jschuldes The improvement is planned for milestone [7.3](https://github.com/SonarSource/SonarJS/milestone/33).

**Comment by saberduck** [comment]
thank you @yassin-kammoun-sonarsource
