### ISSUE TITLE
False-positive for project with multiple subprojects : Vue.js

### ISSUE THREAD

**Issue by vmesafernandez** [SonarSource/SonarJS#1979]
Hi there,

I am having the same problem that this developer has : https://github.com/SonarSource/SonarJS/issues/1124

When doing an analysis with the eslint, I have a false positive.
I saw that you put the solution, but it was for a .NET project. (I don't have the .csproj file)

Could it be fixed for a project in Vue.js?

VERSION : 

SonarJS version: 6.2
SonarQube version: 7.9.2
Eslint version :     
    "eslint": "^5.3.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-sonarjs": "^0.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^5.2.3",

sonar-project.properties (extract) : 
#sonar.sources=src
sonar.projectBaseDir=src
sonar.language=js

#Reports
sonar.javascript.lcov.reportPaths=../../test/coverage/report/lcov.info
sonar.eslint.reportPaths=../../test/eslint_report.json
sonar.modules=components, constants, lang, router, services, store, views, utils

#Components
components.sonar.projectBaseDir=components
components.sonar.sources=./
components.test.inclusions=**/*.spec.js , **/*.ispec.js
components.sonar.exclusions=**/*.spec.js , **/*.ispec.js

#Constants 
constants.sonar.projectBaseDir=constants
constants.sonar.sources=./
   [....]

Can I help me, please? : )

**Comment by vilchik-elena** [comment]
Try to move `sonar.eslint.reportPaths` property into properties of each module you define with the value relative to the module
