### ISSUE TITLE
Taking very long time analysing when using spread operator

### ISSUE THREAD

**Issue by eberhm** [SonarSource/SonarJS#1991]
When the SonarJS analizes the following code snippet it takes up to 120 mins to fininsh with the analisys:

```javascript
const mocks = {
  Query: () => ({
    insights: () => ({
      currentCompaniesInsight: () => ({
        ...mockData
      }),
    }),
  }),
}
```

When we change the snippet to the following it works perfectly fine (run takes ~5 mins)

```javascript
const mocks = {
  Query: () => ({
    insights: () => ({
      currentCompaniesInsight: () => mockData,
    }),
  }),
}
```

**SonarJS version:** 6.1 (build 11503)
**SonarQube version:** Version 8.1 (build 31237)

**Comment by vilchik-elena** [comment]
Can you show the logs of long analysis to understand which sensor is stuck?

**Comment by vilchik-elena** [comment]
Ok, so the problem is in the java parser part. As we plan to drop this parser soon (and fully rely on ESLint-compatible parser), I'm afraid we will not fix this problem.

As a workaround you can exclude this file from the analysis.

sorry for this inconvenience!
