### ISSUE TITLE
Parsing failed when empty line is there at the end.

### ISSUE THREAD

**Issue by shabinpshams** [SonarSource/SonarJS#1992]
I am using sonarqube with Angular application and getting the error when running.

ERROR: Error during SonarScanner execution
java.lang.IllegalArgumentException: 2 is not a valid line offset for pointer.

I could see one empty line at the end of the file when I checked.

**Comment by vilchik-elena** [comment]
Which version of analyzer are you using? 
Please post full log, or at least the logs around the failure
Post reproducer file.

P.S. Please read something about how to ask questions (e.g. this link from StackOverflow https://stackoverflow.com/help/how-to-ask). That's great that you are reporting your problems and help us to improve the analyzer but we will not be able to help you with such a poor information.

**Comment by vilchik-elena** [comment]
closing as no answer. Please report on https://community.sonarsource.com/ if still relevant
