### ISSUE TITLE
Unable to find the Open DB connection, Streams in Nodejs

### ISSUE THREAD

**Issue by rajablackhat** [SonarSource/SonarJS#2027]
Hi All, 

I am facing issues with open database connection, streams in nodejs. I checked with the built-in rules of sonarjs and typescript plugins. I didn't see any rules for this issue to resolve. 

We are looking for a plugin / rule to check the open connections, streams . I have added my instance details for your reference. 

Sonarqube : Community Edition
Version : 8.2

Thanks in advance.

**Comment by vilchik-elena** [comment]
hi,

Indeed seems there is no rules on this matter.
if you have ideas of the rules feel free to provide them https://community.sonarsource.com/c/suggestions/rules/13
