### ISSUE TITLE
FP on S905 with expression with comma

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2035]
Statements with comma raise S905 

```

if (render == null) {
 getTextInfo = Canvas.prototype.getTextInfo,
 addText = Canvas.prototype.addText,
 render = Canvas.prototype.render;
}
```

**Comment by andrey-tyukin-sonarsource** [comment]
Is this really an FP? The [documentation of the corresponding ESlint rule](https://eslint.org/docs/rules/no-unused-expressions) explicitly states:

> Sequence expressions (those using a comma, such as a = 1, b = 2) are always considered unused unless their return value is assigned or used in a condition evaluation, or a function call is made with the sequence expression value.

All the other options have been left maximally permissive, if I'm not mistaken:
```
  private static class Config {
    boolean allowShortCircuit = true;
    boolean allowTaggedTemplates = true;
    boolean allowTernary = true;
  }
```
