### ISSUE TITLE
Exclude huge files from analysis

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2037]
Currently we attempt to detect minified files by computing average line length. This is not always sufficient, as some bundles can have standard line size, but they are large overall. This can make `eslint-bridge` unresponsive and block the analysis. We should also exclude very big files from the analysis (threshold to be defined, but I think anything bigger than 512kb is probably generated).

One example offender is this 7MB file in https://github.com/plotly/plotly.py/tree/master/packages/python/plotly/plotlywidget/static

**Comment by andrey-tyukin-sonarsource** [comment]
Some numbers on file sizes in the projects we are using for ITs. Here is the top of the slightly filtered list (stuff that is not obviously minified etc.):

```
260210	./sources/es5-shim/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/@babel/generator/node_modules/source-map/dist/source-map.debug.js
267739	./sources/backbone/test/vendor/jquery.js
268380	./sources/sizzle/external/jquery/jquery.js
270474	./sources/es5-shim/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/ajv/dist/ajv.bundle.js
283567	./sources/es5-shim/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/esprima/dist/esprima.js
287210	./sources/jshint/data/non-ascii-identifier-start.js
331363	./sources/angular.js/i18n/closure/numberSymbolsExt.js
337015	./sources/p5.js/docs/yuidoc-p5-theme/assets/js/vendor/ace-nc/ace.js
374993	./typescript-test-sources/src/searchkit/release/bundle.js
379019	./sources/jshint/tests/unit/parser.js
491357	./sources/angular.js/test/ng/compileSpec.js
542559	./sources/es5-shim/.scannerwork/.sonartmp/eslint-bridge-bundle/package/node_modules/lodash/lodash.js
597747	./sources/sizzle/external/dojo/dojo.js
839548	./sources/angular.js/i18n/closure/datetimeSymbolsExt.js
1103264	./typescript-test-sources/src/emission/Pod/Assets/Emission.js
1262331	./sources/jshint/dist/jshint.js
1262369	./sources/jshint/dist/jshint-rhino.js
1337456	./typescript-test-sources/src/ag-grid/dist/ag-grid.noStyle.js
1432264	./typescript-test-sources/src/ag-grid/dist/ag-grid.js
2401979	./typescript-test-sources/src/console/static/voyager.worker.js
```
I don't understand what the `dojo.js` is or how it has been generated, but it looks otherwise like a reasonable (albeit lengthy) file with 17k lines, which is comprehensible by humans, so maybe 512kB is a bit low?
