### ISSUE TITLE
S3776 (`cognitive-complexity`): secondary locations are hard to understand for boolean expressions

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/SonarJS#2044]
**Context of analyzer execution:** SonarQube/SonarCloud
**Rule key:** [S3776 "Cognitive Complexity of functions should not be too high"](https://jira.sonarsource.com/browse/RSPEC-3776)

**Problem**
When rule RSPEC-3776 adds secondary locations on a boolean expression, it puts multiple locations on some operators instead of putting them where boolean operators really increase the complexity counter. This makes it difficult to understand how cognitive complexity works.

**Reproducer**
With a maximum complexity of 15.
```
function and_or_16(k) {
    const a1 = (k[0] || k[1] && k[2] || k[3] && k[4] || k[5] && k[6]
        || k[7] && k[8] || k[9] && k[10] || k[11] && k[12]
        || k[13] && k[14] || k[15] && k[16]) 
```

This is what the output looks like on SonarQube:
<img width="935" alt="Screenshot 2020-07-27 at 19 56 37" src="https://user-images.githubusercontent.com/40498978/88574938-6559ed80-d043-11ea-95a3-9459d4024caf.png">

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-136
