### ISSUE TITLE
Search for jsconfig.json files and use them when analyzing JavaScript files

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2069]
We should also support `jsconfig.json` which contains the configuration for JS project, same way as `tsconfig.json`

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by ilia-kebets-sonarsource** [comment]
this was reverted with the TSconfig work.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-135
