### ISSUE TITLE
Files not referenced in tsconfig are not analyzed

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2073]
We don't analyze files that are part of the project, but they are not directly referenced in `tsconfig.json`. If we have `tsconfig.json` such as 

```
{
  "files": ["root.ts"]
}
```

where `root.ts` imports another file `module.ts`, which is not referenced in `tsconfig.json` however it is part of the project build

```
import * as m from 'module'
```

`module.ts` will not be recognized as belonging to project by SonarJS. To be able to recognize it as belonging to the project we would need to create the project using TypeScript APIs (`project.getSourceFiles()`), and not only parse `tsconfig.json` file.

As a workaround, project should list all TypeScript files in `tsconfig.json` file

**Comment by thw0rted** [comment]
Hi, as an end-user I'm not sure if I'm reading your description correctly, but I might be having this problem now?  I wrote [a longer description here](https://github.com/SonarSource/SonarJS/issues/2051#issuecomment-1200450533) but the gist is that if I have 3 entries in my `files` array, those 3 files get analyzed but the rest of my project, which is `import`ed from the main entry point, does not.  Given that the fix above is tagged as milestone 8.7, and we're on server 8.9.8, should I expect this to be resolved?
