### ISSUE TITLE
No jar download link for 6.4.X releases

### ISSUE THREAD

**Issue by Franziskus1988** [SonarSource/SonarJS#2151]
Could you please add the missing jars to the assets of the 6.4.X releases?

**Comment by Franziskus1988** [comment]
Additionally there is no possible update shown in sonar marketplace:
![image](https://user-images.githubusercontent.com/5774027/93993846-84e56c00-fd8f-11ea-8959-d59aa47bdb13.png)

Is it related?

**Comment by Franziskus1988** [comment]
And when will the 6.4.X releases published? I really would like to stop spreading `//NOSONAR` comments, because of  #1990

**Comment by saberduck** [comment]
@Franziskus1988 6.4 release was not distributed, because we decided to revert change in Node.JS version requirement. We released 6.5 which is part of SonarQube 8.5 and available on SonarCloud.

We have also just published 6.6 release, which will be available on SonarCloud soon.
