### ISSUE TITLE
prefer-optional rule is incorrect

### ISSUE THREAD

**Issue by mad-gooze** [SonarSource/SonarJS#2165]
**I want to provide the following feedback.**

**Rule key:** prefer-optional

**Example**
prefer-optional requires this declaration
```typescript
interface Person1 {
    name: string | undefined;
}
```
to be rewritten to 
```typescript
interface Person2 {
    name?: string;
}
```

But types `Person1` and `Person2` are different:
```typescript
const person2: Person2 = {}; // this is correct
const person1: Person1 = {}; // this is incorrect, name is missing but required
```

So `Person1` and `Person2` are semantically different.

**Comment by guillaume-dequenne-sonarsource** [comment]
I'm closing this issue that somehow remained opened despite the underlying rule has since been migrated and works as intended.
