### ISSUE TITLE
Rule: Shorthand promises should be used

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2178]
Implements [RSPEC-4634](https://jira.sonarsource.com/browse/RSPEC-4634)

**Comment by guillaume-dequenne-sonarsource** [comment]
Reopening due to reporting issue for long promises:
https://peach.sonarsource.com/project/issues?id=FreeCodeCamp_nodev12&issues=AXTsNI4LizcPDSeW-bmG&open=AXTsNI4LizcPDSeW-bmG
