### ISSUE TITLE
Migrate S2817 to eslint frontend for JS/TS (new rule for TS)

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2201]

**Comment by guillaume-dequenne-sonarsource** [comment]
Reopening due to FPs when the `openDatabase` function is an override:
https://peach.sonarsource.com/project/issues?id=nextjs&issues=AXIIBk3Gfur-rOVhCz6b&open=AXIIBk3Gfur-rOVhCz6b
