### ISSUE TITLE
Migrate S2999 to eslint frontend for JS/TS (new rule for TS)

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2211]
Related: https://github.com/SonarSource/SonarJS/issues/1763

**Comment by guillaume-dequenne-sonarsource** [comment]
Reopening the issue due to FPs on Peach with `this` keyword

**Comment by yassin-kammoun-sonarsource** [comment]
> Reopening the issue due to FPs on Peach with `this` keyword

This [ticket](https://github.com/SonarSource/SonarJS/issues/2261) was created for the issue observed on Peach, implemented, and merged.
