### ISSUE TITLE
Rule S836: Variables should be initialized before use

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2239]
Implements [RSPEC-836](https://jira.sonarsource.com/browse/RSPEC-836)

**Comment by guillaume-dequenne-sonarsource** [comment]
See this comment: https://jira.sonarsource.com/browse/MMF-1772?focusedCommentId=234227&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-234227
This issue should be tackled along with the migration of S3757, S3758, S3760 and S3402.

**Comment by saberduck** [comment]
We decided to postpone implementation of this rule, because the rules which were supposed to be replaced were not deprecated yet - RSPEC-3757, RSPEC-3758, RSPEC-3760, RSPEC-3402
