### ISSUE TITLE
Deprecate Security Hotspots that are noisy for developers or overlap with SQ DE

### ISSUE THREAD

**Issue by agigleux** [SonarSource/SonarJS#2257]
Here is the list of Security Hotspots to deprecate:

* S4829
* S4823
* S4818
* S4817
* S4787
* S4784
* S2255

**Comment by saberduck** [comment]
@agigleux do you have a list of hotspots that are replacing the ones here? Can we already do it, or should we wait until we have all replacement rules implemented?

**Comment by saberduck** [comment]
Also, we plan to release 6.6 rather soon, so perhaps this should go to 6.7

**Comment by agigleux** [comment]
Some will be replaced by more precise Hotspots or Vulnerabilities, some will be simply dropped at some point. So there is no need to wait, we can already deprecate them even with 6.6.
