### ISSUE TITLE
Fix FP S3800 (`function-return-type`): when returning object literals

### ISSUE THREAD

**Issue by guillaume-dequenne-sonarsource** [SonarSource/SonarJS#2276]
S3800 seems to have some FPs when returning object literals along with named types.
Example on Peach:
https://peach.sonarsource.com/project/issues?id=c-family%3Awikipedia-ios-simulator&issues=AXVH6RfWzOHivJfHhRef&open=AXVH6RfWzOHivJfHhRef

**Comment by ilia-kebets-sonarsource** [comment]
the reproducer cannot be found anymore.

**Comment by yassin-kammoun-sonarsource** [comment]
Kinda hard to guess from the issue title a code snippet raising the reported false positive. Let's close this.
