### ISSUE TITLE
FP S4507: should not raise on alert() and debugger;

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#2326]
Following [this discussion](https://discuss.sonarsource.com/t/vulnerability-rating-of-rules-related-to-debug-code/6325), this [rule](https://rules.sonarsource.com/javascript/type/Security%20Hotspot/RSPEC-4507?search=debug) should not raise on `alert()/confirm()/prompt()` or `debugger;` use cases
it's likely not a security-problem.

There is no code smell for these kind of use cases, [this one](https://jira.sonarsource.com/browse/RSPEC-106) doesn't match well. So these use cases haven't been moved to another rule, we should just remove them to not trigger anylonger the rule S4507 in these cases.

**Comment by saberduck** [comment]
Fixed by https://github.com/SonarSource/SonarJS/pull/2438
