### ISSUE TITLE
Support configuration of environment global variables

### ISSUE THREAD

**Issue by guillaume-dequenne-sonarsource** [SonarSource/SonarJS#2358]
Currently, eslint linter configuration of global variables only includes those from `es6`.

Rules such as S3798 and S3827 could have more relevant results (less FPs) for users if they could configure which environment they are using so that we don't raise any issues for their global variables.

See: https://eslint.org/docs/user-guide/configuring#specifying-environments

**Comment by andrea-guarino-sonarsource** [comment]
Fixed in #2357
