### ISSUE TITLE
Create rule: Assertions comparing incompatible types should not be made

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [SonarSource/SonarJS#2363]
[RSPEC-5845](https://jira.sonarsource.com/browse/RSPEC-5845)
[Expected issues](https://github.com/SonarSource/expected-issues/tree/master/javascript/test/RSPEC_5845)
This is part of [MMF-2213](https://jira.sonarsource.com/browse/MMF-2213)

[RSPEC-5845]: https://sonarsource.atlassian.net/browse/RSPEC-5845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MMF-2213]: https://sonarsource.atlassian.net/browse/MMF-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by yassin-kammoun-sonarsource** [comment]
One needs to be careful when reporting the textual representation of a type inferred by TypeScript's compiler.  For example, TypeScript would return `{ a: A, ..., z: Z }[]` for the expression `[{ a: A(), ..., z: Z() }]` while `object[]` not only is shorter but also more meaningful from JavaScript developer's perspective. In that regard, we need to normalise the types before reporting them. To do so, one can take inspiration from [function-return-type](https://github.com/SonarSource/SonarJS/blob/9750665898c4a84044a322752c91ea13811ed53d/eslint-bridge/src/rules/function-return-type.ts#L120-L142), extract that piece of code into a reusable helper function, and eventually extend it.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-133
