### ISSUE TITLE
Replace rules RSPEC-3760 and RSPEC-3402

### ISSUE THREAD

**Issue by guillaume-dequenne-sonarsource** [SonarSource/SonarJS#2375]
New rule to be created: "Arithmetic and comparison operation involving different type should be avoided".

Replaces [RSPEC-3760](https://jira.sonarsource.com/browse/RSPEC-3760) and [RSPEC-3402.](https://jira.sonarsource.com/browse/RSPEC-3402)

**Comment by vilchik-elena** [comment]
The rational behind this replacement is not clear. Closing as won't fix.

**Comment by vilchik-elena** [comment]
Found the comment about rational https://jira.sonarsource.com/browse/MMF-1772?focusedCommentId=234227&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-234227
