### ISSUE TITLE
Sonar Coverage showing 0% and not reflecting in Dashboard

### ISSUE THREAD

**Issue by mohamednazarae** [SonarSource/SonarJS#2439]
Hi Team,

I am getting below logs.

SonarQube - 4.17.0
INFO: Test Coverage Sensor is started
INFO: 17/17 source files have been analyzed
INFO: Analysing [/home/vsts/work/1/s/test/coverage/lcov.info]
WARN: Could not resolve 2 file paths in [/home/vsts/work/1/s/test/coverage/lcov.info], first unresolved path: vue.config.js

We could see that vue.config.js file there in root folder (i.e) under test/vue.config.js 

After that still it showing 0.0% coverage in sonar dashboard. Please help to resolve the error.

I am running all these in Azure DevOps build pipeline and I am using below task in pipeline

  - task: SonarQubePrepare@4
    displayName: "Prepare Sonar Analysis for Frontend"
    inputs:
      SonarQube: 'Sonar'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'TEST:TestFrontend'
      cliProjectName: 'Test Frontend'
      cliProjectVersion: 'branch'
      cliSources: 'test/src'
      extraProperties: |
        sonar.javascript.lcov.reportPaths=test/coverage/lcov.info

Please help!

**Comment by saberduck** [comment]
SonarQube 4.17 is very old version. Please upgrade to more recent version of SonarQube and open a thread on our community forum if still facing the problem https://community.sonarsource.com/
