### ISSUE TITLE
Deprecate SonarWay Recommended quality profile

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2450]
We want to remove SonarWay Recommended profile, as a first step we should change the name of the profile to be `SonarWay Recommended (deprecated)`. 

When this profile is used we should log a warning `SonarWay Recommended profile is deprecated, use SonarWay profile instead`. This warning should be in the logs and UI.

The change should be applied to both JS and TS.

This change should be implemented after SonarWay profile is updated.

**Comment by yassin-kammoun-sonarsource** [comment]
Duplicate with #2569
