### ISSUE TITLE
Ignore d.ts files from analysis

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2451]
We should ignore `.d.ts` files from analysis, they are usually not part of the project and don't contain code to be checked.

Based on feedback https://community.sonarsource.com/t/no-tsconfig-json-file-found-analysis-will-be-stopped/35824/7

**Comment by vodelerk** [comment]
any updates?

**Comment by saberduck** [comment]
@vodelerk if there were any updates, you would see them here. Writing comments like yours is just spamming maintainers of the project and not very helpful.

**Comment by thw0rted** [comment]
Hi, sorry to come to this issue so long after it was closed, but our server only recently updated to the version that incorporates the linked PR.

I'd like to better understand why this change was made.  Our project is primarily typescript and does have a number of `.d.ts` files, which are used to add type declarations to libraries we consume or augment definitions that were incomplete.  These files **are project code**, and Sonar has correctly flagged issues with them in the past.  Now, they're not being analyzed.  This seems like an undesirable regression to me.

(Of course, `.d.ts` files that ship with libraries shouldn't be analyzed, but those should already be caught by exclusion defaults like `**/nodes_modules/**`.)
