### ISSUE TITLE
Analyse TS files without tsconfig

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2506]
In some contexts (ie SonarLint) we don't have `tsconfig` file of project. However, we could still analyze the file. This is already done for JS files and we rely on default project created by @typescript-eslint/parser

**Comment by hosszubalazs** [comment]
Hey @saberduck ! 

Can you please clarify the requirement here? Does a tsconfig.json file have to exist in order for the TS files to be analyzed?

**Comment by saberduck** [comment]
We've decided not to implement this, because having tsconfig file is requirement for any TS project, so the use case of this change is limited only to some toy examples and not relevant for majority of users.
