### ISSUE TITLE
Improve S2814 by distinguishing value exports from type exports

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2509]
Community: https://community.sonarsource.com/t/false-positives-for-rule-typescript-s2814-with-const-and-type/39395

**Comment by DoctypeRosenthal** [comment]
I still get a false positive for interfaces and (function) identifiers:

![image](https://user-images.githubusercontent.com/12626798/116929731-1f2f5b80-ac5f-11eb-8087-4e5eed4377c4.png)

Sonarqube Developer EditionVersion 8.8 (build 42792).

**Comment by jrnail23** [comment]
I'm also still getting this false positive.
<img width="679" alt="Screen Shot 2021-07-03 at 3 36 38 AM" src="https://user-images.githubusercontent.com/392612/124347008-e99be580-dbaf-11eb-9e08-5c56d9708bcc.png">

**Comment by yassin-kammoun-sonarsource** [comment]
@DoctypeRosenthal @jrnail23

Indeed, it seems that the improvement that was implemented recently didn't entirely remove those false positives. I will reopen the ticket, and we will address it as soon as possible.

**Comment by yassin-kammoun-sonarsource** [comment]
I will close this ticket as it was somehow already addresses, and I created a new ticket #2685.
