### ISSUE TITLE
Stop bundling source maps and TS localization files

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2520]
Currently when we create the bundle we include everything in `node_modules` . We should exclude source maps and TS localization in `node_modules/typescript/loc` to make bundle smaller.

![](https://i.redd.it/tfugj4n3l6ez.png)

**Comment by andrea-guarino-sonarsource** [comment]
I'll share briefly the outcome of my investigation.

- I didn't find an easy way to prevent `npm pack` including source maps and TS localization files. I tried adding [`.npmignore`](https://docs.npmjs.com/cli/v7/using-npm/developers#keeping-files-out-of-your-package) to exclude those:
```
**/*.map
node_modules/typescript/loc
```
However the first line only excludes file of the project source code (not the bundled dependencies), while the second doesn't 
have any effect.

- [`rollup`](https://rollupjs.org/guide/en/) bundler: I managed to have a rollup configuration running (see [branch](https://github.com/SonarSource/SonarJS/tree/issue-2520-rollup)) , however starting node server produces runtime exception on third-party code. 

In my opinion, relying on a module bundler like rollup to bundle both project code and dependencies is a too fragile approach: JavaScript is very dynamic in its nature and I'm afraid the bundler might cut out some code that might be eventually needed at runtime.
Moreover, the cost of maintaing a module bundler is quite high: every time we add a dependency we should run and potentially trouble-shoot problems within the bundling process.

**What I didn't try yet**

It might be interesting to manually remove source maps and TS localization files from the tarball.
However, I'm not sure the work of implementing such post-packaging hook is worth the investment. Also, it might need to be maintened whenever TS changes localization files.
