### ISSUE TITLE
TypeScript sensor should skip analysis if no input files are found

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2617]
Due to change in #2590 we invoke `TypeScriptSensor` even if there are only JS files in the project. Consequently there will be no files to analyze, however we anyway create default empty `tsconfig.json` with empty `files: []` property and then we invoke typescript compiler to provide all the (nonexistent) files for the project. TypeScript compiler prints error that `files` property is empty 

```
"The 'files' list in config file 'tsconfig.json' is empty."
```

This is printed as `ERROR` which stops the build because of Azure DevOps default behavior.

Fix should be to exit TypeScript Sensor as soon as we find out that there is nothing to analyze.

**Comment by juannunez0906** [comment]
@saberduck just for clarification this Error should still display but then it skips the analysis correct?

**Comment by saberduck** [comment]
@juannunez0906 no, the error is not displayed anymore

**Comment by juannunez0906** [comment]
@saberduck I am still getting this error 
![image](https://user-images.githubusercontent.com/60671719/121384732-88695500-c916-11eb-9e09-3e4d0e057225.png)

**Comment by Anil2214** [comment]
@saberduck i'm also getting the same error

**Comment by saberduck** [comment]
@Anil2214 , @juannunez0906 please provide more details on which version of SonarQube do you use? This fix was included in the SonarQube 8.9.1 which was released recently, and it was deployed on SonarCloud in the last week.

**Comment by Anil2214** [comment]
@saberduck I'm using SonarQube 8.9 .

**Comment by Anil2214** [comment]
@saberduck we updated it from version 7.9.1 to 8.9 . Two days back and started getting this issue

**Comment by saberduck** [comment]
@Anil2214 you should upgrade to 8.9.1 there was a patch release last week

**Comment by Anil2214** [comment]
@saberduck I am getting this error as well ##[error]ERROR: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["../Bundles"]'****. is it also because of the above issue??

**Comment by saberduck** [comment]
@Anil2214 I don't think this is related. please create a post on https://community.sonarsource.com/and provide all relevant info

**Comment by juannunez0906** [comment]
@saberduck I will make double check to make sure we are on the 8.9.1 version and will post if we still get the error otherwise thank you for the help!
