### ISSUE TITLE
Rule S6268: Disabling Angular built-in sanitization is security-sensitive

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2618]
We should detect following functions from Angular's `DomSanitizer` object as security hotspot [S6268](https://jira.sonarsource.com/browse/RSPEC-6268)

```
DomSanitizer.bypassSecurityTrustHtml(value: string)
DomSanitizer.bypassSecurityTrustStyle(value: string)
DomSanitizer.bypassSecurityTrustScript(value: string)
DomSanitizer.bypassSecurityTrustUrl(value: string)
DomSanitizer.bypassSecurityTrustResourceUrl(value: string)
```

Related rule S5247 is about disabling escaping in the **whole** application, so this is another rule.

**Comment by pierre-loup-tristant-sonarsource** [comment]
@vilchik-elena I think we should filter out this use case as it's an obvious FP:

```
sanitizer.bypassSecurityTrustHtml("<p>Hello</p>"); // Compliant: hard-coded string can be trusted
sanitizer.bypassSecurityTrustHtml(`<p>${hello}</p>`); // Sensitive: string can be trusted
```

Should I create a separate ticket?

**Comment by vilchik-elena** [comment]
@pierre-loup-tristant-sonarsource no, I will update implementation to exclude those cases
