### ISSUE TITLE
Do not mention custom rules when deploying security frontend

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2625]
Currently we print following logs when deploying security frontend custom rules:
```
INFO: Sensor JavaScript analysis [javascript]
INFO: Deploying custom rules bundle jar:file:/home/ganncamp/.sonar/cache/1c0d0d6d358b2ff25a27998c60079e2e/sonar-securityjsfrontend-plugin.jar!/js-vulnerabilities-rules-1.0.0.tgz to /home/ganncamp/testProjects/javascript/juice-shop/.scannerwork/.sonartmp/eslint-bridge-bundle/package/custom-rules1939007438647855735
INFO: 5 source files to be analyzed
INFO: 5/5 source files have been analyzed
```

This definitely might sound confusing for the user to know that some "custom" rules are provided by analyzer as they are not.

We should reword this technical details and/or hide them in debug logs.

**Comment by saberduck** [comment]
Is this coming from internal feedback?

**Comment by vilchik-elena** [comment]
Yep, https://discuss.sonarsource.com/t/custom-rules-for-js-analysis/7683/2
