### ISSUE TITLE
FP on S2819 should only raise on the message type of event

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [SonarSource/SonarJS#2666]
A lot of SonarCloud users complain about this rule: 
* https://sonarcloud.io/project/issues?id=CorruptComputer_BookStack&issues=AXmjlsbTnxEHvUM0ZLpK&open=AXmjlsbTnxEHvUM0ZLpK
* https://sonarcloud.io/project/issues?id=CorruptComputer_BookStack&issues=AXmjlsZ3nxEHvUM0ZLok&open=AXmjlsZ3nxEHvUM0ZLok

We should raise an issue on `window.addEventListener` only if the first argument is a literal string equals to "message"

```
window.addEventListener("message", function(event) { // Noncompliant: no checks are done on the origin property.
      console.log(event.data);
 }); 
```

```
window.addEventListener("onClick", function(event) { // Compliant (FP today)
      console.log(event.data);
 }); 
```

**Comment by DiegoCardoso** [comment]
We also have faced this issue on our project:
- https://sonarcloud.io/project/issues?id=vaadin_web-components&open=AXk3bWgjaNlh6LJanq3v&resolved=false&types=VULNERABILITY

**Comment by lukeapage** [comment]
and false errors on pointerdown

```
window.addEventListener('pointerdown', handlePointerDown, true);
```

**Comment by dvag-joerg-toelstede** [comment]
We have also a problem with this in our project (Angular with Typescript):
`this.window.addEventListener('beforeinstallprompt', e => {})
this.window.addEventListener('appinstalled', e => {})`

Both lines throw an "Verify the message's origin in this cross-origin communication".

We have already updated to the current version "Enterprise Edition Version 8.9.6 (build 50800)".

Do we have a wrong version?

**Comment by vilchik-elena** [comment]
@dvag-joerg-toelstede yes, you need latest version (which is 9.x), not LTS.

**Comment by sgtwilko** [comment]
@vilchik-elena  Any chance this can be backported into LTS?

**Comment by vilchik-elena** [comment]
@sgtwilko sorry, no

**Comment by mmitchell-w** [comment]
I was having this false positive with
```javascript
window.addEventListener('popstate', (event) => {
```
and found this workaround
```javascript
window.onpopstate = function(event) {
```

**Comment by tomaso** [comment]
How can I tell which version of SonarQube contains this fix? 
I tried to browse through release notes mentioned in https://docs.sonarqube.org/latest/setup/upgrade-notes/ but I don't see S2819 being mentioned there.

**Comment by monkpit** [comment]
If anyone lands here and cannot update their own SonarQube version to avoid this issue, it may be possible to change your event from targeting `window` to target `document` instead.
