### ISSUE TITLE
Remove S4326 from default profile and improve its description

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2674]
Currently rule S4326 (https://eslint.org/docs/rules/no-return-await) is part of default profile. But the rule gives bad recommendations if performance is not that important while stack traces are. So probably we should remove the rule from Sonar Way profile and also improve description mentioning when rule should be activated.

**Comment by vilchik-elena** [comment]
https://community.sonarsource.com/t/await-should-not-be-used-redundantly-affecting-stacktraces/44531

**Comment by ilia-kebets-sonarsource** [comment]
Fix: https://github.com/SonarSource/rspec/pull/1312

**Comment by yassin-kammoun-sonarsource** [comment]
@ilia-kebets-sonarsource Once you merge https://github.com/SonarSource/rspec/pull/1312, could you check whether we manually need to remove the rule number from https://github.com/SonarSource/SonarJS/blob/1fccda81b95decaff134206ebbbeaca72bb035e1/javascript-checks/src/main/resources/org/sonar/l10n/javascript/rules/javascript/Sonar_way_profile.json#L136

I don't remember if the rule API does it automatically when updating the metadata.
