### ISSUE TITLE
S4328 (no-implicit-dependencies): check package.json files in all levels up

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2682]
Currently we stop as soon as one package.json is found, yet NPM will search the dependency up until it finds it or the root is reached. This problem is common for monorepo projects.

Reported in https://community.sonarsource.com/t/dependencies-only-searched-one-package-json-up/42816

**Comment by derhecht** [comment]
also in non-monorepo projects this happens quite regularly. we just have two package.json files in tree and got those false messages because of it.

**Comment by dotku** [comment]
Any solution to ignore a certain package?

**Comment by yassin-kammoun-sonarsource** [comment]
Hello @dotku,

You can use the rule parameter `whitelist`, which expects a comma-separated list of modules to ignore while checking in package.json.

**Comment by mike-fam** [comment]
Hi, any updates on this issue?
