### ISSUE TITLE
Fix FP on S2814 (`no-redeclare`): when mixing export kinds

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2685]
We need to better filter out redeclared symbols that are exported according to their kind (value v.s. type). A previous work attempted to address the problem of exported symbols as values redeclared by exported symbols as types. However, because of the way the rule is implemented, the previous fix turns out to be insufficient as we are only able to ignore this pattern:

```typescript
export var T = 'foo';
export type T = number;
```
but we still raise issues on that one:

```typescript
export type T = number;
export var T = 'foo';
```

The rule decorator should avoid being dependent on the exports order and rely on a cache mechanism to do so.

**Comment by ilia-kebets-sonarsource** [comment]
no context
