### ISSUE TITLE
Drop deprecated TypeScript properties

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2758]
- sonar.typescript.node
- sonar.typescript.lcov.reportPaths

**Comment by omio-ma** [comment]
Hi, where do you guys post for breaking changes like this, is it perhaps part of some release notes somewhere I have missed?

**Comment by vilchik-elena** [comment]
@omio-ma https://github.com/SonarSource/SonarJS/releases/tag/8.3.0.16208

**Comment by omio-ma** [comment]
@vilchik-elena thanks for sharing that, so I take SonarJS gets ran when we use the `SonarCloudPrepare@1` task in devops? Is there a property that is used to use not the latest version? 
Referring to this: https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarcloud

Or just so I understand, anytime any changes are made to this, it will get used using that task?

**Comment by vilchik-elena** [comment]
This analyzer is deployed on SonarCloud as soon as it's released (may be it can take couple of days), and you have to use the deployed version

Here https://sonarcloud.io/deploy/plugins/index.txt you can see that latest version is deployed already

**Comment by omio-ma** [comment]
Oh yes, definitely it has been deployed however as a result of this change all our PRs started to fail for few days and turns out no one was aware of this change. I have changed the property now and does appear to be working correctly now.

**Comment by vilchik-elena** [comment]
I am happy you fixed it :) 
In previous analyses you had a warning log saying that you are using property to be dropped soon

**Comment by omio-ma** [comment]
Thanks, we also use the property `sonar.typescript.exclusions` to exclude certain files (like node modules), should that be updated as well?

**Comment by vilchik-elena** [comment]
@omio-ma no, but to be sure have a look at your analysis logs from time to time

**Comment by omio-ma** [comment]
is the analysis log part of the pipeline logs (when running those sonarcloud tasks), or something we can see in sonarcloud web app?

**Comment by vilchik-elena** [comment]
I think when running sonarcloud tasks, there is no logs in sonarcloud web
