### ISSUE TITLE
Rule S6425 [TS only]: Type imports should be used when possible

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2759]

**Comment by yassin-kammoun-sonarsource** [comment]
TypeScript ESLint [consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports/)

**Comment by thw0rted** [comment]
In your first example I think you should be fine with `import { Logger, type LoggerFactory }`, right?

**Comment by ilia-kebets-sonarsource** [comment]
@thw0rted Thanks for the proposition, I'll look into it!

**Comment by ilia-kebets-sonarsource** [comment]
As suggested by @thw0rted, using newer versions of Typescript and Eslint parser and plugin yielded accepting `import { Logger, type LoggerFactory }`. However the quickfix provided by Eslint still refactored it in 2 lines as such:

```javascript
import type { MyType } from "./double";
import { MyClass } from "./double";
```

The dependencies versions are:
- typescript: 4.6
- @typescript-eslint/eslint-plugin: 5.22.0
- @typescript-eslint/parser: 5.22.0

**Comment by ilia-kebets-sonarsource** [comment]
We are putting this rule on hold for now as we only see value in coner cases using Babel, esbuild or other transpiling tools.
The advantage to using it has been partly described in the rspec: https://github.com/SonarSource/rspec/pull/981
