### ISSUE TITLE
"Browserslist: caniuse-lite is outdated" in error output

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2803]
Browserlist is a transitive dependency of @babel-core and has an automatic mechanism which reports when it's outdated. Unfortunately it prints into stderr which might cause issues with certain CI services.

We have same issue with sonar-css https://github.com/SonarSource/sonar-css/issues/370 . We don't actually need this dependency for the analysis and we should look into how to remove it from the package.

```
=> Found "caniuse-lite@1.0.30001251"
info Reasons this module exists
   - "@babel#core#@babel#helper-compilation-targets#browserslist" depends on it
   - Hoisted from "@babel#core#@babel#helper-compilation-targets#browserslist#caniuse-lite"
```

**Comment by saberduck** [comment]
Reported internally https://discuss.sonarsource.com/t/error-browserslist-caniuse-lite-is-outdated/8701/3

**Comment by saberduck** [comment]
You can set env. variable BROWSERSLIST_IGNORE_OLD_DATA=true to avoid the message. I found this in https://github.com/browserslist/browserslist/issues/361#issuecomment-479221925

**Comment by rantoniuk** [comment]
I don't think that ignoring a valid message is a good resolution, especially that as you mentioned that this package is not needed for the scan - it should be better updated (if used) or removed (if unused).

**Comment by khatekar** [comment]
I can fix it locally by `npx browserslist@latest --update-db`, but how should we fix this on the server build, yarn build is failing due to this.
