### ISSUE TITLE
Fix FP on S3403 (`different-types-comparison`): when the variable involved in the check stores values of multiple types

### ISSUE THREAD

**Issue by agigleux** [SonarSource/SonarJS#2819]
I analyzed https://github.com/montulli/GrooveScribe. There are [2 similar bug issues](https://sonarcloud.io/project/issues?id=agigleux_GrooveScribe&open=AXxeqUCf-dDKUnsQ_Kej&resolutions=FALSE-POSITIVE&types=BUG) that are suspicious: the software is working well and should really behave wrongly if what SonarCloud reports is correct.

![image](https://user-images.githubusercontent.com/1057037/136561025-46b6c287-902c-4833-ae4c-2b38e30ab95c.png)

If this example, `prev_hh_note` is initialized with the value 46 like this:

`var prev_hh_note = 46;  // default to open hi-hat so that the first hi-hat note also mutes any previous hh open.`

Then there is a for-loop and finally the code where SonarCloud reports the issue.

I believe this is a FP because:
* we assume that `prev_hh_note` is an integer everywhere and so SonarCloud reports that the comparison with !== won't work and will always return "true"
* whereas `prev_hh_note` can be an integer or a boolean at different moment in the code (yes this is not a good practice but this is what is done in this software) 

If the developer just follow SonarCloud and considers that a condition that is always true can be removed, then the software will have a different behavior.

**Comment by ilia-kebets-sonarsource** [comment]
- maybe improve message
- check rule performance

**Comment by vdiez** [comment]
Leave as is at the moment, not much we can do right now. Probably title could be changed (to what?). Or just drop this rule as is, and add a new rule checking assignments to values with a type not corresponding to declaration type.
