### ISSUE TITLE
Add minJreVersion to manifest for SonarLint

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#2820]
To offer nice UX for SonarLint we should add minJreVersion for SonarLint in the manifest.

We can still stay on Java 8. Requirement to use Java 11 should come later.

see https://xtranet-sonarsource.atlassian.net/wiki/spaces/SL/pages/900577/SonarLint+compliant+plugin+guideline#Advertise-minimal-required-JRE-version (internal link)

**Comment by vilchik-elena** [comment]
fixed in a62dc93492d70f23cab03aeba7c72dba17f32a78
