### ISSUE TITLE
Fix FP S3353 (`prefer-const`): uninitialized variable

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2875]
TypeScript will complain if replace `let` with `const` in the following example
```
let x: Foo; // FP is here

foo(() => { x.foo(); });
x = new Foo();
```

**Comment by vilchik-elena** [comment]
This does not seem to be a common pattern, so may be we can close this ticket as won't fix later

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-123
