### ISSUE TITLE
Create rule: Unused exported values should be removed

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#2941]

**Comment by vilchik-elena** [comment]
https://frontendgirl.com/spring-cleaning-how-to-safely-remove-dead-code-unused-exports-in-js-codebase/

**Comment by vilchik-elena** [comment]
Similar rules is implemented for CFamily https://sonarsource.github.io/rspec/#/rspec/S5536

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-122
