### ISSUE TITLE
Fix FP S1110 `no-redundant-parentheses`: Ignore sequence expressions

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#2995]
The rule S878 raises an issue on the use of the comma operator, in other words in presence of a sequence expression:

```javascript
foo = bar(), baz;   // issue
```

It makes, however, an exception when a sequence expression is explicitly wrapped in parentheses:

```javascript
(foo = bar(), baz); // no issues
```

On the other hand, S1110 inconsistently raises an issue when surrounding a sequence expression between parentheses.

Reported in https://community.sonarsource.com/t/s878-unexpected-use-of-comma-operator/58715

**Comment by JohnGurin** [comment]
As a suggestion, it would be great if an arrow function does not require an additional parentheses when used like this:
```javascript
const fn = () => (foo = bar(), baz)
```
