### ISSUE TITLE
Rely on sonar file system API to discover tsconfig files

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#3034]
Currently we rely on java file system to discover tsconfig files, and we discover those which are excluded by the user

See https://community.sonarsource.com/t/tsconfig-json-in-build-output-causes-error-produces-noise-in-azure-devops/59234/3

**Comment by vilchik-elena** [comment]
Another similar problem https://community.sonarsource.com/t/specifying-sonar-exclusions-for-folder-that-begins-with-a-dot/62101

**Comment by vilchik-elena** [comment]
https://sonarsource.atlassian.net/browse/MMF-2926

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-120
