### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by MadDonkey** [SonarSource/SonarJS#3071]
when I build with command "mvn clean install -Dlicense.skip=true -DskipTests  -X" on master branch(release 7.4.4), I got one error, " 
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (yarn build) on project eslint-bridge: Command execution failed."
my maven version is 3.6.3
java version is 1.8.0_231
yarn version is 1.22.4
node version is v16.14.1
is there anyone can help me to resolve this problem? Your help would be greatly appreciated！

**Comment by saberduck** [comment]
hi, sorry we don't have the bandwidth to fix builds of such old versions of the analyzer.
