### ISSUE TITLE
Improve S2259 (`null-dereference`): consider any kind of nullable target objects

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#3086]
The rule currently limits itself to raising issues on member expressions in which the possibly nullable target object is an identifier:

```javascript
var nullable = /* ... */;
console.log(nullable.bar); 
```

We should extend the scope of the rule and relax this constraint so that it is able to raise on any kind of nullable target objects:

```javascript
var nullable = /* ... */;
console.log(nullable().bar); 
```

**Comment by yassin-kammoun-sonarsource** [comment]
Reported in https://community.sonarsource.com/t/identify-npe-in-typescript-js/60074

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-119
