### ISSUE TITLE
Fix FP S3776 (`cognitive-complexity`): not report on JQuery `document.ready` top-level functions

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#3116]
https://community.sonarsource.com/t/fp-on-javascript-s3776-incorrect-calculation-of-cognitive-complexity/59337/12

**Comment by ilia-kebets-sonarsource** [comment]
linked to https://github.com/SonarSource/SonarJS/issues/3289

**Comment by ilia-kebets-sonarsource** [comment]
This issue will be taken care of by https://github.com/SonarSource/SonarJS/issues/3500
