### ISSUE TITLE
Eslint-bridge process should terminate gracefully when parent process dies

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3131]
In SonarLint context it can happen that parent java process (which starts eslint-bridge Node.js process) dies unexpectetly. Currently eslint-bridge process keeps running as a zombie process. We should implement heartbeat mechanism and if client doesn't issue a request after certain timeout eslint-bridge process should terminate itself gracefully.

**Comment by victor-diez-sonarsource** [comment]
As agreed with @saberduck  @duncanp-sonar:
* Eslint node server should receive a request on /heartbeat to reset the shutdown timeout.
* Shutdown timeout will be hardcoded initially to 15s.
* Sonarlint VSCode will HTTP GET the eslint server every Ns (N < 15).
* SonarJS plugin will HTTP GET eslint every 5s.
* The timeout will be cancelled on any other (non-hearthbeat) new request, and restarted when the response to the request has been sent.

**Comment by victor-diez-sonarsource** [comment]
Finally, the heartbeat will send requests to the existing `/status` endpoint, instead of creating a dedicated `/heartbeat`. Given that any request resets the timeout, we decided it does not make sense to have an exclusive endpoint for this.
