### ISSUE TITLE
Add 'sap' to the list of default global variables

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#3155]
https://community.sonarsource.com/t/sap-ui5-define-template-recognized-as-undefined-variable/63670

**Comment by Haemma83** [comment]
Hello. Is there a timeframe when this issue is going to be fixed? Thx

**Comment by yassin-kammoun-sonarsource** [comment]
Hey @Haemma83, we will include this fix in our next release.
