### ISSUE TITLE
Fix FP `css:S4666`: Unexpected duplicate selector "", first used 

### ISSUE THREAD

**Issue by schlundus** [SonarSource/SonarJS#3209]
It seems that the scanning of LESS files has an error regarding to rule css:S4666
when using "Mixins With Parentheses" in less like this
.test() {

and selectors with variables like this
@{foo}_bar {

they are all triggering a false positive "css:S4666: Unexpected duplicate selector "", first used ...."

SonarQube Server version is 9.5.0.56709

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-118
