### ISSUE TITLE
Improve S6439 (`sonar-jsx-no-leaked-render`): Rely on `React.PropTypes`

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#3222]

**Comment by ilia-kebets-sonarsource** [comment]
We could consider developing PropTypes support when multiple rules can take advantage of it.
We need to investigate if PropTypes are usually defined in the same file or not, in which case, we will not be able to work with them.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-117
