### ISSUE TITLE
Upgrade `vue-eslint-parser` dependency

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#3233]
Depends on #3231

We are currently using `vue-eslint-parser@8.3.0`, but we are not able to upgrade the dependency as the next version [9.0.0](https://github.com/vuejs/vue-eslint-parser/releases/tag/v9.0.0) dropped the support of Node.js 12. Furthermore, this new version adds support for scope analysis of `<script setup>`, which should theoretically replace the workarounds implemented in #2818 and #3125 to kill the noise.

**Comment by ilia-kebets-sonarsource** [comment]
Should we investigate if it still has the side-effect bug where it patches the way SourceCode is built, where nodes share `Location` objects?

**Comment by sschneider-ihre-pvs** [comment]
<script setup lang="ts"> was overlooked
