### ISSUE TITLE
Add exception to S3512 about back-ticks

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3246]
S3512 - unexpected string concatenation

- Should ignore strings containing back-ticks as part of the text

**Comment by gabriel-vivas-sonarsource** [comment]
Here's one example:
<img width="1015" alt="Screenshot 2022-06-28 at 17 39 55" src="https://user-images.githubusercontent.com/103954349/179913702-e976ad2d-9b2b-432b-ae54-4ce5a678a1ba.png">

**Comment by gabriel-vivas-sonarsource** [comment]
As with other rules that are not in the Sonar Way, we should remove this from MMF-2835.
