### ISSUE TITLE
Add exception for S1067 for same operator

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3248]
S1067 - reduce the number of conditional operators, 3 max

- Should not increment count when the operator is the same. For example, a || b || c || d || e || f || g should not be raised as an issue.

**Comment by saberduck** [comment]
@gabriel-vivas-sonarsource I am not really sure about this one, these kinds of ideas are the basis of "cognitive complexity" rule. In fact, I am not sure why we have this rule in the profile, IMO it's superseded by cognitive complexity rule. wdyt @vilchik-elena ?

**Comment by gabriel-vivas-sonarsource** [comment]
Here's one example of the rule [in Peach](https://peach.sonarsource.com/project/issues?id=redash_nodev14&open=AX4HNUruXIB4CaHfo57o&resolved=false&rules=javascript%3AS1067&types=CODE_SMELL) (internal link).

<img width="1001" alt="example" src="https://user-images.githubusercontent.com/103954349/179779681-530eeacb-1a47-4f39-9f8c-14497bbefdc0.png">

**Comment by gabriel-vivas-sonarsource** [comment]
Upon closer inspection, S1067 is in the *all* pseudo-profile and not in the Sonar Way.
Sorry for the noise, let's remove this from MMF-2835.
I'll double check the MMF to ensure all rules are in the Sonar Way.

**Comment by vilchik-elena** [comment]
I will close the ticket as rule is not in default profile
