### ISSUE TITLE
Analyze JS inside YAML with type information

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#3263]
Rules using type information currently don't raise any issues on inline JavaScript code in YAML files. In fact, they are automatically disabled since the parser services returned by TypeScript ESLint parser don't include a reference to TypeScript's type checker, which a subset of rules relies on. This happens because a YAML analysis input neither provides a TSConfig nor a TypeScript Program identifier that should enable the support of type information. Similar to Vue.js Single File Components (.vue files), a program-based analysis is impossible; only a TSConfig-based analysis works. Therefore, we need to generate a default TSConfig file for YAML input files and include it in each YAML analysis input, as we do for analyzing regular JavaScript input files.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-116
