### ISSUE TITLE
Improve S3776: Exclude complexity of JSX attribute short-circuits

### ISSUE THREAD

**Issue by gabriel-vivas-sonarsource** [SonarSource/SonarJS#3289]
| Label | Description |
| --- | --- |
|Rule | S3776 "Cognitive Complexity of functions should not be too high"  |
| FP Example | * [Short-circuits in JSX attribute values](https://sonarcloud.io/project/issues?resolved=false&rules=javascript%3AS3776&id=gabriel-vivas-sonarsource_caronte-tool&open=AYIcpFGSkChixz00fwGY) 

### Explanation
In JSX, it is fairly common to use short-circuit logic for conditionally rendering values. Currently, we count this as Cognitive Complexity.

See example:
* https://sonarcloud.io/project/issues?resolved=false&rules=javascript%3AS3776&id=gabriel-vivas-sonarsource_caronte-tool&open=AYIcpFGSkChixz00fwGY

See the dogwood thread (internal):
* https://discuss.sonarsource.com/t/cognitive-complexity-and-jsx-tsx/12399/5

### Suggestion

When counting the Cognitive Complexity, we should consider short circuits, nulls coalescing, and optional chaining as shorthand.

Propagating
* `something && something.prop`
* `something.?prop`

Coalescing
* `something || other`
* `something ?? other`

This is true for the following cases at least:

In JSX
* JSX attribute values
* JSX embedded JS expressions

Everywhere, not only in JSX
* `return` statements
* Assignments

Perhaps there are more cases where it makes sense.
Perhaps we don't need to count them in any place?

**Comment by saberduck** [comment]
we didn't manage to do this in current sprint, removing from milestone

**Comment by gabriel-vivas-sonarsource** [comment]
See some of the comments in https://github.com/SonarSource/SonarJS/issues/2238
As people keep coming to this subject.
