### ISSUE TITLE
Avoid long unpacking of `eslint-bridge` on Windows during the Visual Studio SonarLint installation and update

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3319]
## Why

During the installation of Visual Studio's SonarLint extension, they unpack the `eslint-bridge` tarball which was created with `npm pack`: 

https://github.com/SonarSource/SonarJS/blob/293e62f81fb328e816ac66198682f700612c666d/eslint-bridge/package.json#L13

Since it contains many files (>14k as of SonarJS 9.6), it takes minutes on some Windows [due to Defender](https://github.com/microsoft/Windows-Dev-Performance/issues/27).

This also happens in VS code when:
- the ID boots
- changing workspaces
- changing to/from connected mode

## What

We could do one of the following:
1. pack fewer files in this tarball: bundling
2. not have to unpack it as part of the installation process: either distribute it unpacked in the SonarJS JAR, or in SonarLint, which increases its size from 20MB to 30MB
3. Use the `~/.sonar/` folder as a cache for the extracted data

We didn't have any success with bundling, and option 2 is not acceptable for SonarLint, therefore, we will implement the cache from option 3.

Exploration work has been done as part of the file path length issue: https://github.com/SonarSource/SonarJS/issues/3135#issuecomment-1216676359

## How

TBD

**Comment by ilia-kebets-sonarsource** [comment]
Leaving the current dependencies external (not bundled), as done in #3330, produces a distribution with 7.5k files which is an improvement of only 50% based on the >14k files.
And we haven't yet addressed the issue of module aliases introduced in SonarJS 9.6

**Comment by ilia-kebets-sonarsource** [comment]
another case was reported here: https://community.sonarsource.com/t/javascript-sensor-taking-too-long-at-deploying-the-bridge-server/110316/6

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-115
