### ISSUE TITLE
Rule S1313: Exclude reserved documentation IP ranges

### ISSUE THREAD

**Issue by hendrik-buchwald-sonarsource** [SonarSource/SonarJS#3321]
S1313 should not report an issue for the following IP ranges:

* 192.0.2.0/24
* 198.51.100.0/24
* 203.0.113.0/24
* 2001:db8::/32

In other words, no issue should be reported if the IP address starts with:

* 192.0.2.
* 198.51.100.
* 203.0.113.
* 2001:db8:

The ranges are reserved for documentation purposes by [RFC 5737](https://datatracker.ietf.org/doc/html/rfc5737) and [RFC 3849](https://datatracker.ietf.org/doc/html/rfc3849).

**Comment by caspChristian** [comment]
Any IPv6 mapped version of well known IPv4 addresses should be just as fine, ex: `::ffff:192.0.2.0`
Maybe more difficult is other prefixes, but one could still argue that any variant of these IPv4 prefixes should be ignored, regardless of IPv6 prefix.

**Comment by hendrik-buchwald-sonarsource** [comment]
@caspChristian that is a good point, thanks for the note!
