### ISSUE TITLE
Reduce memory usage for JavaScript analysis by relying on program-based analysis

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3346]
JavaScript analysis should use the same approach as in TypeScript sensor - instead of generating `tsconfig.json` file, we create program instance programmatically by calling `/create-program` endpoint.
 
`/create-program` endpoint needs to be extended to allow the creation of program from the list of files sent in the body of the request. 

Main benefit is that we do not use watch programs from typescript-eslint that are quite memory intensive and we manage the lifecycle of the program. This should lead to faster analysis and less memory usage (we should setup some measurement for this change, see #3369)

TypeScript part which introduced `create-program` was done in this PR https://github.com/SonarSource/SonarJS/pull/2910

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-114
