### ISSUE TITLE
Add an optimized linter with only the external rules and an option to analyse JS/TS/YAML files with it

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3347]
In order to reduce the analysis time when files are not modified, we can skip some rules but not the security rules that are still required to generate UCFG files.
The server loads these external rules dynamically according to the 'bundles' node command parameter and when the ESLint linter is created based on the request rules parameter. 
Thus a second 'optimized' linter should be created in the initialization service with only these external rules. And the JS/TS/YAML analysis services need a new flag triggering the use of the 'optimized' linter.

**Comment by vilchik-elena** [comment]
technical step done as part of #3345
