### ISSUE TITLE
Fix FP S5332 ('no-clear-text-protocols'): Ignore SES communications

### ISSUE THREAD

**Issue by loris-s-sonarsource** [SonarSource/SonarJS#3351]
Rule [S5332](https://sonarsource.github.io/rspec/#/rspec/S5332/javascript) gives a FP when nodemailer is used with SES:

```javascript
import * as ses from '@aws-sdk/client-ses'
import nodemailer from 'nodemailer'

const sesClient = new ses.SES({ region: AWS_REGION })
const transporter = nodemailer.createTransport({
  SES: {
    ses: sesClient,
    aws: ses,
  },
})
```

SES communications are encrypted by default.

### Appendix
- Docs: [NodeMailer > SES transport](https://nodemailer.com/transports/ses/)
- FP Source: [SonarSource Community > AWS SES Nodemailer Transport doesn’t use clear-text protocol](https://community.sonarsource.com/t/aws-ses-nodemailer-transport-doesnt-use-clear-text-protocol/60547)
- SES Encryption enforcement: [Amazon SES and security protocols](https://docs.aws.amazon.com/ses/latest/dg/security-protocols.html)

**Comment by victor-diez-sonarsource** [comment]
Hi @loris-s-sonarsource,

do you want to cover as well AWS SDK v2? I see in your examples that you are using v3, but I understand most existing codebases will still be based on [previous version](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html). 

If yes, can you please provide a code sample that would cover AWS SDK V2?

Thanks!

**Comment by victor-diez-sonarsource** [comment]
ok, thanks!

**Comment by yassin-kammoun-sonarsource** [comment]
@loris-s-sonarsource We are going to merge the PR corresponding to this ticket for now. Let's rather create a separate ticket if you that the user case reported by @victor-diez-sonarsource is worth covering too.

**Comment by loris-s-sonarsource** [comment]
@yassin-kammoun-sonarsource Ok, thanks. I didn't have in mind that the proposition to add v2 was actually urgent. Thanks

**Comment by yassin-kammoun-sonarsource** [comment]
No, it's not urgent. I just want the fix of the original scope to be merged before our next release early next week. You are probably busy specifying the MMFs about the AWS CDK rules, so it's okay to investigate Victor's suggestion later on.

**Comment by loris-s-sonarsource** [comment]
Got it.
