### ISSUE TITLE
Use the plugin caching API to store and retrieve UCFG files

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3362]
In order to speed up the analysis, the plugin API provides a caching API to reuse content generated by sensors which can be applied to UCFG files.
On the java plugin side, the sensors should leverage the caching API to populate the cache and skip completely the call to the eslint-bridge for unchanged files for which there are cached UCFG files.
On the javascript side, analyzers should return the paths to the UCFG files generated during the analysis.

**Comment by victor-diez-sonarsource** [comment]
PR on sonar-security:

https://github.com/SonarSource/sonar-security/pull/3351
