### ISSUE TITLE
Run table partitioning in Athena after each Peach analysis batch

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#3363]
We should call following query when every analysis is over.
```sql
MSCK REPAIR TABLE `sonarjs_sensor_metrics`;
```

This is required when new version of SonarJS is released, but we can do it every time as we can hardly now that the version has changed.

**Comment by victor-diez-sonarsource** [comment]
implemented in:

https://github.com/SonarSource/peachee-languages/pull/290

fixed aws permissions via:

https://github.com/SonarSource/sonarsource-iam/pull/588
https://github.com/SonarSource/sonarsource-iam/pull/591

**Comment by victor-diez-sonarsource** [comment]
Further permissions were needed:
https://github.com/SonarSource/sonarsource-iam/pull/612
https://github.com/SonarSource/sonarsource-iam/pull/613

Issue closed
