### ISSUE TITLE
Ignore bundled code

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3368]
We would currently analyze (and fail) on files such as 

https://github.com/SonarResearchScanning/odoo/blob/master/addons/web/static/lib/pdfjs/build/pdf.js 

we should revisit our detection of generated code and avoid such files automatically.

**Comment by victor-diez-sonarsource** [comment]
Probably a good strategy would be filtering out by path? something like **/vendor/* or any other conventional paths where dependencies usually sit

**Comment by gabriel-vivas-sonarsource** [comment]
Some more examples here:
https://sonarcloud.io/project/issues?resolved=false&rules=javascript%3AS3504&id=skflabsjs_Client-side-restriction-bypass
