### ISSUE TITLE
Add information to logs on used memory during analysis

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3369]
We should augment the logs with information about memory usage during the analysis. 

We need to investigate available APIs

- https://nodejs.org/api/process.html#process_process_memoryusage
- https://nodejs.org/api/v8.html#v8_v8_getheapstatistics

We could observe heap after each file and print summary at the end of analysis for JS/TS sensor.

TBD if something is needed for CSS sensor

**Comment by ilia-kebets-sonarsource** [comment]
as discussed with @saberduck, we should do a dedicated sprint for this one, so I'm removing it from the hardening.

**Comment by yassin-kammoun-sonarsource** [comment]
Completed with:

- https://github.com/SonarSource/SonarJS/pull/4294
- https://github.com/SonarSource/SonarJS/pull/4274
- https://github.com/SonarSource/SonarJS/pull/4269
- https://github.com/SonarSource/SonarJS/pull/4263
