### ISSUE TITLE
Prevent dependabot from opening PRs on fixtures

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3384]
We have lockfiles in fixtures in `its/plugin/projects/` which get flagged by dependabot like here:
- https://github.com/SonarSource/SonarJS/pull/3328
- https://github.com/SonarSource/SonarJS/pull/3327
- https://github.com/SonarSource/SonarJS/pull/3326
- https://github.com/SonarSource/SonarJS/pull/3325

They are not relevant and provide unwanted noise.

I propose 2 solutions:

1. Remove lockfiles from these fixtures
2. Adopt a dependabot config: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory

**Comment by vilchik-elena** [comment]
@ilia-kebets-sonarsource don't you think we can simply disable dependabot for the whole repo as we use another tooling for SCA?

**Comment by vilchik-elena** [comment]
done
