### ISSUE TITLE
Support analysis of CSS in SonarLint

### ISSUE THREAD

**Issue by jblievremont** [SonarSource/SonarJS#3402]
The SonarLint team has plans to support [analysis of CSS in the IDE](https://portal.productboard.com/sonarsource/4-sonarlint/c/211-support-css-in-visual-studio-code-and-certain-jetbrains-ides?utm_medium=social&utm_source=portal_share) in 2022Q4.

As a requirement, the components related to CSS have to be declared to the plugin API when run in the SonarLint context.

**Comment by vilchik-elena** [comment]
https://sonarsource.atlassian.net/browse/MMF-2909

**Comment by jblievremont** [comment]
Please note that sonarlint-core 8.9.0.54830 was just released, with the appropriate language declaration (so that you can use it for the ITs related to SonarLint + CSS 😇).
