### ISSUE TITLE
Update rule S6304: "Granting access to all resources" should not be raised on actions without resource-level permissions

### ISSUE THREAD

**Issue by egon-okerman-sonarsource** [SonarSource/SonarJS#3543]
## Description
Rule S6304 looks for policies that grant access to all resources by looking for policies that set the resources to the wildcard identifier (`"*"`.) This causes issues, as policies can contain actions without any resource-level permissions. In this case, the wildcard identifier is required and is not a security issue.

## Detection Logic
The best way to prevent FPs here will be to keep an allowlist of all AWS actions that should raise a security hotspot. A JSON file containing all actions with resource-level permissions can be found in attachments (`withResources.json`.) This is a large list of ~9000 entries, which may have an effect on the analyzer filesize. As this list will be used by multiple analyzers (SonarJS, sonar-python, sonar-iac), it might be useful to turn it into a shared resource.

If at least one action in `actions` (in `PolicyStatement()`) or `$.Action` (in `PolicyStatement.from_json()` and `PolicyDocument.from_json()`) can be found in the allowlist for resource-level permissions, then a hotspot should be raised.

Although KMS actions sometimes have resource-level permissions, key policies should never trigger this hotspot (unchanged from #3451) and thus KMS actions are not included in the allowlist.

### Examples

```typescript
import { aws_iam as iam, aws_kms as kms } from "aws-cdk-lib";

new iam.ManagedPolicy(this, "NoncompliantPolicy1", {
    document: new iam.PolicyDocument({
        statements: [
            new iam.PolicyStatement({
                effect: iam.Effect.ALLOW,
                actions: ["iam:CreatePolicyVersion"],
                resources: ["*"] // Noncompliant, policy gives access to all resources
            })
        ]
    })
});

new iam.ManagedPolicy(this, "CompliantPolicy1", {
    document: iam.PolicyDocument({
        statements: [
            iam.PolicyStatement({
                 effect: iam.Effect.ALLOW,
                 actions: ["ec2:DescribeTransitGatewayAttachments"],
                 resources: ["*"] // Compliant, policy doesn't give access to any resource
            })
        ]
    })
});

new iam.ManagedPolicy(this, "CompliantPolicy2", {
    document: iam.PolicyDocument({
        statements: [
            iam.PolicyStatement({
                 effect: iam.Effect.ALLOW,
                 actions: ["snowball:*"],
                 resources: ["*"] // Compliant, no Snowball actions use resources
            })
        ]
    })
});

new kms.Key(this, "MyKey", {
    policy: new iam.PolicyDocument({
        statements: [
            new iam.PolicyStatement({
                actions: ["kms:*"],
                principals: [iam.AccountRootPrincipal()],
                resources: ["*"] // Compliant, "*" means "this key" for key policies
            })
        ]
    })
});
```

## RSPEC
[RSPEC PR 1381](https://github.com/SonarSource/rspec/pull/1381) updates the exceptions for this rule.

## References
Specification ticket: [APPSEC-219](https://sonarsource.atlassian.net/browse/APPSEC-219)
[Original Discuss topic](https://discuss.sonarsource.com/t/python-s6304-granting-access-to-all-resources/12137)

## Attachments
[withResources.json.gz](https://github.com/SonarSource/SonarJS/files/9940210/withResources.json.gz) (gzipped as GitHub doesn't allow JSON files to be uploaded)

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-110
