### ISSUE TITLE
S2814 might not be needed in TypeScript

### ISSUE THREAD

**Issue by gabriel-vivas-sonarsource** [SonarSource/SonarJS#3580]
| Label | Description |
| --- | --- |
| Rule | S2814 "Variables and functions should not be redeclared"  |
| Subject | FP on TypeScript `type` and `function` with same name |
| Community | https://community.sonarsource.com/t/typescript-file-produces-a-false-positive-already-defined-when-types-and-variable-share-same-name/76080 |

### Explanation
`type` and `function` have different name spaces in TypeScript, so we should not raise an issue for this case.
Notice that this also applies to variables, `namespace`, `interface`, and perhaps more.

See many FP in Peach (internal):
* https://peach.sonarsource.com/coding_rules?languages=ts&q=already&open=typescript%3AS2814

### Suggestion
The TypeScript compiler will already check for reused names and output an error.
So this rule does not make much sense in TypeScript, as compared to JavaScript.

Regardless of potential fixes to the FP, we should consider removing this rule for TypeScript.
Or at least remove it from the "Sonar Way" profile for TypeScript.

**Comment by saberduck** [comment]
We need programmatically deprecate the rule in `TypeScriptRulesDefinition` and `JavaScriptProfilesDefinition` because metadata is shared for both JS and TS
