### ISSUE TITLE
Implement project size check to activate typed rules in NodeJS

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3611]
Typed rules use the TypeScript compiler on JavaScript files with a generated `tsconfig.json` file specifying the project root folder. With this configuration, the TypeScript compiler is able to find the other project files that are imported into the analyzed files and provide the required type information.
However, the more files a project contains, the longer the compiler will need to compile. And to avoid excessive analysis time, the TypeScript compiler is deactivated if the number of JS/TS files exceeds a configured threshold. This check runs in Java, which means it also needs to be implemented in SonarLint for VisualStudio as it doesn't have the Java runtime.
The check should run in NodeJS to avoid this logic duplication and occur before generating the `tsconfig.json` file. The endpoint '/create-tsconfig-file' may thus return an empty response when the check fails.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-107
