### ISSUE TITLE
Update eslint dependencies to latest version

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3681]
The current version of eslint used is 8.26.0 and version 8.33.0 is available. In version 8.27.0 the PR [#16458](https://github.com/eslint/eslint/pull/16458) updated some core rules to use the new flat configuration and this is causing regressions on our side when they were decorated (like `comma-dangle`). The decoration logic should be changed to support this new behavior.

**Comment by vilchik-elena** [comment]
relates to #3647
