### ISSUE TITLE
Update S1472 (`call-argument-line`): cover scope of ESLint's `no-unexpected-multiline`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3705]
https://eslint.org/docs/latest/rules/no-unexpected-multiline

**Comment by francoismora** [comment]
The rule logic should be changed to cover more cases that happen when there's a closing parent between the caller and the argument nodes located on the same line as the arguments.

**Comment by francoismora** [comment]
ESLint also checks that the tag and the literal are on the same line in tagged templates. As tagged templates are syntactic sugars corresponding to function calls, it makes sense to include the same validation in S1472.
