### ISSUE TITLE
Analysis should work when computer resumes from sleep

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#3719]
Users report that resume from sleep can close the socket between Java and Node part of the analyzer. Due to the mechanism which prevents needless attempts to start the Node part of the analyzer, we will fail to resume the analysis.

To be discussed how to handle the closed socket and avoid repeated needless restarts in case we are not able to start Node process. 

Original report https://community.sonarsource.com/t/eslint-bridge-server-closed/81530/3 
SonarLint ticket https://sonarsource.atlassian.net/browse/SLI-874

**Comment by paolobiavati** [comment]
January 2024 same problem:  skip analysis after exit sleep mode without restarting Visual Studio Code

Visual Studio Code;
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

SonarLint  VSC extension:  v4.2.2

SonarQube: Community EditionVersion 9.9.3 (build 79811)

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-100
