### ISSUE TITLE
Update S1121 (`no-nested-assignment`): cover cases from ESLint's `no-cond-assign`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3723]
Cases to cover:

1. if (someNode || (someNode = parentNode)) { }
2. var x; var b = x && (y = 0) ? 1 : 0;

**Comment by yassin-kammoun-sonarsource** [comment]
Closing this issue because we are deliberately excluding those cases in the current implementation of the rule, which makes sense to me.

See #2539.
