### ISSUE TITLE
How should contributors test changes locally?

### ISSUE THREAD

**Issue by hamirmahal** [SonarSource/SonarJS#3730]
How should contributors test changes locally? Is there a way to do so manually, and automatically?

**Comment by saberduck** [comment]
Hi,

`npm run test` should work for JS part in `eslint-bridge`, standard Maven commands work for Java part. However, we do not expect bigger contributions, as we do not have the capacity to review and discuss them.
Please use our community forum https://community.sonarsource.com to provide feedback we can transform into our roadmap. Thanks!
