### ISSUE TITLE
Fix FP S2189 (`no-infinite-loop`): Ignore delete operator

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3734]
The rule should consider modifications done by the `delete` operator.

Reported in https://community.sonarsource.com/t/i-get-javascript-s2189-item-is-not-modified-in-this-loop-even-though-i-am-modifying-it/84385/1

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-99

**Comment by vincesp** [comment]
Only that I don't seem to be able to subscribe to that ticket on Jira

**Comment by Wohops** [comment]
Hello @vincesp ,

Unfortunately, this is a limitation that we are aware of. Watching the issue on Jira is not possible for the time being.
I feel you will have to regularly visit the page.

Michael
