### ISSUE TITLE
JS analyzer in HTML should ignore non-javascript types

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#3757]
Reported in community: https://community.sonarsource.com/t/jsx-error-appearing-in-angular-html-files/85243

We should ignore non-javascript types

[Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type)
[Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript)

**Comment by Phil-Appraisd** [comment]
Hi, I originally raised this. Thanks for looking into this!

Just to check will you still analyse the code for other types than JS?  I'm not sure if the angular templates were ever analysed but ideally they would be.  Similarly we have some script tags that contain typescript that could be analysed.
Thanks
