### ISSUE TITLE
Add exception to Cognitive Complexity for React forwardRef components

### ISSUE THREAD

**Issue by timphamcmc** [SonarSource/SonarJS#3777]
consider React forwardRef component such as

```
const FancyButton = React.forwardRef((props, ref) => {
  const handleSomething = () => {
    if (something) {
      do something
    }
  }
  const handleSomethingElse = () => {
    if (somethingElse) {
      do somethingElse
    }
  }
  if (condition) {
    return sth
  }
  if (condition2) {
    return sth2
  }
  if (condition3) {
    return sth3
  }
  if (condition4) {
    return sth4
  }
  return (
    <button ref= { ref } className = "FancyButton" >
      { props.children }
      < /button>
  );
});
```

Currently, cognitive complexity of such component would be 15, while the equivalent component using class syntax and regular functional syntax will have only one. We should avoid adding complexity of nested functions to the outer function in such case.

**Comment by vartuom** [comment]
I'm developing a UI library and I have the same problem. Maybe there is some workaround?
