### ISSUE TITLE
Update S4204 (`no-any`): Report all kinds of expression of type any

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3803]
Extend the rule S4204 with the cases supported by
- [no-unsafe-argument](https://typescript-eslint.io/rules/no-unsafe-argument)
- [no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment)
- [no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)
- [no-unsafe-member-access](https://typescript-eslint.io/rules/no-unsafe-member-access)
- [no-unsafe-return](https://typescript-eslint.io/rules/no-unsafe-return)

**Comment by yassin-kammoun-sonarsource** [comment]
Closing this because these additional TypeScript ESLint rules raise a lot of noise and there are many false positives on ruling; some are due to missing `d.ts` files, others because of globals like `describe` and `expect`, and so on.
