### ISSUE TITLE
Add rule for `promise-function-async`

### ISSUE THREAD

**Issue by francoismora** [SonarSource/SonarJS#3817]
https://typescript-eslint.io/rules/promise-function-async

 - Covered?
   - Not covered
 - Makes sense?
   - Require any function or method that returns a Promise to be marked [async](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#description). Shows explicit intention about functions returning promises. Educates developers about promises
 - No options, quickfix available

RSPEC PR: https://github.com/SonarSource/rspec/pull/1754

**Comment by ilia-kebets-sonarsource** [comment]
This rule doesn't convince us and is too noisy. We can drop this rule.
2237 issues on Peach
