### ISSUE TITLE
Avoid using deprecated `InputFile` methods in SonarLint context

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3847]
The following methods on the `InputFile` class have been deprecated because we shouldn't assume that file are on the local FS:
1. relativePath()
2. absolutePath()
3. file()
4. path() 

Instead, use `InputFile::uri`.

Watch out for `FileSystem::baseDir()`, which would not return the parent folder in this case.

Only access the file content using `InputFile::content`.

Goal: do not crash. Extensive functional coverage is not necessary.

Examples: 
- https://sonarsource.atlassian.net/browse/SLE-607

### Notes

TypeScript offers an abstraction for the underlying File System that we could use.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-96
