### ISSUE TITLE
Fix FP S1874 (`deprecation`): `'fileSaver' is deprecated. use `{ autoBom: false }` as the third argument`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3862]
Reproducer:

TS project, add the dependency `npm i file-saver`

Then use:

```typescript
import * as fileSaver from 'file-saver';

fileSaver.saveAs(
  '42',
  'foo',
  { autoBom: false },
);
```

The issue was flagged in community at https://community.sonarsource.com/t/typescript-filesaver-is-deprecated-use-autobom-false-as-the-third-argument/88453/

**Comment by msindev** [comment]
This issue still persists. Has there been any resolution over this?

**Comment by ilia-kebets-sonarsource** [comment]
This was fixed in https://github.com/SonarSource/SonarJS/releases/tag/10.6.0.22520
