### ISSUE TITLE
Create rule: Confusing operator priority for `new foo().bar()`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3897]
When using the pattern `new foo().bar()`, the operator priority is actually `(new foo()).bar()`. This use case has actually been encountered when implementing `new-cap` from ESLint with the following pattern: `new require('foo').bar()` as following:

![image](https://github.com/SonarSource/SonarJS/assets/104737176/45acc414-fec0-4398-907f-2539796e9bf3)

This was first noticed when working on https://github.com/SonarSource/SonarJS/issues/3886.

It should cover this case as well: https://eslint.org/docs/latest/rules/no-new-require 

Ref.: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-95
