### ISSUE TITLE
Improve S3735 (`void-use`): cover new cases

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3909]
There are a few cases from ESLint's [`no-void`](https://eslint.org/docs/latest/rules/no-void) which our rule doesn't cover:
- `void 0`
- `void(0)`
- `var foo = void 0`

Either improve our implementation to cover them or use ESLint's rule.

**Comment by alexander-kamushkin-sonarsource** [comment]
`void 0` variations are listed as exceptions in S3735 and they are excluded by design - `void 0` was used as a substitute for `undefined` in the early days, so may produce a lot of noise.

Keep the rule as it is.
