### ISSUE TITLE
Update S3834 (`no-new-symbol`): replace with `no-new-native-nonconstructor`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3917]
ESLint rule definition https://eslint.org/docs/latest/rules/no-new-native-nonconstructor

maybe propose quickfix that removes `new`

**Comment by alexander-kamushkin-sonarsource** [comment]
Overlaps with S3834, which is `no-new-symbol` (eslint recommended)

**Comment by alexander-kamushkin-sonarsource** [comment]
Instead of creating a new rule will update S3834, replacing `no-new-symbol` with `no-new-native-nonconstructor`
