### ISSUE TITLE
Create rule S6644 (`no-unneeded-ternary`): Ternary operator should not be used instead of simpler alternatives

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3923]
ESLint rule definition https://eslint.org/docs/latest/rules/no-unneeded-ternary

Related to S1126

has quickfix

**Comment by MrJithil** [comment]
Can I take it?

**Comment by MrJithil** [comment]
Need suggestion, to add the new rule args. Can I use `"S1126" "no-unneeded-ternary"` ?

**Comment by MrJithil** [comment]
Also, as per the steps mentioned in the https://github.com/SonarSource/SonarJS/blob/master/docs/DEV.md , I am unable to create the rule. May be an access issues. 

Someone please advice the right steps to make the changes? I am happy to contribute this project.

**Comment by ilia-kebets-sonarsource** [comment]
Thank you for the proposition, @MrJithil, but this is part of a sprint for our internal team.
