### ISSUE TITLE
Fix FP S6606 (`prefer-nullish-coalescing`): When the first argument is `boolean | undefined`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#3936]
The issue happens with Tsonfig's `strict` mode ON.

Reproducer:

```typescript
function foo(bar: boolean | undefined, baz: string) {
  return bar || baz; // FP
}
```

In case `bar` is false, the function will return `false || baz` which will be `baz`
But if we apply the proposed fix, `false ?? baz` will evaluate to `false` which is different!

This issue was notified by dogfooding our rule.

Add link to https://www.typescriptlang.org/tsconfig#strictNullChecks in RSPEC

**Comment by victor-diez-sonarsource** [comment]
Add this fix to [PreferNullishCoalescingCheck.java](https://github.com/SonarSource/SonarJS/blob/master/sonar-plugin/javascript-checks/src/main/java/org/sonar/javascript/checks/PreferNullishCoalescingCheck.java). only works after upgrading typescript-eslint, as the parameter used here (IgnorePrimitives) was [added in August 2023](https://github.com/typescript-eslint/typescript-eslint/commit/dfcafae515e7f4d1ae69387eb163200e455dd0ce):

```java
    IgnorePrimitives ignorePrimitives = new IgnorePrimitives();

    private static class IgnorePrimitives {

      boolean string = false;

      @SerializedName(value = "boolean")
      boolean bool = true;

      boolean number = false;
      boolean bigint = false;
    }
```

At this moment we are blocked until we drop support for Node 14, as the latest typescript-eslint does not support it.

**Comment by vdiez** [comment]
Another community post reporting that when union contains object-only types (and thus cannot be falsy):

https://community.sonarsource.com/t/s6606-nullish-coalescing-should-be-preferred-should-not-fire-on-object-only-nullable-types/103618

Duplicate: https://github.com/SonarSource/SonarJS/issues/3986

**Comment by ericmorand-sonarsource** [comment]
@ilia-kebets-sonarsource , @yassin-kammoun-sonarsource , @vdiez ,

I have the feeling that the problem also arises with strings and numbers:

```ts
function foo(bar: string | undefined, baz: string) {
  return bar || baz; // '' || baz return baz; '' ?? baz returns ''
}

function foo(bar: number | undefined, baz: string) {
  return bar || baz; // 0 || baz return baz; 0 ?? baz returns 0
}
```

Should they be treated as exceptions just like booleans?

**Comment by yassin-kammoun-sonarsource** [comment]
I would say yes. In fact, the new rule option introduced by the rule mentioned by @vdiez ignores strings, numbers, booleans, and bigints. I think we can just enable this option.

**Comment by vdiez** [comment]
yes, exactly what @yassin-kammoun-sonarsource pointed out. [in the comment above](https://github.com/SonarSource/SonarJS/issues/3936#issuecomment-1775138570) you can see how to enable it from the Java side

**Comment by vdiez** [comment]
but you're right, in my code all other privimites are set to false. Not sure if setting them to `true` is what we want

when someone uses this:
```
function foo(bar: string | undefined, baz: string) {
  return bar || baz; // '' || baz return baz; '' ?? baz returns ''
}
```
I would say `??` is better option. The falsy value of empty string is not so obvious for many devs. boolean I think it makes sense to enable. string and number not so sure. @yassin-kammoun-sonarsource ?

**Comment by yassin-kammoun-sonarsource** [comment]
I would give it a try and see what kind of results we get on ruling. I just hope we are not introducing too many exceptions to a point where the rule no longer reports anything without us realizing it :)

**Comment by ericmorand-sonarsource** [comment]
@yassin-kammoun-sonarsource, well, as you suspected, we may be introducing so many exceptions that I have a hard time finding an invalid syntax that would trigger the rule.

I will restrain the exception to the `boolean | undefined` and `object` cases, but we'll probably end up with some requests from the community to add exception for the other primitives that include falsy values - see this ESLint issue for example: https://github.com/typescript-eslint/typescript-eslint/issues/4906.

Maybe at one point should we make this rule configurable?
