### ISSUE TITLE
Fix SonarLint limitations

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#3992]
We cannot tweak watchPrograms creation. Limitations:

* We cannot customize tsconfig contents (needed to not crash when tsconfig extends from node_modules not installed).
* We cannot use fallback Program if file is not included by any program. (createDefaultProgram is not the same)
* We cannot customize compilerHost, needed to limit dependencies lookup in ruling tests, fixing the node_modules conflict in ITs.

Start contributing to typescript-eslint? Fork?

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-89
