### ISSUE TITLE
Fix deprecations in ESLint API

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#3998]
Replace ESLint deprecated API methods
context.getSourceCode() -> context.sourceCode

Fix schemas:
DeprecationWarning: "Dependencies should be explicit" rule has options but is missing the "meta.schema" property and will stop working in ESLint v9. Please add a schema: https://eslint.org/docs/latest/extend/custom-rules#options-schemas

**Comment by alexander-kamushkin-sonarsource** [comment]
Looks like this requires updating typescript-eslint to 6.4 - https://github.com/typescript-eslint/typescript-eslint/pull/7460

**Comment by alexander-kamushkin-sonarsource** [comment]
> Fix schemas:
That should be done separately while moving config/metadata from java to the js side
