### ISSUE TITLE
Check breaking changes in Typescript 5.1

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#3999]
Update typescript to 5.1

**Comment by GabrielDelepine** [comment]
The `tsconfig.json` parameter `verbatimModuleSyntax` is currently not supported. I guess it is related

`Error: Unknown compiler option 'verbatimModuleSyntax'.`

**Comment by vdiez** [comment]
Hello @GabrielDelepine,

currently SonarJS is using TypeScript 5.1 already. What version of SonarQube are you currently using?

**Comment by GabrielDelepine** [comment]
> What version of SonarQube are you currently using?

I am very sorry for the confusion. The versions used in the project I am currently working on are:

SonarQube server 9.9.1.69595
SonarScanner 4.8.0.2856

**Comment by vdiez** [comment]
Hi @GabrielDelepine,

SQ 9.9 uses SonarJS 9.13, and TypeScript support was added in SonarJS 10.3. Is it possible for you to upgrade to latest SQ?

**Comment by vdiez** [comment]
ok, feel free to post in [our community](https://community.sonarsource.com/) if you encounter any issues. Usually, it's better to post there as all devs from all analyzers will have access to the user's feedback.

Closing this ticket, it was already done and I guess we missed it when merging https://github.com/SonarSource/SonarJS/pull/3939.
