### ISSUE TITLE
Rethink the whole ruling concept

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#4000]
Whenever we introduce some changes in the analyzer, especially related to rules, we run integration tests known as “ruling” to observe, track, and validate any changes in analysis results and behaviours. This task is time consuming and the value it brings is unclear:

The ruling integration tests analyzes several projects locally, set ups an orchestrator, starts a SonarQube instance, etc, which seems a bit overkill since the original purpose is to check rules’ behaviour.
Furthermore, the validation step is redundant because it is expected from us, developers, to validate any changes on a larger scale with the projects analyzed daily on a remote SonarQube instance, namely Next.
Last but not least, the slowness of the corresponding CI job affects our productivity since we try to keep our focus at one task at a time and therefore avoid too many context-switching tasks. Today, it can take a whole hour for a PR to be green.

It’s time to rethink the whole ruling concept and make it more relevant for what we are trying to achieve, that is, evaluating early the impact of a rule implementation without starting a local SonarQube instance. To this end, we can maybe take inspiration from the CFamiliy squad; they don’t have “ruling” tests at all, or rather they write them themselves instead of analyzing complete projects locally. Alternatively, we could benefit from the sonar-scanner-npm tool, but no longer relying on any Java at all for validating a rule seems more legit.

**Comment by ilia-kebets-sonarsource** [comment]
this is not relevant since aa12c8482b3d02cc5b4a95209fbf6ed309988f23
