### ISSUE TITLE
Investigate merging eslint-plugin-sonarjs into SonarJS

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#4001]
eslint-plugin-sonarjs could benefit release cycles of SonarJS.

If we can merge SonarJS and the Eslint plugin (probably make the eslint plugin a special npm target, to be investigated in the How) we could be much more proactive in deciding new rules to be added/removed/updated in the eslint plugin.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-84
