### ISSUE TITLE
Improve S109 (`no-magic-numbers`)

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#4004]
C/P from [discuss post](https://discuss.sonarsource.com/t/improving-the-magic-number-rule-javascript-typescript-s109/14081/6):

* Basic math with 2 should probably be ignored, specifically for halving (x / 2) and doubling (x * 2). This would be similar to the way we ignore 0 or 1 as they have immediate meaning in most situations. Examples [here](https://next.sonarqube.com/sonarqube/project/issues?resolved=false&rules=typescript%3AS109&open=AYac8M2ylpM2qp5PgCRI&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?resolved=false&rules=typescript%3AS109&open=AYac8M2JlpM2qp5PgCQ9&id=org.sonarsource.sonarqube%3Asonarqube-private).

* Should not raise for default values of destructured parameters, and similar cases where there is already a name to provide context for the meaning of the number. Examples [here](https://next.sonarqube.com/sonarqube/project/issues?resolved=false&rules=typescript%3AS109&open=AYac8M2ylpM2qp5PgCRH&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?resolved=false&rules=typescript%3AS109&open=AYgGG_n3_JFKICD98H2E&id=org.sonarsource.sonarqube%3Asonarqube-private).

* Consider ignoring any numeric values passed to style attributes in JSX and HTML element’s attributes that expect numeric values, like style, padding, margin, width, height, etc. For example [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fcomponents%2Frules%2FIssueTabViewer.tsx&resolved=false&rules=typescript%3AS109&open=AYigNSK20vS6jBAPWjIZ&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fapp%2Fcomponents%2Fnav%2Fglobal%2FGlobalNavBranding.tsx&resolved=false&rules=typescript%3AS109&open=AXDpE0rZ9759-T8_X3Of&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fapps%2Fissues%2Fsidebar%2FCreationDateFacet.tsx&resolved=false&rules=typescript%3AS109&id=org.sonarsource.sonarqube%3Asonarqube-private&open=AXDpE1vf9759-T8_X3Uz).

* Consider ignoring numeric values used with bitwise operators. Example [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fdesign-system%2Fsrc%2Fhelpers%2Fcolors.ts&resolved=false&rules=typescript%3AS109&open=AYac8M46lpM2qp5PgCRl&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fdesign-system%2Fsrc%2Fhelpers%2Ftheme.ts&resolved=false&rules=typescript%3AS109&open=AYac8M3hlpM2qp5PgCRO&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fdesign-system%2Fsrc%2Fhelpers%2Fcolors.ts&resolved=false&rules=typescript%3AS109&id=org.sonarsource.sonarqube%3Asonarqube-private&open=AYac8M46lpM2qp5PgCRm).

* Consider ignoring obvious datetime operations, like 1000 * 60 * 60 * 12. Example [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fapps%2FprojectActivity%2Fcomponents%2FProjectActivityGraphs.tsx&resolved=false&rules=typescript%3AS109&id=org.sonarsource.sonarqube%3Asonarqube-private&open=AXDpE1-m9759-T8_X3Vk) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fhelpers%2Fmeasures.ts&resolved=false&rules=typescript%3AS109&id=org.sonarsource.sonarqube%3Asonarqube-private&open=AXtkInr9GIUvI6i6M4S8).

* Consider ignoring values passed as the third argument of JSON.stringify (the number of spaces). This is a super common pattern and the API is just weird like that. For example [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fapps%2Fwebhooks%2Fcomponents%2FDeliveryItem.tsx&resolved=false&rules=typescript%3AS109&open=AXDpE2Pm9759-T8_X3Wq&id=org.sonarsource.sonarqube%3Asonarqube-private).

* Consider ignoring array literals with only numbers, at least when there is a name already in the context (variable assignment, property assignment, default parameter, etc). Examples [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fcomponents%2Fcharts%2FZoomTimeLine.tsx&resolved=false&rules=typescript%3AS109&open=AYQ5BioBUze70vDfinLZ&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fcomponents%2Fcharts%2FZoomTimeLine.tsx&resolved=false&rules=typescript%3AS109&open=AYQ5BioBUze70vDfinLa&id=org.sonarsource.sonarqube%3Asonarqube-private) and [here](https://next.sonarqube.com/sonarqube/project/issues?files=server%2Fsonar-web%2Fsrc%2Fmain%2Fjs%2Fapps%2Fprojects%2Ffilters%2FCoverageFilter.tsx&resolved=false&rules=typescript%3AS109&open=AXDpE1kU9759-T8_X3S0&id=org.sonarsource.sonarqube%3Asonarqube-private).

**Comment by gabriel-vivas-sonarsource** [comment]
There's a [community thread](https://community.sonarsource.com/t/typescript-s109-magicnumbers-add-authorized-numbers-parameter-like-java-s109/98158/5) with similar examples:

* Simple time formulas: 24 (hours), 60 (minutes, seconds)
* Simple algorithms using Random/Hash: Powers of 2: 2, 4, 8, 16, 1024
* Simple conversions: Powers of 10: 10, 100, 1000

I think these make sense, although I'm not sure to what degree we can detect them.
