### ISSUE TITLE
FYI: typescript-eslint@v6 will remove parserServices.hasFullTypeInformation

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [SonarSource/SonarJS#4005]
[^1]👋 Hi! I'm one of the maintainers of [typescript-eslint](https://typescript-eslint.io). We're getting ready to release a new v6 major version of the tooling, which includes some small breaking changes.

Coming over from https://github.com/typescript-eslint/typescript-eslint/issues/7124: I see this repo contains references to `hasFullTypeInformation`. That property is something we've never recommended using (see that issue & https://github.com/typescript-eslint/typescript-eslint/issues/7158). We recommend instead using `ESLintUtils.getParserServices` per https://typescript-eslint.io/developers/custom-rules#typed-rules.

If you _really_ want to "progressively enhance" lint rules, `parserServices.program` will be `null` if type information isn't available. But we definitely recommend against that kind of rule behavior changing.

Overall, I'd suggest trying out typescript-eslint@v6 and making sure internal builds & downstream repos still compile & lint nicely with all the changes. Let me know if there's anything we can do to help with the v6 upgrade! 💖 

[^1]: Btw, I do see the template asking not to create issues here. I took a look at community.sonarsource.com but didn't see an appropriate place to put this kind of technical FYI. Seems like most of that is targeted towards bug reports and feature requests, which this isn't. I won't be offended at all if you move this to a more appropriate form/location. Cheers! 😄

**Comment by ilia-kebets-sonarsource** [comment]
Thank you for the notice, we'll take this into account for the next release!

**Comment by JounQin** [comment]
https://github.com/SonarSource/SonarJS/blob/ddd31a75b38ee534cd96944f0062a659fb755bd1/package.json#L78-L80

It seems already fixed?

**Comment by ilia-kebets-sonarsource** [comment]
Fixed by https://github.com/SonarSource/SonarJS/pull/4452
