### ISSUE TITLE
Fix FP S1874: (`deprecation`): Should not report when at least one function signature is not deprecated

### ISSUE THREAD

**Issue by victor-diez-sonarsource** [SonarSource/SonarJS#4008]
Reported in community: https://community.sonarsource.com/t/deprecated-apis-should-not-be-used-typescript-s1874/94779

In the array of jsdocs there may be non-deprecated signatures:
https://github.com/SonarSource/SonarJS/blob/master/src/linting/eslint/rules/deprecation.ts#L187

We should not report if at least one is not deprecated.

**Comment by ilia-kebets-sonarsource** [comment]
Putting this on pause because I ran into edge cases for which I can't write a working logic, see PR.

**Comment by ilia-kebets-sonarsource** [comment]
Another occurrence of this issue has been reported in discuss. There will be a link in the post added to this issue.
