### ISSUE TITLE
Options Schemas required for ESLint v9

### ISSUE THREAD

**Issue by alex-sonar** [SonarSource/SonarJS#4063]
As described in #3998 - ESLint v9 will require meta.schema property for rules with configurations options.

DeprecationWarning: "Dependencies should be explicit" rule has options but is missing the "meta.schema" property and will stop working in ESLint v9. Please add a schema: https://eslint.org/docs/latest/extend/custom-rules#options-schemas

This should be done while moving config/metadata from java to the js side

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-81
