### ISSUE TITLE
Support TypeScript 5.2

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4106]
https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/

We will unlikely be able to fully support TypeScript 5.2 as long as we don't upgrade TypeScript ESLint to the latest. This version of TypeScript introduces a new syntactical construct `using` for [Explicit Resource Management](https://github.com/tc39/proposal-explicit-resource-management). The version of TypeScript ESLint we are currently using will produce parsing errors on code using this new construct.

**Comment by ilia-kebets-sonarsource** [comment]
Fixed by https://github.com/SonarSource/SonarJS/pull/4452
