### ISSUE TITLE
Port sonar-analyzer-commons's comment-based verifier

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4117]
The comment-based testing framework was originally a partial port to TypeScript from [sonar-analyzer-commons's Java implementation](https://github.com/SonarSource/sonar-analyzer-commons/tree/master/test-commons/src/main/java/org/sonarsource/analyzer/commons/checks/verifier). Due to lack of time, the porting effort was stopped midway. We currently are able to extract issue expectations from comments. However, we still rely on ESLint's rule tester to test expected issues against actual ones. While this works, mismatch reporting is just unreadable. To improve this, we should port the remaining part, that is, the expectation verifier.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-80
