### ISSUE TITLE
Tag RSPECs of JS/TS rules relying on type information

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4190]
Users currently have no way of knowing which JavaScript rules rely on type information. This information matters for SonarLint users when type-checking of JavaScript files is deactivated due to project size. By tagging these rules, users would then be able to identify which rules are impacted when type information is missing.

**Comment by ilia-kebets-sonarsource** [comment]
we might need to update the DEV.md with this step
