### ISSUE TITLE
CSS: only parse supported formats

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4230]
We currently send to the CSS analyser [all the web languages](https://github.com/SonarSource/SonarJS/blob/6318f0450c12f75ef03eca7ed4dfbca744c3afc0/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/CssRuleSensor.java#L214-L219), which [includes lots of template languages](https://github.com/SonarSource/sonar-html/blob/master/sonar-html-plugin/src/main/java/org/sonar/plugins/html/api/HtmlConstants.java#L33) that we cannot parse and fail in a weird way.

We will therefore accept the following formats for the CSS analyzer:
- HTML-like: html, htm, xhtml
- Stylelint officially supported languages: TBD

We will filter out the others at Sensor level.

**Comment by victor-diez-sonarsource** [comment]
Add `.php` as requested in the [community](https://community.sonarsource.com/t/how-to-exclude-php-files-from-css-sonar/101975). It can still be added if needed by using `sonar.css.file.suffixes`

**Comment by ilia-kebets-sonarsource** [comment]
`.htm` files won't get metrics, but I opened an issue for it: https://sonarsource.atlassian.net/browse/SONARHTML-180
