### ISSUE TITLE
Fix confusion over `sonar.javascript.maxFileSize` being applied on CSS files

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4234]
The `sonar.javascript.maxFileSize` option is applied at the analyzer level for JS, TS, and CSS.

At least 1 customer was confused that his big CSS file was not analyzed until he changed the aforementioned option which is labelled for JS.

We need to investigate if the file size limit is necessary for CSS, by analyzing a big file for example.
- If yes, we introduce a dedicated option like `sonar.css.maxFileSize`
- otherwise, we don't apply this limitation for CSS files

~~We can also improve the current behaviour by logging clearly when a file is excluded from the analysis because of its size.~~

This issue was raised in https://community.sonarsource.com/t/problems-parsing-css-file/101595

**Comment by saberduck** [comment]
Logging is quite clear already, not sure what could be added
https://github.com/SonarSource/SonarJS/blob/ac74f3d875397f0b62e272352af4baf2b8ba7bcc/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/filter/SizeAssessor.java#L76

**Comment by ilia-kebets-sonarsource** [comment]
Indeed, I didn't verify this.
