### ISSUE TITLE
Fix analysis error due to encoding different from `UTF-8`

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4246]
We have had many reports of files failed to be analyzed with logs similar to:

```log
java.lang.IllegalArgumentException: Unable to create symbol on file ...
[...]
Caused by: java.lang.IllegalArgumentException: Start pointer [line=868, lineOffset=24] should be before end pointer [line=868, lineOffset=24]"
```

These issues can be fixed by providing the `sonar.sourceEncoding=UTF-8` to the scanner.

While looking for a fix, we are collecting the occurrences of these issues in this [google doc](https://docs.google.com/spreadsheets/d/1sgyARUol_UUP3cceDJ3V3300v07feQT-1WUsoV2-rR0/edit#gid=0) (private to Sonar).

**Comment by ilia-kebets-sonarsource** [comment]
Make utf-8 default for SonarJS, and HTML

**Comment by ilia-kebets-sonarsource** [comment]
After discussing with @saberduck, this seems to be impossible as the plugins get booted after the scanner has read the files, so we can only retrieve the text that was parsed using the default or set encoding.
Saving this issue for a later date.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-75
