### ISSUE TITLE
Add S2933 (`prefer-readonly`) to Sonar way

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4266]
S2933 is in Sonar way for C# but not for TypeScript.

**Comment by ilia-kebets-sonarsource** [comment]
@gabriel-vivas-sonarsource WDYT about adding to the Sonar way?

**Comment by gabriel-vivas-sonarsource** [comment]
How would it work for JS without type annotations?
Would you need to change the code with an explicit getter?

Actually, I think this would be a good fit for a design/architecture rule.
But we need to be careful. I suspect this might bring up many many issues in old JS codebases.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-73
