### ISSUE TITLE
Fix FP S6767 (`no-unused-prop-types`): Detect prop usage when passed into other functions

### ISSUE THREAD

**Issue by alex-sonar** [SonarSource/SonarJS#4300]
Reported in [dogfood](https://discuss.sonarsource.com/t/fp-on-rule-typescript-s6767-proptype-is-defined-but-prop-is-never-used/16256), [example](https://github.com/SonarSource/sonar-enterprise/blob/c67f1ccf76fe901dbc0a3274714992d4a847aaca/private/core-extension-enterprise-server/src/main/js/portfolios/components/MeasureDetails.tsx#L16)

Looks like the props usage is not detected when the props are passed as an argument to another function

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-72
