### ISSUE TITLE
Add syntax highlighting to CSS

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4310]
We currently don't compute syntax highlighting in the bridge and don't give it to the plugin. This could be a big plus for people fixing issues in CSS.

⚠️ Some extensions like `html`, `xhtm` are already covered by the HTML sensor and should be ignored.

**Comment by yassin-kammoun-sonarsource** [comment]
Syntax highlighting for CSS is already supported.
