### ISSUE TITLE
Do not deploy embedded Node.js runtime if `sonar.nodejs.executable` is set

### ISSUE THREAD

**Issue by vdiez** [SonarSource/SonarJS#4400]
The embedded runtime is deployed [here in BridgeServer#startLazily()](https://github.com/SonarSource/SonarJS/blob/f992fc19ca354d7324273e0167e03d1d2d1d9d45/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java#L299), while the logic that uses the `sonar.nodejs.executable` is only accessed [afterwards, in BridgeServer#startServer()](https://github.com/SonarSource/SonarJS/blob/f992fc19ca354d7324273e0167e03d1d2d1d9d45/sonar-plugin/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/bridge/BridgeServerImpl.java#L304).

Related to https://github.com/SonarSource/SonarJS/issues/4401

Reported in community:

https://community.sonarsource.com/t/org-sonar-plugins-javascript-nodejs-nodecommandexception-failed-to-start-server/99434/19?u=victor.diez

Also, we should not fail hard if the extraction of the runtime fails, but failover to the host runtime if present.

**Comment by ilia-kebets-sonarsource** [comment]
verified with built plugin on local SQ
