### ISSUE TITLE
Create rule XXX: Module loading should not have side effects

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4417]
#### Detection

- We should review statement types in ESTree and classify them
- We should prefer a blacklist over a whitelist to mitigate false postives
- A file should at least not contain the following nodes at the top-level scope:
  - function calls
  - loops
  - conditions
  - switches
  - mutable variables
  - ...
  - there might be more after reviewing ESTree nodes

#### Noncompliant

```js
export const x = 42;
while (x > 0) { // Noncompliant: side-effects on module loading
  console.log(x);
}
```

#### Compliant

```js
export const x = 42;
```

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-65
