### ISSUE TITLE
Create rule XXX: Destructuring should not be too complex

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4419]
#### Detection

- Destructuring arrays and objects should not make use of too many destructuring features
  - nesting
  - alias
  - default value
  - rest props/params
  - skipping array elements
- Raise an issue when at least N of these are used in a single expression (N tbd)
- Consider destructuring at declaration, assignment, and parameter level
- Might decide to split this into two different rules: 1) object destructuring, 2) array destructuring
- Adjust the complexity heuristic after seeing ruling findings 

#### Noncompliant

```js
const { foo: bar, baz = 42, qux: [quux, , corge], ...grault } = garply;
```

#### Compliant

```js
const { foo: bar, baz = 42, qux, ...grault } = garply;
const [quux, , corge] = qux;
```

_Let's try to find more meaningful code snippets, maybe something from our own codebase._

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-63
