### ISSUE TITLE
Create rule S1607: A reason should be provided when skipping a test

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4425]
[S1607](https://sonarsource.github.io/rspec/#/rspec/S1607)

Prevent `.skip` altogether (S3424) is deprecated, but we can support a comment on the same line or at +-1 line as it is done in S1607 for PHP.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-58
