### ISSUE TITLE
Create rule XXX: Imports should not create cycles

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4435]
[eslint-plugin-import/no-cycle](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md)

### Configuration

- Because the rule can induce a significant performance cost, we should limit the detection depth from 2 to 3 levels.
- This should be the default threshold, and should not be configurable.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-53
