### ISSUE TITLE
Deprecate rule S6245

### ISSUE THREAD

**Issue by sebastien-andrivet-sonarsource** [SonarSource/SonarJS#4466]
As part of a general effort to deprecate hotspots that are no longer useful, we decided to deprecate [S6245](https://sonarsource.github.io/rspec/#/rspec/S6245) "Disabling server-side encryption of `S3` buckets is security-sensitive". `S3` now encrypts by default.

RSPEC PR: https://github.com/SonarSource/rspec/pull/3501
AppSec ticket: [APPSEC-1412](https://sonarsource.atlassian.net/browse/APPSEC-1412)

[APPSEC-1412]: https://sonarsource.atlassian.net/browse/APPSEC-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ericmorand-sonarsource** [comment]
This rule was deprecated in RSPEC on December 2023 and the change was propagated to SonarJS a few days later: https://github.com/SonarSource/SonarJS/pull/4480

There is no further action needed
