### ISSUE TITLE
Property `shouldUseTypeScriptParserForJS` should be removed

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#4476]
Long time ago we introduced the property `shouldUseTypeScriptParserForJS` to make it possible to opt-out from tsc when parsing. I believe this is no longer necessary and we should remove the option to simplify the codebase.

However, we should consider the case when project is using Flow, where all the files will fail to parse with tsc. It will be probably quite slow if we always first try tsc and then fallback. We should probably detect flow and similar cases and use babel for the whole project without attempting to parse with tsc

**Comment by ilia-kebets-sonarsource** [comment]
related to https://github.com/SonarSource/SonarJS/issues/3604

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-46
