### ISSUE TITLE
Plugin should detect failures from bridge

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#4478]
Currently, in case of an unknown failure, the bridge will return a response with an `error` field. This is not handled on the Java side and the analysis simply continues as if nothing happened.

The bridge should return an HTTP error code (500) and this should be detected on the Java side and handled accordingly.

**Comment by ilia-kebets-sonarsource** [comment]
this would help from more specification:
- a reproducer would be nice
- a proposed solution would be nice.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-45
