### ISSUE TITLE
Upgrade Stylelint to v16

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#4481]

**Comment by ilia-kebets-sonarsource** [comment]
related to https://github.com/SonarSource/SonarJS/issues/4600

**Comment by zglicz** [comment]
As explained in the PR, we will not upgrade Stylelint to v16, as we require CommonJS module and that is incompatible with Stylelint.v16 - https://stylelint.io/migration-guide/to-16#deprecated-commonjs-api 

Hopefully, with the PR and once SonarJS moves to ESM, this will just be a version bump. We should keep this ticket alive and tackle it later.
