### ISSUE TITLE
Fix FP S3516: When the returned value is modified between the return statements, it isn't the same return

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4486]
Reproducer:

```js
function foo() {
  const a = {}
  if (b) return a;
  a.bar = 2;
  return a;
}
```

Example: [issue on SonarJS on Next](https://next.sonarqube.com/sonarqube/project/issues?pullRequest=4458&issueStatuses=OPEN%2CCONFIRMED&open=AYyRo3hObAPV64qQMp43&id=org.sonarsource.javascript%3Ajavascript)

We could either check if it is modified between the return statements, or make an exception for objects or `let` and `var` variables.
This seems to especially target the early return pattern.

### Property updates:
- https://peach.aws-prd.sonarsource.com/project/issues?issues=AX4cI04bPp2MRvnWaTP6&open=AX4cI04bPp2MRvnWaTP6&id=js%3Adojo (same as above)
- https://peach.aws-prd.sonarsource.com/project/issues?issues=AYMShmTJ1kW2CRuq2FjD&open=AYMShmTJ1kW2CRuq2FjD&id=js%3Areact-native (similar, but with computed property access)

### Possible side effects:
- Method of the returned object is called in one execution path: https://peach.aws-prd.sonarsource.com/project/issues?issues=AYtfjOrHEaozhETYVILT&open=AYtfjOrHEaozhETYVILT&id=js%3Anextjs

```js
function foo() {
  const a = {}
  if (b) return a;
  a.bar();
  return a;
}
```

- Return value being used as a parameter of a function call between execution paths https://peach.aws-prd.sonarsource.com/project/issues?issues=AYV3XmdJKzx7YpNBZLGL&open=AYV3XmdJKzx7YpNBZLGL&id=js%3Anextjs

```js
function foo() {
  const a = {}
  if (b) return a;
  bar(a);
  return a;
}
```

### Update through aliasing:
- https://peach.aws-prd.sonarsource.com/project/issues?issues=AX4cJtDAuj7OPLYg8Gtj&open=AX4cJtDAuj7OPLYg8Gtj&id=js%3Asecurity-expected-issues%3Ajavascript-frameworks

```js
function foo() {
  const a = {}
  if (b) return a;
  c = a;
  c.d = 42;
  return a;
}
```

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-43
