### ISSUE TITLE
Improve S2699 (`assertions-in-tests`): Detect Jest assertion API

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4506]
The rule should consider Jest assertion API as possible assertions within a test case. Since this API can be used globally without an explicit import statement, the rule should either query the package.json file to identify which testing tool is used and refine its detection or take a less sophisticated approach and extend its current heuristic to consider Jest in addition to Chai.js, Sinon.js, and Vitest.

https://community.sonarsource.com/t/false-positive-s2699-add-at-least-one-assertion-to-this-test-case-with-repro/103847/10

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-40
