### ISSUE TITLE
Fix FP S2699 (`assertions-in-tests`): Detect `expect` provided by the test callback on concurrent tests

### ISSUE THREAD

**Issue by yassin-kammoun-sonarsource** [SonarSource/SonarJS#4507]
https://community.sonarsource.com/t/vitest-and-describe-concurrent-tests-should-include-assertions/107121

**Comment by ericmorand-sonarsource** [comment]
This issue is a duplicate of #4459. Please refer to the added test `vitest concurrent test cases` for confirmation.
