### ISSUE TITLE
Fix FP S3776 (`cognitive-complexity`): Ignore nested functions and default values

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4520]
We wish to ignore:
1. JavaScript's old way of default value `declaration = parameter || literal`: 
    1. at declaration
    2. in assignment
2. internal functions

**Comment by yassin-kammoun-sonarsource** [comment]
@ericmorand-sonarsource The PR is in another repository: [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs/pull/444).
