### ISSUE TITLE
Fix FP S6582 (`prefer-optional-chain`): Update description and severity

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4521]
- Check ES version
- Update the rule description to give examples of chaining on function calls (o.f?.(arg)) and array accesses (o.arr?.[idx]).
- Reduce defaultSeverity to minor

**Comment by yassin-kammoun-sonarsource** [comment]
> * Check ES version

As discussed during a standup, let's have a proper sprint to extract the ECMAScript version used by a project.
