### ISSUE TITLE
Fix FP S1186 (`no-empty-function`): Ignore noop-like functions, arrows, and constructors

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4523]
1. The rule already allows empty functions that include a comment explaining why it’s empty. We could improve the rule documentation by making this more explicit with a code example
2. The rule description says the rule ignores empty arrow functions and empty functions expressions, but it doesn’t seem to be the case:
    - https://peach.aws-prd.sonarsource.com/project/issues?issues=AYbghgkaTAxgzWtXk532&open=AYbghgkaTAxgzWtXk532&id=abapGit
    - https://peach.aws-prd.sonarsource.com/project/issues?issues=AYPHhDIGfZrQIWTe-cG7&open=AYPHhDIGfZrQIWTe-cG7&id=ruby%3Agitlab
3. Since empty functions are sometimes used as noop in some scenarios, we could also ignore such functions that have “noop”, “disabled”, or “dummy” in their name. Document this behaviour!
    - https://peach.aws-prd.sonarsource.com/project/issues?issues=AYZ8Y2LaR2A6SLmJSN2W&open=AYZ8Y2LaR2A6SLmJSN2W&id=js%3Anextjs
4. We could ignore functions that are assigned to mutable variables as they are likely used as an initial value and then overwritten depending on the program’s execution: https://peach.aws-prd.sonarsource.com/project/issues?issues=AW72inEAAosTBtpuSiLR&open=AW72inEAAosTBtpuSiLR&id=python%3Aarchery
5. ignore constructors: overlap with S6647

**Comment by yassin-kammoun-sonarsource** [comment]
> The rule already allows empty functions that include a comment explaining why it’s empty. We could improve the rule documentation by making this more explicit with a code example

This seems to be decently documented: "_The method is an intentionally-blank override. In this case a nested comment should explain the reason for the blank override."_ Furthermore, it includes a meaningful compliant code example.

**Comment by yassin-kammoun-sonarsource** [comment]
> 3. Since empty functions are sometimes used as noop in some scenarios, we could also ignore such functions that have “noop”, “disabled”, or “dummy” in their name. Document this behaviour!

I think we should limit ourselves to `noop` only, as it seems widely spread enough. Otherwise, if we accept more than one exception, users might ask for more to be considered.

**Comment by yassin-kammoun-sonarsource** [comment]
> 2. The rule description says the rule ignores empty arrow functions and empty functions expressions, but it doesn’t seem to be the case:

It's tricky to ignore empty function expressions because a function expression is actually used in different contexts. For instance, a method definition uses a function expression. Therefore, I would suggest to limit the exception to arrow functions.
