### ISSUE TITLE
Improve S6571 (`no-redundant-type-constituents`): improve doc about intentional violation

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4524]
According to feedback, users seem to intentionally add redundant types for “readability” or documentation, e.g., unions of string literals and the type string, same for numbers

**Comment by ilia-kebets-sonarsource** [comment]
We're not quite sure what to suggest to users.
1. Using redundant types for developer hints is quite convenient if some value can be several predefined types and custom ones like: `foo: 'bar' | 'baz' | string`.
2. We tried to use JS doc for IDE auto-completion, but it didn't work.

We should find a way on what best to suggest to users that use redundant types for documentation or developer tooling.

**Comment by ericmorand-sonarsource** [comment]
@ilia-kebets-sonarsource , if this is of some help, there is a very typical usage of types redundancy in the typings of DOM events, and the purpose is to give developers a hint about what events are natively supported (and of course enable IDE autocompletion).

For example:

```ts
document.addEventListener('DOMContentLoaded', () => { // valid and auto-completed
    
});

document.addEventListener('foo', () => { // valid
    
});
```

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-38
