### ISSUE TITLE
Fix FP S6644 (`no-unneeded-ternary`): add suggestion for case where ternary condition is not boolean

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4525]
When a ternary has the pattern `<expr> ? <bool-literal> : <bool-literal>` and `<expr>` is not of type boolean, we should suggest `!!<expr>`.

We need to update the RSPEC and implement a quickfix.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-37
