### ISSUE TITLE
Fix FP S4323 (`use-type-alias`): Ignore nullable types

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4530]
Add exception when the union is: `<primitive-type> | null | undefined`.

Examples:
- https://peach.aws-prd.sonarsource.com/issues?resolved=false&rules=typescript%3AS4323&open=AX3GPJs8I3PCaQXmpfaU
- https://peach.aws-prd.sonarsource.com/issues?resolved=false&rules=typescript%3AS4323&open=AX3GPJYpI3PCaQXmpd8I
- https://peach.aws-prd.sonarsource.com/issues?resolved=false&rules=typescript%3AS4323&open=AYQK4VrhgknyLMaKMLG9
- https://peach.aws-prd.sonarsource.com/issues?projects=js%3Aangular&resolved=false&rules=typescript%3AS4323&open=AYrj49R377rhrEP8-ikG

**Comment by yassin-kammoun-sonarsource** [comment]
I would propose to generalize the exception to any kind of nullable type, that is, `T | null | undefined` where `T` can be anything. I don't think it makes sense to restrict ourselves to primitive types only.
