### ISSUE TITLE
Consider supporting RSPEC-110 (class hierarchy too deep)

### ISSUE THREAD

**Issue by gabriel-vivas-sonarsource** [SonarSource/SonarJS#4533]
Rule RSPEC-110 detects inheritance chains of classes that are too deep, beyond a threshold.

We had a community thread suggesting to consider this for TypeScript and JavaScript:
https://community.sonarsource.com/t/support-inheritance-depth-analysis-for-javascript-typescript/95492

This rule in other languages is a mixed bag, with a very high dismiss rate, but a general agreement of its value.
We could consider this in the scope of adaptability rules.

The user also made an interesting point about mixing, which are not really a thing in most other languages. How would such rule handle these?

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-34
