### ISSUE TITLE
Fix FN S4123 ("no-invalid-await"): when an async function returns a boolean

### ISSUE THREAD

**Issue by ericmorand-sonarsource** [SonarSource/SonarJS#4535]
### Reproducer:

```ts
async function foo () {
  await bar(); // FN
}

function bar () {
  return true
}
```

### Analysis:

TypeScript considers `false` as a type union between `false` and `true`, which makes `isUnion(awaitedType)` return `true`.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-33
