### ISSUE TITLE
Consider using exclusion filter directly in the sensor

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#4545]
Currently, we use `InputFileFilter` API to remove generated/minified/bundled files from the analysis, however, this removes the file completely from Sensor filesystem and makes it inaccessible to any sensor. This is not always desired, for example, because of secret detection.

We could consider using the exclusion filter only in the sensor itself, making it possible for other sensors from other plugins to still do the analysis on the file.

However, we should consider the impact on metrics and similar.

See https://discuss.sonarsource.com/t/sonartext-is-not-able-analyze-generated-javascript-files/17357 (internal)

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-32
