### ISSUE TITLE
FP S2187: SonarJS project's S6606 unit test file triggers the rule unexpectedly

### ISSUE THREAD

**Issue by ericmorand-sonarsource** [SonarSource/SonarJS#4571]
The file `packages/jsts/src/rules/S6606/unit.test.ts` of our SonarJS project triggers the S2187 rule even though it actually contains test cases.

See: https://next.sonarqube.com/sonarqube/project/issues?issues=5746b5c9-cbdb-4dcc-99ac-be04e97b65f1&open=5746b5c9-cbdb-4dcc-99ac-be04e97b65f1&id=org.sonarsource.javascript%3Ajavascript

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-29
