### ISSUE TITLE
Make jest `maxWorkers` more robust and adaptable

### ISSUE THREAD

**Issue by ilia-kebets-sonarsource** [SonarSource/SonarJS#4587]
We have currently 2 values that must work in concert for the CI:
- `task.cpu` in `cirrus.yml`
- `maxWorkers` parameter in jest command in `package.json`

PR: https://github.com/SonarSource/SonarJS/pull/4583

To make this more robust, we will introduce a test that checks that these 2 values respect the following formula:

```
maxWorkers = CPU - 2
```

We would like the value of maxWorkers to be more easily adaptable on dev machines, since the hardware is varied and different from our CI.
For this, we would need to have a different test command executed whether or not `IS_CI` is true.
We would probably keep a % value for `maxWorkers` for the dev environment.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-27
