### ISSUE TITLE
Create artifact which embeds Node.JS for Alpine Linux

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#4609]
We create platform-specific binaries with embedded Node.JS runtime. We should add another flavor for Alpine Linux because it is a commonly used environment.

This artifact will be not part of "multi" distribution. It will be used once SonarQube/SonarCloud allows for platform-specific plugins.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-25
