### ISSUE TITLE
Fix FP S2699 (`assertions-in-tests`): Add support for testing types in `vitest`

### ISSUE THREAD

**Issue by huynhducduy** [SonarSource/SonarJS#4972]
Vitest allows you to write tests for your types, using `expectTypeOf` or `assertType` syntaxes (https://vitest.dev/guide/testing-types) like the following:

```ts
it('someFunction types', () => {
  expect.assertions(2)

  expectTypeOf(someFunction).parameter(0).toEqualTypeOf<Sometype>()
  expectTypeOf(someFunction).returns.toBeVoid()
})
```

Currently `expectTypeOf` or `assertType` are not taken into account yet, resulting in errors for valid tests.

**Comment by vdiez** [comment]
Added to https://sonarsource.atlassian.net/jira/software/c/projects/JS/issues/JS-41
