### ISSUE TITLE
Rule OneStatementPerLine: add parameter for toggling exceptions back off

### ISSUE THREAD

**Issue by ganncamp** [SonarSource/SonarJS#574]
[RSPEC-122](https://jira.sonarsource.com/browse/RSPEC-122)
Version 3.0 added exceptions in this rule (ticket [SONARJS-944](https://jira.sonarsource.com/browse/SONARJS-944)) to ignore things like 

```
if (condition) doTheThing;  // ignored by exception
var a = 0; doTheOtherThing;  // Still noncompliant

```
But many people who turn this rule on will want to find _all_ instances of multiple statements on a line, especially the ones after conditions or loops. So a parameter should be added to the rule to allow the user to disable these exceptions.

**Comment by ganncamp** [comment]
Personally, yes @vilchik-elena. My experiences with the kind of code this rule now ignores are unpleasant.

**Comment by vilchik-elena** [comment]
Closing this ticket as no traction to this feature
