### ISSUE TITLE
Change contract of rule S1226 to make it become more relevant

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#635]
This rule currently triggers an issue as soon as a method parameter is reassigned. With updated [RSPEC-1226](https://jira.sonarsource.com/browse/RSPEC-1226) this rule is supposed to raise an issue if an only if a method parameter, caught exception or foreach variable is reassigned without having been read before. 

To be noted that this rule must be part of Sonar way and becomes a bug detection rule.

**Comment by vilchik-elena** [comment]
seems to be fixed already, so closing the issue
