### ISSUE TITLE
Rule: Deprecated features should not be used

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#638]
Implements [RSPEC-3817](https://jira.sonarsource.com/browse/RSPEC-3817)

**Comment by vilchik-elena** [comment]
There is existing rule S1874 (Deprecated APIs should not be used) which reports based on js-doc annotation. Seems like the API from S3817 for some reason don't have this annotation in the typings (e.g. `lib.es2015.core.d.ts`) thus we are not reporting on them (e.g. on `str.fixed()`), while it seems relevant.

**Comment by vilchik-elena** [comment]
Rule S1874 is already implemented
