### ISSUE TITLE
DFA: inconsistent evaluation for compared "undefined"s

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#646]
In Data Flow Analysis (DFA) engine we have assertion: at least one branch should be executed (otherwise we have unreasonable deadlock). This assertion might fail if we have inconsistent data evaluation. We should try to avoid such cases and fix them. 
This ticket is supposed to fix this case:
```
function test() {
    var a, b; // a===undefined, b===undefined
    if (a > b) { //  a===undefined, b===undefined and we add knowledge of relation "a > b" while we should simply not enter this branch ('undefined > undefined' is always false)
        if (a != b) { // we know that "a != b" can't be true as they are both "undefined", but "a != b" can't be false as well as we know that "a > b". Here we fail DFA.
        }
    }
}
```

**Comment by vilchik-elena** [comment]
Closing issue as DFA is deprecated and will be soon dropped
