### ISSUE TITLE
Improve ArrayCallbackWithoutReturnCheck : ignore 'map()' if it has side-effects

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#648]
[RSPEC-3796](https://jira.sonarsource.com/browse/RSPEC-3796)

We also thought of just changing the issue message into something like : "you are not explicitly returning anything in this map callback, did you mean to use forEach?"

**Comment by vilchik-elena** [comment]
Not clear why not using `forEach` if `map` is required for side-effects. Closing as won't fix
