### ISSUE TITLE
Improve MultilineBlockCurlyBraceCheck : include same-line statements

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#650]
[RSPEC-2681](https://jira.sonarsource.com/browse/RSPEC-2681)

Exception : if the conditional statement is itself on the same line as a prior statement we ignore further same-line statements. We assume that the developer is explicitly writing everything on a single line and is taking care of what is executed conditionally and what not.

```
foo(); if(a) bar(); zoo();  // OK
```

When working on this don't forget to discuss with [~ann.campbell.2] to change the description of RSPEC-2681 as it would not fit anymore.

One more interesting case:
```
if(a) {
 ...
} if(b) {           //Missing else ?
  ...
}
```

**Comment by vilchik-elena** [comment]
I am not sure what the intention of this issue. For the note we are currently reporting on `foo(); if(a) bar(); zoo(); `.
Closing as won't fix
