### ISSUE TITLE
Update rule messages

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#657]
We should verify that rule messages make sense and up to date.
* [RSPEC-3735](https://jira.sonarsource.com/browse/RSPEC-3735) VoidUseCheck
* [RSPEC-1116](https://jira.sonarsource.com/browse/RSPEC-1116) EmptyStatementCheck

**Comment by yassin-kammoun-sonarsource** [comment]
- RSPEC-3735: verified
- RSPEC-1116: #2469 created
