### ISSUE TITLE
Symbolic Engine: comparison expressions with non-number operand should return 'false'

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#660]
There is a rule RSPEC-3758 "Values not convertible to numbers should not be used in numeric comparisons" which raises an issue each time you compare object, `NaN` or `undefined` with numeric value. Such expression will return false. It can't considered as a bug, but we can profit from this logic in symbolic engine itself. So that we will have new issues for other rules, e.g.
```
var x;

if (x < 0) { // condition is always false
}
```

**Comment by vilchik-elena** [comment]
Closing issue as DFA is deprecated and will be soon dropped
