### ISSUE TITLE
Exclude node_modules and bower_components from Analysis

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#665]
`node_modules` is the location where npm stores dependencies, same for `bower_components` for bower.

The contents of neither should be included in the analysis.

[~fabrice.bellingard] has excluded `node_modules` from the npm-supported scanner

**Comment by stas-vilchik** [comment]
Please be aware that if the proposal works for 99% of the cases, there are still practices to put the real code in `node_modules`. For example, it might be done for simpler dependency management of multi-module projects. So it should be possible to opt out.
