### ISSUE TITLE
Improve NullDereferenceCheck to cover for-of expressions returning null/undefined

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#667]
```
  var arrayContainer = "some container";
  for(let i of arrayContainer.arr) {  // Noncompliant
    ...
  }
```

Currently we check for symbols being null/undefined, not for the result of expression evaluation. This ticket implies changing the way we model `for-of` loop in the CFG.

**Comment by vilchik-elena** [comment]
Closing issue as DFA is deprecated and will be soon dropped
