### ISSUE TITLE
Consider arrow functions with expression body in symbolic execution

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#669]
It might make sense in considering arrow functions with expression body in symbolic execution, at least for cross-procedure analysis. For example
```
function foo() {
  var bar = (a, b) => a - b;
  var x = bar(4, 5); // we can infer that "x" is number 
}
```

**Comment by vilchik-elena** [comment]
Closing issue as DFA is deprecated and will be soon dropped
