### ISSUE TITLE
Improve modelling of object-related symbolic values

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#675]
- BuiltInFunctionSymbolicValue should extend BuiltInObjectSymbolicValue
- prototype objects (e.g. `String.prototype`) should not have `baseConstraint` equal to constraint on object created with this prototype (e.g. `STRING_OBJECT`). Due to this we have FP like:
```
if (String.prototype instanceof String) { // FP: always true (in fact it's always false)
  foo();
}
```
- property access logic should not be so spread over different classes (`MemberProgramPoint`, `Type`, `BuiltInObjectSymbolicValue`)

**Comment by vilchik-elena** [comment]
Closing issue as DFA is deprecated and will be soon dropped
