### ISSUE TITLE
Fix false-negative when value of one variable depends on value of another one

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#678]
Due to live variable analysis we defined the set of variables which values are dead. Based on that we clean constraints in program state. The problem appears when values of variable is used through another variable (as `c` can be used through `a`).
```
function bar(d) {
  let c = d;
  let a = (c === null);
  if (d === 'aaa') {
    if (typeof(c) == "string") {  // OK, issue (on always true) raised here
    }
    if (a) {                      // KO, issue (on always false) missing here (FN)
    }
  }
  // foo(c);    // uncomment to avoid the FN above
}
```

**Comment by vilchik-elena** [comment]
Closing issue as DFA is deprecated and will be soon dropped
