### ISSUE TITLE
Drop support of "reportPath" and "itReportPath" properties when 6.x LTS is released

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#679]
Currently `reportPath` and `itReportPath` are visible in the interface but marked deprecated, and honored by analysis but with a deprecation warning.

Once the 6.x LTS has been released, all support for these properties should be dropped, so: 
- dropped from the UI
- ignored by analysis.

**Comment by vilchik-elena** [comment]
outdated, done already
