### ISSUE TITLE
TooManyArgumentsCheck: default parameter value

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#683]
[RSPEC-930](https://jira.sonarsource.com/browse/RSPEC-930)
```
var arrow_function = (foo=()=>true) => {
  foo(1, 2); // FP
};
```

**Comment by yassin-kammoun-sonarsource** [comment]
Fixed since using ESLint's [no-extra-arguments](https://github.com/SonarSource/SonarJS/commit/35e7f65485b5bfc1328d98e28d2c97a23938208c).
