### ISSUE TITLE
Improve TooManyArgumentsCheck based on type information

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#685]
[RSPEC-930](https://jira.sonarsource.com/browse/RSPEC-930)

**Comment by vilchik-elena** [comment]
rule has a different implementation now, based on eslint semantic. We can indeed improve it based on TS type checker.

**Comment by vilchik-elena** [comment]
The impact of this old ticket is not clear, even if theoretically it makes sense. I close the ticket and we can still do the change to the rule later as part of the bigger initiative around types usage.
