### ISSUE TITLE
Filter activated rules based on the ECMAScript version used by a project

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#686]
Some rules which are tagged with "es2015" should not be executed on a project which cannot use the new syntaxes provided by ES2015. Users have to take care of that when building their quality profile.
However, the JavaScript plugin could automatically disable some rules when a project declares that it targets a given version of ECMAScript. That could be similar to [what already exists for Java](http://docs.sonarqube.org/display/PLUG/Handling+Java+Source+Version).

**Comment by vilchik-elena** [comment]
That is probably outdated need. Closing the issue
