### ISSUE TITLE
Create rule: Disallow lexical declarations in case/default clauses

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#690]
http://eslint.org/docs/rules/no-case-declarations.html

**Comment by vilchik-elena** [comment]
a nice rule!

**Comment by ilia-kebets-sonarsource** [comment]
in the latest ESLint recommended rules review, we decided to add this as a new rule, but didn't go through with it for some reason.

**Comment by yassin-kammoun-sonarsource** [comment]
> in the latest ESLint recommended rules review, we decided to add this as a new rule, but didn't go through with it for some reason.

I think we either forgot to create a new ticket for the rule or we realize this one existed but didn't label it with the mmf label.
