### ISSUE TITLE
Improve DeadStore (S1854): consider block-scoped variables created in global scope

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#692]
We can consider block-scoped variables created in global scope as local as they are not accessible everywhere and you can't access them through window.x. So it will be nice to have issues for such variables
```
// global scope
if (cond) {
  let x = 1;  // NOK!
  x = 2;
  foo(x);
}
```

**Comment by vilchik-elena** [comment]
Not much traction and it's unlikely there will be a lot of logic on global level, so closing issue as low ROI
