### ISSUE TITLE
Improve rule WrongScopeDeclaration: precise line number for "for" loop

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#693]
[RSPEC-2392](https://jira.sonarsource.com/browse/RSPEC-2392)
Message is supposed to say the line number where declaration should be ("Move the declaration of "%s" to line %s."). Currently we use first line of declaration + 1. It's a false line when declaration should be on scope line as for `for`-loop:
```
var i;    // Move the declaration of "i" to line 3.
for (i = 0; i<10; i++) {
  ...
}
```

**Comment by vilchik-elena** [comment]
Low ROI, rule is not even in default profile (while this can be challenged). Closing issue
