### ISSUE TITLE
Support class properties accessors

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#694]
Currently for all accessors, properties with FunctionType are created. 
```
class A {
  get foo() {
     return 1; 
  }
}

```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/set
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by yassin-kammoun-sonarsource** [comment]
ESLint-based parsers are now used since frontend migration.
