### ISSUE TITLE
Rule: Too many dependencies for module in AMD format

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#704]
```
define(
["module1", "module2", ..., "module3"],
function(){
// module code here
});
```

http://requirejs.org/docs/whyamd.html#amd

**Comment by eoghanc** [comment]
Agree that this should be separate from the "Functions should not have too many parameters" rule.

Opinion is that it should be higher, maybe 12-15 to allow for some text/json/i18n/template resources as well as js modules.

**Comment by vilchik-elena** [comment]
Closing as AMD is less and less used
