### ISSUE TITLE
Improve (1854) DeadStoresCheck: cover properties

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#705]
[RSPEC-1854](https://jira.sonarsource.com/browse/RSPEC-1854)
Improve the rule to cover cases when object properties are assigned a value which is never used, e.g:
```
var obj = {
  first: 1,
  second: 2
}
obj.first = "first";       // Noncompliant
```

**Comment by fmallet** [comment]
Should be added to RSPEC
## Noncompliant Code Example
```
var obj = {
  first: 1,
  second: 2
}
obj.first = "first";       // Noncompliant; unused
```

## Compliant Solution
```
var obj = {
  first: 1,
  second: 2
}
```

**Comment by ilia-kebets-sonarsource** [comment]
this rule requires to use the codePath API from ESLint, which we aren't very knowledgeable yet.

**Comment by Wohops** [comment]
Migrated to Jira. New ticket number: JS-142
