### ISSUE TITLE
Rule: Proprietary attributes should not be used

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#707]
Implements [RSPEC-2787](https://jira.sonarsource.com/browse/RSPEC-2787)

We should define how a variable could be considered as an HTMLElement, e.g:
```
var element = document.getElementById();
var element = document.getElementsByTagName()[0];
var element = document.querySelector("p.intro");
```

```
document.anchors["id"]
document.body
document.documentElement
document.embeds["id"]
document.forms["id"]
document.head
document.images["id"]
document.links[0]
document.scripts["id"]
```

Are there other ways ?

It's worth investigation of other than `innerText` proprietary attributes.

**Comment by vilchik-elena** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/issues/156

**Comment by vilchik-elena** [comment]
other rules about browser compatibility https://github.com/amilajack/eslint-plugin-compat

**Comment by vilchik-elena** [comment]
It seems that `innerText` is supported by all browsers now, so closing this issue as not relevant
