### ISSUE TITLE
Improve S3271 LocalStorage rule: support 'window.localStorage'

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#711]
RSPEC-3271

Current implementation of the rule supports only direct access of `localStorage`. We should support its usages on `window` object. 

This issue relates to #701

**Comment by vilchik-elena** [comment]
As soon as this ticket done this suggestion #623 should be considered.

**Comment by eric-therond-sonarsource** [comment]
[RSPEC-3271](https://jira.sonarsource.com/browse/RSPEC-3271) is deprecated
