### ISSUE TITLE
S2583: Add exceptions

### ISSUE THREAD

**Issue by jccollet** [SonarSource/SonarJS#792]
The following exceptions have been added to [RSPEC-2583](https://jira.sonarsource.com/browse/RSPEC-2583):
- When the condition is a single `const` of boolean value
```
const debug = false;
//...
if (debug) {
  // Print something
}
```
- When the condition is the literal `0`, `1`, `true` or `false`.

In these cases it is obvious the code is as intended.

**Comment by yassin-kammoun-sonarsource** [comment]
The rule was deprecated and eventually dropped #2339.
