### ISSUE TITLE
Analysis fails on JSX files containing object: Parser error

### ISSUE THREAD

**Issue by Eoan242** [SonarSource/SonarJS#817]
Hi, 
I'm running an analysis on this React project using the sonar-scanner-3.0.3.778-linux version. Sonar-scanner is working; however it is also throwing "Unable to parse file" errors on all my *.jsx files that contain object declarations in them.

**Reproducer** 
Perform an analysis with some "analyse_me.jsx" file containing an object:
```
    this.state = {
      foo: [
        'bar': false,
        'raz': true,
      ],
    }
```

**Logs**
```

ERROR: Unable to parse file: src/analyse_me.jsx
ERROR: Parse error at line 3 column 14:

1:     this.state = {
2:       foo: [
3:         'bar': false,
                ^
4:         'raz': true,
5:       ],
6:    }

```

**Expected behavior**

I'm not expecting a parser error at this point. Object is syntactically valid here.
Thanks for your kind help!

**Comment by vilchik-elena** [comment]
Hi @Eoan242! Thanks for sharing with us your problem. Could you send me link or something explaining this syntax?

**Comment by vilchik-elena** [comment]
@Eoan242 Could you confirm that you use flow?

**Comment by Eoan242** [comment]
We can work around it by altering syntax (though the original compiled fine). 
Makes it explicit to be an array of objects nested inside an object. SonarQube likes this just fine. 
Thanks! 

    this.state = {
      foo: [
        { 'bar': false },
        { 'raz': true },
      ],
    }
