### ISSUE TITLE
Drop support for separate coverage reports

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#839]
Since SonarJS 4.0 stop supporting these properties
* `sonar.javascript.forceZeroCoverage`
* `sonar.javascript.lcov.reportPath`
* `sonar.javascript.lcov.itReportPath`

**Comment by vilchik-elena** [comment]
relates to #837

**Comment by NilSet** [comment]
Will SonarJS create its own coverage reports instead of importing lcov?

**Comment by vilchik-elena** [comment]
@NilSet indeed
