### ISSUE TITLE
Parsing error: attributes in 'script' tag in 'vue' file

### ISSUE THREAD

**Issue by ilawrencewu** [SonarSource/SonarJS#843]
I installed the SonarJS into SonarQube, and scanned a Vue project, the result snippet as below: 
**Maybe this is a bug.**
**SonarJS version:**  3.3.0.5702 <br>
**SonarQube version:** 5.6.6<br>
"dependencies": {
             "lodash": "4.17.4",
             "vue": "2.3.4",
             "vue-resource": "1.3.4",
             "vue-router": "2.6.0",
             "vuex": "2.3.1",
             "vue-loader": "11.3.4",
             "vue-style-loader": "2.0.5",
             "vue-template-compiler": "2.3.4",
             "webpack": "^2.2.1",
             "webpack-bundle-analyzer": "^2.2.1",
             "webpack-dev-middleware": "^1.10.0",
             "webpack-hot-middleware": "^2.16.1",
             "webpack-merge": "^2.6.1"
  }

ERROR: Unable to parse file: /data/jenkins/workspace/develop/vueportal/lib/components/picker/src/picker-slot.vue
ERROR: Parse error at line 111 column 1:

101:     overflow: visible
102:   }
103: 
104:   .picker-3d .picker-item {
105:     transform-origin: center center;
106:     backface-visibility: hidden;
107:     transition-timing-function: ease-out
108:   }
109: </style>
110: 
111: <script type="text/babel">
     ^
112:   import draggable from './draggable'
113:   import translateUtil from './translate'
114:   import { once, addClass, removeClass } from './dom'
115:   import emitter from './emitter'
116:   import Vue from 'vue'
117:   if (!Vue.prototype.$isServer) {
118:     require('raf.js')
119:   }
120: 
121:   var rotateElement = function (element, angle) {.....other code}
</script>

It seems that SonarJS cannot recognize the <script> tag.

**Comment by vilchik-elena** [comment]
Minimal reproducer
```
<script someAttr="foo">
console.log("Bar");
</script>
```

**Comment by vilchik-elena** [comment]
@ilawrencewu Thanks for this issue! I've added it to next milestone
