### ISSUE TITLE
[feature request] Provide "Public API" metric

### ISSUE THREAD

**Issue by AMorgaut** [SonarSource/SonarJS#872]
**I want to request a feature.**

Sonarqubre provide a very interesting [Public API metric](https://docs.sonarqube.org/display/SONAR/Metrics+-+Public+API)

It looks unfortunately to be only available for Java & Cobol

Note:
[#871 - Native ESLint support](https://github.com/SonarSource/SonarJS/issues/871) feature request may help as:
- ESLint use a ESTree AST variant that includes JSDoc nodes 
- ESLint already provides JSDoc related plugins ( [valid-jsdoc](https://eslint.org/docs/rules/valid-jsdoc), [require-jsdoc](https://eslint.org/docs/rules/require-jsdoc) )

**Comment by AMorgaut** [comment]
Note:
I create a feature request to make require-jsdoc validate that public API is documented
[eslint / eslint #9708 - require-jsdoc rule should enforce JSDoc on exported (public) API ](https://github.com/eslint/eslint/issues/9708)
I started a first implementation
I'm unfortunately less comfortable with the sonar dev environment

**Comment by vilchik-elena** [comment]
@AMorgaut These metrics are deprecated since SQ 6.2 and not displayed https://jira.sonarsource.com/browse/SONAR-8328
Do you think some new rules will make sense instead?

**Comment by AMorgaut** [comment]
We currently only have a comment ratio rule 
This one does not reflect API documentation, and you may want to create a Quality Gate that FAIL if your product doesn't document all its public API (ex: should be mandatory for a framework)

**Comment by vilchik-elena** [comment]
--> #1049
