### ISSUE TITLE
Parse Error: nested ternary with arrow function

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarJS#874]
```
const x = cond1
  ? cond2
    ? a
    : b
  : fn => fn()
```
Relates to #859

**Comment by vilchik-elena** [comment]
Not at all obvious how to fix this parsing error

Parsing fails, as while we try to parse nested ternary we consume `b: fn => fn()` as arrow function with return type

**Comment by yassin-kammoun-sonarsource** [comment]
Parsable with ESLint frontend.
