### ISSUE TITLE
Rule S3041: Arrays should not be accessed beyond their boundaries

### ISSUE THREAD

**Issue by ashmna** [SonarSource/SonarJS#896]
Implements [RSPEC-3041](https://jira.sonarsource.com/browse/RSPEC-3041)

**I want to request a feature.**

Please find out of bounds array exceptions
The following fragment of code can explain better

code with the exception
```
    let index = -1;

    if (cards[cards.length - 1].type === "QUESTION") {
        // not executed
        index = cards.length - 1;
    } else if (cards[cards.length - 2].type === "QUESTION") {
        // not executed
        index = cards.length - 2;
    }

    // exception
    cards[index].responseText = responseText;
```

the correct code examples

```
    let index = -1;

    if (cards[cards.length - 1].type === "QUESTION") {
        // not executed
        index = cards.length - 1;
    } else if (cards[cards.length - 2].type === "QUESTION") {
        // not executed
        index = cards.length - 2;
    }

    if (index !== -1) {
        cards[index].responseText = responseText;
    }
```

P.S. Of course, I understand that there is billion possible example, but the index with possible -1 is the most popular and it will be cool have such bug filter.

**Comment by vilchik-elena** [comment]
Data flow analysis is required for such rule. So far we don't have such techniques in place. We can reopen the issue or create a new one if/when we bring such technology.
