### ISSUE TITLE
Skip size measures (comments) in template of vue files

### ISSUE THREAD

**Issue by thiagoaos** [SonarSource/SonarJS#901]
SonarJS version: 3.3.0.5702 
SonarQube version 6.2

When Sonar checks .vue files, the system is counting the lines of code in <template> block and this is being applied to the percentage of commented lines. 

How do I disable parsing <template> block because I do not want the html to be checked?

**Comment by vilchik-elena** [comment]
Could you give more explanations? some small example may be?

**Comment by thiagoaos** [comment]
Sorry. I update to 6.7.1 today and can't reproduce again.

I will close if happen again i will record and post here.
