### ISSUE TITLE
Rule: Multiple variables should not be declared on the same line

### ISSUE THREAD

**Issue by alban-auzeill** [SonarSource/SonarJS#946]
Implements [RSPEC-1659](https://jira.sonarsource.com/browse/RSPEC-1659)

**Comment by vilchik-elena** [comment]
see
https://eslint.org/docs/rules/one-var
https://eslint.org/docs/rules/one-var-declaration-per-line

**Comment by vilchik-elena** [comment]
This rule is covered for all other languages in SQ, yet I am not sure if it should be in default profile
