### ISSUE TITLE
Add React flow types to globals

### ISSUE THREAD

**Issue by saberduck** [SonarSource/SonarJS#947]
React Flow types should be defined as globals for flow environment, because they are available in global scope.

We can also consider to avoid raising `javascript:S3827` Reference Error on all flow types, since this will be usually detected by flow and will not cause runtime error.

See also https://stackoverflow.com/questions/48863228/sonarjs-marks-issues-if-flowtype-type-annotations-from-the-standard-library-are?noredirect=1#comment84733942_48863228

**Comment by vilchik-elena** [comment]
Closing as we use another parser for Flow now
