### ISSUE TITLE
Upgrade to sslr-squid-bridge 2.7.0.377

### ISSUE THREAD

**Issue by m-g-sonar** [SonarSource/SonarJS#956]
A new version of sslr-squid-bridge has been released (technically, sync with maven central ongoing), updated to SQ 6.7 LTS and removed unused code.

**Comment by m-g-sonar** [comment]
Relates to #948

**Comment by m-g-sonar** [comment]
Contributes to [MMF-1217](https://jira.sonarsource.com/browse/MMF-1217)

**Comment by vilchik-elena** [comment]
Close it as replaced by #948
