### ISSUE TITLE
Multiline toplevel HTML Comments in .vue files are not supported

### ISSUE THREAD

**Issue by meh2481** [SonarSource/SonarJS#957]
**I want to report a bug.**

**SonarQube version:** Version 7.0 (build 36138)<br>

**Reproducer** 
```
<!-- Test comment
comment
-->
<template>
  <div></div>
</template>

<script>
</script>

<style>
</style>
```

**Logs**
```
ERROR: Unable to parse file: file:///C:/Users/...../test.vue

ERROR: Parse error at line 2 column 1:

 1: <!-- Test comment
 2: comment
    ^
 3: -->
 4: <template>
 5:   <div></div>
 6: </template>
 7:
 8: <script>
 9: </script>
10:
11: <style>
12: </style>
```

**Expected behavior**

According to the [Vue Component Spec](https://vue-loader.vuejs.org/en/start/spec.html), this is a valid .vue file, as this is valid HTML comment syntax. Vue files with single-line toplevel HTML comments work as expected.

**Comment by vilchik-elena** [comment]
https://vue-loader.vuejs.org/spec.html#comments

**Comment by cellphoneworld** [comment]
hi
nice article thank fore sheering
www.cellphoneworld.in
