### ISSUE TITLE
Support detection of quality issues on test source files

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#959]
Based on the value of the RSPEC field "Analysis Scope" (see [MMF-1160](https://jira.sonarsource.com/browse/MMF-1160)), SonarJS should automatically determine when a rule should be applied to main source files or to test sources files or to all files. Up to now, only the main source files are analyzed.

**Comment by vilchik-elena** [comment]
closing as https://jira.sonarsource.com/browse/MMF-1451 is pending
