### ISSUE TITLE
TY

### ISSUE THREAD

**Issue by ahmetcaglayan** [SonarSource/SonarJS#962]
..

**Comment by saberduck** [comment]
can you please post full logs, it's not clear what the error is because logs are cut.

**Comment by ahmetcaglayan** [comment]
+ . /common.sh
+ start_docker registry.tool.zfu.zb:5000
+ mkdir -p /var/log
+ mkdir -p /var/run
+ sanitize_cgroups
+ mkdir -p /sys/fs/cgroup
+ mountpoint -q /sys/fs/cgroup
+ mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
+ mount -o remount,rw /sys/fs/cgroup
+ sed -e 1d /proc/cgroups
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<cpuset\>'
+ grouping=cpuset
+ '[' -z cpuset ']'
+ mountpoint=/sys/fs/cgroup/cpuset
+ mkdir -p /sys/fs/cgroup/cpuset
+ mountpoint -q /sys/fs/cgroup/cpuset
+ mount -n -t cgroup -o cpuset cgroup /sys/fs/cgroup/cpuset
+ '[' cpuset '!=' cpuset ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<cpu\>'
+ grouping=cpu
+ '[' -z cpu ']'
+ mountpoint=/sys/fs/cgroup/cpu
+ mkdir -p /sys/fs/cgroup/cpu
+ mountpoint -q /sys/fs/cgroup/cpu
+ mount -n -t cgroup -o cpu cgroup /sys/fs/cgroup/cpu
+ '[' cpu '!=' cpu ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<cpuacct\>'
+ grouping=cpuacct
+ '[' -z cpuacct ']'
+ mountpoint=/sys/fs/cgroup/cpuacct
+ mkdir -p /sys/fs/cgroup/cpuacct
+ mountpoint -q /sys/fs/cgroup/cpuacct
+ mount -n -t cgroup -o cpuacct cgroup /sys/fs/cgroup/cpuacct
+ '[' cpuacct '!=' cpuacct ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<blkio\>'
+ grouping=blkio
+ '[' -z blkio ']'
+ mountpoint=/sys/fs/cgroup/blkio
+ mkdir -p /sys/fs/cgroup/blkio
+ mountpoint -q /sys/fs/cgroup/blkio
+ mount -n -t cgroup -o blkio cgroup /sys/fs/cgroup/blkio
+ '[' blkio '!=' blkio ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<memory\>'
+ grouping=memory
+ '[' -z memory ']'
+ mountpoint=/sys/fs/cgroup/memory
+ mkdir -p /sys/fs/cgroup/memory
+ mountpoint -q /sys/fs/cgroup/memory
+ mount -n -t cgroup -o memory cgroup /sys/fs/cgroup/memory
+ '[' memory '!=' memory ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<devices\>'
+ grouping=devices
+ '[' -z devices ']'
+ mountpoint=/sys/fs/cgroup/devices
+ mkdir -p /sys/fs/cgroup/devices
+ mountpoint -q /sys/fs/cgroup/devices
+ mount -n -t cgroup -o devices cgroup /sys/fs/cgroup/devices
+ '[' devices '!=' devices ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<freezer\>'
+ grouping=freezer
+ '[' -z freezer ']'
+ mountpoint=/sys/fs/cgroup/freezer
+ mkdir -p /sys/fs/cgroup/freezer
+ mountpoint -q /sys/fs/cgroup/freezer
+ mount -n -t cgroup -o freezer cgroup /sys/fs/cgroup/freezer
+ '[' freezer '!=' freezer ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<net_cls\>'
+ grouping=net_cls
+ '[' -z net_cls ']'
+ mountpoint=/sys/fs/cgroup/net_cls
+ mkdir -p /sys/fs/cgroup/net_cls
+ mountpoint -q /sys/fs/cgroup/net_cls
+ mount -n -t cgroup -o net_cls cgroup /sys/fs/cgroup/net_cls
+ '[' net_cls '!=' net_cls ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<perf_event\>'
+ grouping=perf_event
+ '[' -z perf_event ']'
+ mountpoint=/sys/fs/cgroup/perf_event
+ mkdir -p /sys/fs/cgroup/perf_event
+ mountpoint -q /sys/fs/cgroup/perf_event
+ mount -n -t cgroup -o perf_event cgroup /sys/fs/cgroup/perf_event
+ '[' perf_event '!=' perf_event ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<net_prio\>'
+ grouping=net_prio
+ '[' -z net_prio ']'
+ mountpoint=/sys/fs/cgroup/net_prio
+ mkdir -p /sys/fs/cgroup/net_prio
+ mountpoint -q /sys/fs/cgroup/net_prio
+ mount -n -t cgroup -o net_prio cgroup /sys/fs/cgroup/net_prio
+ '[' net_prio '!=' net_prio ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ cut -d: -f2
++ grep '\<hugetlb\>'
+ grouping=hugetlb
+ '[' -z hugetlb ']'
+ mountpoint=/sys/fs/cgroup/hugetlb
+ mkdir -p /sys/fs/cgroup/hugetlb
+ mountpoint -q /sys/fs/cgroup/hugetlb
+ mount -n -t cgroup -o hugetlb cgroup /sys/fs/cgroup/hugetlb
+ '[' hugetlb '!=' hugetlb ']'
+ read sys hierarchy num enabled
+ '[' 1 '!=' 1 ']'
++ cat /proc/self/cgroup
++ grep '\<pids\>'
++ cut -d: -f2
+ grouping=pids
+ '[' -z pids ']'
+ mountpoint=/sys/fs/cgroup/pids
+ mkdir -p /sys/fs/cgroup/pids
+ mountpoint -q /sys/fs/cgroup/pids
+ mount -n -t cgroup -o pids cgroup /sys/fs/cgroup/pids
+ '[' pids '!=' pids ']'
+ read sys hierarchy num enabled
+ grep '/proc/sys\s\+\w\+\s\+ro,' /proc/mounts
+++ ip route get 8.8.8.8
+++ awk '{ print $5 }'
++ cat /sys/class/net/w6rgbhegag5j-1/mtu
+ local mtu=1500
+ local 'server_args=--mtu 1500'
+ local registry=
+ for registry in '$1'
+ server_args='--mtu 1500 --insecure-registry registry.tool.zfu.zb:5000'
+ '[' -n '' ']'
+ echo 111
+ trap stop_docker EXIT
+ sleep 1
+ dockerd --data-root /scratch/docker --mtu 1500 --insecure-registry registry.tool.zfu.zb:5000
+ docker info
+ cp -R dist/coverage/ shell-app/
+ cd shell-app
+ docker pull registry.tool.zfu.zb:5000/sonar-runner
Using default tag: latest
latest: Pulling from sonar-runner
6d987f6f4279: Pull complete 
013dbd5feb01: Pull complete 
9d5b23feead7: Pull complete 
a3daf8c7bea4: Pull complete 
dff3ea652e03: Pull complete 
2f6b1acd53b7: Pull complete 
08e5c4db7687: Pull complete 
9c5822c1cd7e: Pull complete 
90a2c21d113f: Pull complete 
be1f79f68ace: Pull complete 
3016a32e7b42: Pull complete 
6d82c73c627d: Pull complete 
Digest: sha256:c913f418e8b6fcee5076e0d4dd2940f037806583a089244b4d8032ce4cccd389
Status: Downloaded newer image for registry.tool.zfu.zb:5000/sonar-runner:latest
++ pwd
+ docker run --rm -v /tmp/build/8b2915b9/shell-app:/sonar-app registry.tool.zfu.zb:5000/sonar-runner framework shell-app
+ GROUP_NAME=framework
+ PROJECT_NAME=shell-app
+ PROJECT_DIR=/gopath/src/gitlab.zfu.fintek.local/framework/shell-app
+ PROJECT_DIR_2=/var/go/src/gitlab.zfu.fintek.local/framework/shell-app
+ SONAR_DIR=/sonar-app
+ sed -i 's|/gopath/src/gitlab.zfu.fintek.local/framework/shell-app|/sonar-app|g' /sonar-app/coverage/report-lcov/lcov.info
sed: /sonar-app/coverage/report-lcov/lcov.info: No such file or directory
+ sed -i 's|/var/go/src/gitlab.zfu.fintek.local/framework/shell-app|/sonar-app|g' /sonar-app/coverage/report-lcov/lcov.info
sed: /sonar-app/coverage/report-lcov/lcov.info: No such file or directory
+ /usr/lib/sonar-runner/bin/sonar-runner
INFO: Runner configuration file: /usr/lib/sonar-runner/conf/sonar-runner.properties
INFO: Project configuration file: /sonar-app/sonar-project.properties
INFO: SonarQube Runner 2.5-RC1
INFO: Java 1.8.0_131 Oracle Corporation (64-bit)
INFO: Linux 4.4.0-112-generic amd64
INFO: User cache: /root/.sonar/cache
INFO: Load global repositories
INFO: Load global repositories (done) | time=151ms
INFO: User cache: /root/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=3ms
INFO: Download sonar-csharp-plugin-5.0.jar
INFO: Download sonar-java-plugin-3.13.1.jar
INFO: Download sonar-scm-git-plugin-1.2.jar
INFO: Download sonar-scm-svn-plugin-1.3.jar
INFO: Download sonar-javascript-plugin-2.15.jar
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=93ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=19ms
INFO: Load active rules
INFO: Load active rules (done) | time=262ms
INFO: Publish mode
INFO: -------------  Scan SHELL-APP
INFO: Language is forced to js
INFO: Load server rules
INFO: Load server rules (done) | time=52ms
INFO: Base dir: /sonar-app
INFO: Working dir: /sonar-app/.sonar
INFO: Source paths: src
INFO: Test paths: specs
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: Excluded sources: 
INFO:   src/i18n/**
INFO:   src/models/**
INFO:   src/utils/**
INFO:   src/index.js
INFO:   src/main.js
INFO:   src/components/didyoumean2/**
INFO: 88 files indexed
INFO: 24 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for js: Sonar way
INFO: JaCoCoSensor: JaCoCo report not found : /sonar-app/target/jacoco.exec
INFO: JaCoCoItSensor: JaCoCo IT report not found: /sonar-app/target/jacoco-it.exec
INFO: Sensor Lines Sensor
INFO: Sensor Lines Sensor (done) | time=21ms
INFO: Sensor SCM Sensor
INFO: SCM provider for this project is: git
INFO: 6 files to be analyzed
INFO: 6/6 files analyzed
INFO: Sensor SCM Sensor (done) | time=594ms
INFO: Sensor JavaScript Squid Sensor
INFO: 53 source files to be analyzed
ERROR: Unable to parse file: /sonar-app/src/routes/index.js
ERROR: Parse error at line 13 column 17:

 3: import Loadable from "react-loadable";
 4: import Loading from "../components/Loading";
 5: import Layout from "../containers/layout/layout";
 6: import QueryStringUtils from "../utils/queryStringUtils";
 7: import AuthorizingPageContainer from "../containers/pages/Authorizing/Authorizing";
 8: import { logger } from "@zt/logger";
 9: import Api from "../api";
10: import { store } from "../main";
11: 
12: export const LoadableLogin = Loadable({
13:   loader: () => import("../containers/pages/Login/login"),
                    ^
14:   loading: Loading
15: });
16: 
17: export const LoadableHome = Loadable({
18:   loader: () => import("../containers/pages/Home/Home"),
19:   loading: Loading
20: });
21: 
22: export const LoadableMetroMenu = Loadable({
23:   loader: () => import("../containers/pages/MetroMenu/metroMenu"),

INFO: Unit Test Coverage Sensor is started
INFO: 53/53 source files have been analyzed
INFO: Analysing [/sonar-app/coverage/lcov.info]
INFO: Could not resolve 70 file paths in [/sonar-app/coverage/lcov.info], first unresolved path: /gopath/src/gitlab.zfu.fintek.local/framework/shell-app/src/init.js
INFO: Integration Test Coverage Sensor is started
INFO: Overall Coverage Sensor is started
INFO: Analysing [/sonar-app/coverage/lcov.info]
INFO: Could not resolve 70 file paths in [/sonar-app/coverage/lcov.info], first unresolved path: /gopath/src/gitlab.zfu.fintek.local/framework/shell-app/src/init.js
INFO: Sensor JavaScript Squid Sensor (done) | time=2711ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=41ms
INFO: Sensor Code Colorizer Sensor
INFO: Sensor Code Colorizer Sensor (done) | time=2ms
INFO: Sensor CPD Block Indexer
INFO: DefaultCpdBlockIndexer is used for js
INFO: Sensor CPD Block Indexer (done) | time=1ms
INFO: Calculating CPD for 48 files
INFO: CPD calculation finished
INFO: Analysis report generated in 193ms, dir size=890 KB
INFO: Analysis reports compressed in 177ms, zip size=360 KB
INFO: Analysis report uploaded in 43ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://10.1.148.37:9000/dashboard/index/shell.app
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://10.1.148.37:9000/api/ce/task?id=AWJHnpoqd9vx4FXk7CHT
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 7.641s
INFO: Final Memory: 51M/509M
INFO: ------------------------------------------------------------------------
+ rm -rf .sonar
+ stop_docker
++ cat /tmp/docker.pid
+ local pid=111
+ '[' -z 111 ']'
+ kill -TERM 111
+ wait 111

**Comment by ahmetcaglayan** [comment]
is this log enough?

**Comment by ahmetcaglayan** [comment]
Although I give the correct path to lcov.info file, I do not see the gesture covarege files

**Comment by saberduck** [comment]
I am not sure, but it seems that your sources are at  `/sonar-app/src` , while in `lcov.info` paths are like `/gopath/src/gitlab.zfu.fintek.local/framework/shell-app/src/` . 
Make sure that paths seen by `sonar-runner` are same as the ones in `lcov` file.

Also you are using quite old version of SonarQube, consider updating to the latest versions (but this is probably not related to your issue).

**Comment by ahmetcaglayan** [comment]
actually looks at the value of covarege, but every build gives the same error. This is not a problem for us, but can it be a bug from your side?

**Comment by saberduck** [comment]
Sorry, I don't understand what are you trying to say. What is your issue precisely?

**Comment by ahmetcaglayan** [comment]
actually the problem is just "parse error", is this a problem on your side?

**Comment by saberduck** [comment]
Try to update to the latest version of SonarQube (6.7 LTS, or 7.0) and SonarJS (4.6) and verify if you still have a parse error. Also please don't close the issue while we are still investigating the problem
