### ISSUE TITLE
Update rules "All/Two branches ... with same implementation" to support new exceptions

### ISSUE THREAD

**Issue by fmallet** [SonarSource/SonarJS#963]
[RSPEC-3923](https://jira.sonarsource.com/browse/RSPEC-3923) and [RSPEC-1871](https://jira.sonarsource.com/browse/RSPEC-1871) have been updated in sync to support two new exceptions (see the rule descriptions). The implementations must be updated accordingly.

**Comment by yassin-kammoun-sonarsource** [comment]
Was already the case at the time of the implementation.
