### ISSUE TITLE
For code coverage, list the name of test on hover

### ISSUE THREAD

**Issue by srini88** [SonarSource/SonarJS#969]
**I want to request a feature.**

For the code coverage, currently `Sonar` says partially/fully covered by tests. It would be useful if it lists the name of the `test` also that is exercising this file. 

![image](https://user-images.githubusercontent.com/3435834/38515422-38003740-3c02-11e8-9709-d2a8596c2570.png)

**Expected behavior**
Display the name of the tests on hover.

**Comment by vilchik-elena** [comment]
@srini88 thanks for suggestion
