### ISSUE TITLE
specific rules for nodejs/angular?

### ISSUE THREAD

**Issue by javixeneize** [SonarSource/SonarJS#970]
Hi

This is not a bug itself, it might be better considered a enhancement

I think the rules are great for "plain" javascript, but those dont fit very well with NodeJS or AngularJS.

Have you considered creating a profile/plugin specific for those technologies?

Thanks

**Comment by saberduck** [comment]
Hello,

we have not considered writing rules for specific frameworks, however, we want to make it easier to use existing linters with SonarJS ([see here](https://jira.sonarsource.com/browse/MMF-1212)), so in the future, it will be possible for example to import issues from ESLint plugin for angular.

**Comment by vilchik-elena** [comment]
@javixeneize if we talk about configuration of existing rules, do you find there are some rules should be deactivated or activated or reconfigured for nodejs or angular? which one?
Current profiles ("sonar way", and extended "sonar way recommended") are supposed to be framework/environment agnostic.
