### ISSUE TITLE
I am trying to scan js file using sonar-scanner but it is throwing as unable to parse error as it is having some xml tags how to fix it ?

### ISSUE THREAD

**Issue by Umapat77** [SonarSource/SonarJS#976]
Getting parsing error exacctly at the first line of the below snippet. Not sure how to avoid it ?

var request = <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sbl="http://xmlns.oracle.com/pcbpel/adapter/db/SBLCustomerRetrieveENT">
	  <soapenv:Header/>
	  <soapenv:Body>
		 <sbl:SBLCustomerRetrieveENTInput>
			<sbl:CUST_ID></sbl:CUST_ID>
			<sbl:CUST_ID_TYPE></sbl:CUST_ID_TYPE>
			<sbl:SERIAL_NUM>{data.SERIAL_NUM}</sbl:SERIAL_NUM>
			<sbl:CUST_ROW_ID></sbl:CUST_ROW_ID>
			<sbl:KENANACCOUNTID></sbl:KENANACCOUNTID>
		 </sbl:SBLCustomerRetrieveENTInput>
	  </soapenv:Body> </soapenv:Envelope>;

Can anyone help me to overcome this issue ?

**Comment by Umapat77** [comment]
Thanks a lot for your reply. But I have both js and xml sonar plugins under the plugins folder under sonarqube server. Also I dont mention any thing as sonar.language, so my understanding it should parse without any error. I am not very clear what you mean by preprocessing and template string you are referring. Could you please elaborate more ?

**Comment by vilchik-elena** [comment]
@Umapat77 the syntax you use is not legal javascript, you can't just put xml as a value of expression. Even if you use some tool to transform it into legal javascript, SonarJS is not able to parse it.
The only way to go is to put your xml in the quotes (make it string literal). Note, even in that case SonarXML will not consider it (as it's just javascript string)
```js
var request = `<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sbl="http://xmlns.oracle.com/pcbpel/adapter/db/SBLCustomerRetrieveENT">
soapenv:Header/
soapenv:Body
sbl:SBLCustomerRetrieveENTInput
sbl:CUST_ID</sbl:CUST_ID>
sbl:CUST_ID_TYPE</sbl:CUST_ID_TYPE>
sbl:SERIAL_NUM{data.SERIAL_NUM}</sbl:SERIAL_NUM>
sbl:CUST_ROW_ID</sbl:CUST_ROW_ID>
sbl:KENANACCOUNTID</sbl:KENANACCOUNTID>
</sbl:SBLCustomerRetrieveENTInput>
</soapenv:Body> </soapenv:Envelope>`;
```

**Comment by Umapat77** [comment]
Thanks for your comments
