### ISSUE TITLE
Parse error React JSX (CRA) ES6 spread

### ISSUE THREAD

**Issue by Vadorequest** [SonarSource/SonarJS#977]
SonarQube is crashing when parsing my react app, built with Create React App, I suspect it has to do with the spread operator `...{}` which is ES6/7 and maybe not supported?

**SonarJS version:** sonar-scanner-3.1.0.1141-macosx<br>
**SonarQube version:** sonarqube-7.1<br>

**Reproducer** 
```
// any code with use of spread operator?
```

**Logs**
```
ERROR: Parse error at line 42 column 12:

32: const CheckboxSwitch = (
33:   {
34:     // Only use default when the input is disabled, because we don't need it in that particular case
35:     disabled,
36:     name = disabled ? uuid() : null,
37:     id = name,
38:     value = false,
39:     labels,
40:     onChange = (a) => a,
41:     classes,
42:     ...rest,
               ^
43:   },

```

**Expected behavior**
Not to crash

**Comment by andrea-guarino-sonarsource** [comment]
Thanks, ticket #982 has been created to handle this.
In the meantime, you can just remove trailing comma to avoid parsing error.
