### ISSUE TITLE
Parse trailing comma after rest element in an object pattern

### ISSUE THREAD

**Issue by andrea-guarino-sonarsource** [SonarSource/SonarJS#982]
```javascript
const {...rest,} = obj;
```
Removing comma would fix the parsing.

**Comment by saberduck** [comment]
Note that this syntax is not allowed per EcmaScript standard http://www.ecma-international.org/ecma-262/#sec-destructuring-binding-patterns .
However, it is supported by babel and typescript and it was not difficult to implement so I decided to support it.
