### ISSUE TITLE
How to use the text file to show code coverage in sonarqube ?

### ISSUE THREAD

**Issue by Umapat77** [SonarSource/SonarJS#984]
I have written unit cases for my adapter code. The results are in a text file having module name and whether the unit test is succcess or failure with the string SUCCESS AND FAILURE. How can I use this text file to show code coverage in sonarqube analysis ?. Please help me on this.

**Comment by vilchik-elena** [comment]
Hi! you need to convert this file into generic SonarQube format and then provide path to converted file with property `sonar.testExecutionReportPaths`. See details here https://docs.sonarqube.org/display/SONAR/Generic+Test+Data

**Comment by Umapat77** [comment]
Thanks for the update. If you have any sample files can you please provide me

**Comment by vilchik-elena** [comment]
you check this example for TS https://github.com/SonarSource/SonarTS-example/tree/master/example1, it should be around the same for JS

**Comment by vilchik-elena** [comment]
https://docs.sonarqube.org/display/PLUG/TypeScript+Test+Execution+and+Coverage+Results+Import

**Comment by Umapat77** [comment]
Thanks for the timely help. For TS, i can generate lcov file. But in this case I have the test results output in the text file. For example: I am having details like module name and status as whether it is passed or failed. So using this data I need to populate code coverage in sonarqube.  But in the generic test data link there are two cases which i dont understand properly. 

<coverage version="1">
  <file path="xources/hello/NoConditions.xoo">
    <lineToCover lineNumber="6" covered="true"/>
    <lineToCover lineNumber="7" covered="false"/>
  </file>
  <file path="xources/hello/WithConditions.xoo">
    <lineToCover lineNumber="3" covered="true" branchesToCover="2" coveredBranches="1"/>
  </file>
</coverage>

and

<testExecutions version="1">
  <file path="testx/ClassOneTest.xoo">
    <testCase name="test1" duration="5"/>
    <testCase name="test2" duration="500">
      <skipped message="short message">other</skipped>
    </testCase>
    <testCase name="test3" duration="100">
      <failure message="short">stacktrace</failure>
    </testCase>
    <testCase name="test4" duration="500">
      <error message="short">stacktrace</error>
    </testCase>
  </file>
</testExecutions>

**Comment by Umapat77** [comment]
Hi , I want to set as covered as true for the entire folder level and not for linenumber. How to specify in that general xml format ?

**Comment by vilchik-elena** [comment]
@Umapat77 it's not possible
