### ISSUE TITLE
Getting error while running sonar scanner for ts project

### ISSUE THREAD

**Issue by Umapat77** [SonarSource/SonarJS#985]
I am running sonar analysis for a ts project. But getting below error during analysis. Please let me know as what is causing the issue ?

INFO: ------------------------------------------------------------------------ INFO: EXECUTION FAILURE INFO: ------------------------------------------------------------------------ INFO: Total time: 31.904s INFO: Final Memory: 11M/262M INFO: ------------------------------------------------------------------------ ERROR: Error during SonarQube Scanner execution ERROR: Unable to highlight file src/app/Footer/Download/download.component.spec.ts ERROR: Caused by: 3 is not a valid line for pointer. File src/app/Footer/Download/download.component.spec.ts has 1 line(s)

**Comment by vilchik-elena** [comment]
Could you provide content of this file `src/app/Footer/Download/download.component.spec.ts`? Looks like it's a problem with syntax highlighting positioning
