### ISSUE TITLE
Custom tags in *.vue files crash JavaScript analysis

### ISSUE THREAD

**Issue by xShivan** [SonarSource/SonarJS#988]
**SonarJS version:** 4.1 (Cannot determine, I'm using SonarCloud)<br>
**SonarQube version:** 7.2.0<br>

**Reproducer** 
```
<i18n>
{
    "de-DE": {
        "title": "Test"
    },
    "en-US": {
        "title": "Test"
    }
}
</i18n>

<template>
<div>
    <h1>Test</h1>
</div>
</template>

<script>
export default {
    mounted() {
        console.log('test!');
    }
};
</script>

<style>
</style>

```

**Logs**
```
2018-06-07T12:47:39.4658233Z ERROR: Unable to parse file: file:///C:/xyz/ClientApp/components/home/login.vue
2018-06-07T12:47:39.4660933Z ERROR: Parse error at line 1 column 1:
2018-06-07T12:47:39.4661508Z 
2018-06-07T12:47:39.4662032Z  1: <i18n>
2018-06-07T12:47:39.4662471Z     ^
```

**Expected behavior**

The analyzer should skip the <i18n> tags or any other custom tags inside the Single File Component. Content of the <script> tags should be analyzed.

**Comment by nono0481** [comment]
Hello,

 i have a similar problem with  `<docs> ` tags in .vue files.
 In my Nuxt project we use a plugin [vuestyleguide](https://github.com/vue-styleguidist/vue-styleguidist) and to use them we add a `<docs> ` tags :
```javascript
<docs>
    ```jsx
    <div>
        <navbar/>
    </div>
    ```
</docs>
``` 
And in Sonar we have this error :
```
ERROR: Unable to parse file: file:///.../components/common/Navbar/Navbar.vue
ERROR: Parse error at line 97 column 1:
```

Is there a way to fix this parsing ?

**Comment by vilchik-elena** [comment]
@nono0481 I don't think there is a workaround for your problem, the parser itself should be fixed

**Comment by vilchik-elena** [comment]
https://vue-loader.vuejs.org/spec.html#custom-blocks
