### ISSUE TITLE
Rule S2070: SHA-1 and Message-Digest hash algorithms should not be used

### ISSUE THREAD

**Issue by agigleux** [SonarSource/SonarJS#991]
Implements [RSPEC-2070](https://jira.sonarsource.com/browse/RSPEC-2070)

This rule raises an issue when:
- MD5 or SHA1 methods from https://www.npmjs.com/package/crypto-js are used
- when  createHash('md4') or createHash('md5') or createHash('sha1') from the 'crypto' Node.js module is called:
`const crypto = require('crypto');`
`const hash = crypto.createHash('md5');`
or
`const hash = crypto.createHash('sha1');`
- when the sha1 Class from the "Stanford Javascript Crypto Library" is used http://bitwiseshiftleft.github.io/sjcl/doc/sjcl.hash.sha1.html

**Comment by eric-therond-sonarsource** [comment]
[RSPEC-2070](https://jira.sonarsource.com/browse/RSPEC-2070) vulnerability is now superseded by hotspot [RSPEC-4790](https://jira.sonarsource.com/browse/RSPEC-4790) 

And 4790 rule seems to be already implemented for JS:
https://sonarcloud.io/project/issues?id=eric-therond-sonarsource_testjs&open=AW-O4TKOUFlQ0Vt1QkTf&resolved=false&types=SECURITY_HOTSPOT

**Comment by yassin-kammoun-sonarsource** [comment]
Closed since the rule is deprecated.
