### ISSUE TITLE
Issues not showing all at once in file

### ISSUE THREAD

**Issue by fetassinari** [SonarSource/SonarJS#993]
When an analysis is executed issues are not shown all at once for rule Variables should be declared explicitly. It shows one issue and only when you correct the issue it shows another one after running the analysis again.

Exanple in attached image.

Is that the expected behaviour or is it a bug?

Is there any workaround?

Thanks!

![sonar](https://user-images.githubusercontent.com/37186162/41357652-03a594da-6efd-11e8-85cc-e9ffe1909948.jpg)

**SonarJS version:**
4.1 (build 6085)

**SonarQube version:** 
6.7 (build 33306)

**Rule key:** 

Variables should be declared explicitly

**Comment by vilchik-elena** [comment]
it's expected behaviour, we raise one issue per variable

**Comment by fetassinari** [comment]
Thanks for quick reply!
