### ISSUE TITLE
Rule S2278: Neither DES (Data Encryption Standard) nor DESede (3DES) should be used

### ISSUE THREAD

**Issue by agigleux** [SonarSource/SonarJS#996]
Implements [RSPEC-2278](https://jira.sonarsource.com/browse/RSPEC-2278)

This rule raises an issue when the following algorithms are used with the "Crypto" Node.js module:

des               des-cbc           des-cfb           
des-ecb           des-ede           des-ede-cbc       des-ede-cfb       
des-ede-ofb       des-ede3          des-ede3-cbc      des-ede3-cfb      
des-ede3-ofb      des-ofb           des3 

Example:
`const crypto = require('crypto');`
`const cipher = crypto.createCipher('des-ede3', secretKey);`

**Comment by eric-therond-sonarsource** [comment]
RSPEC-2278 is deprecated by RSPEC-5547
Ticket for RSPEC-5547 here https://github.com/SonarSource/SonarJS/issues/1783
