### ISSUE TITLE
.html files are not supported from sonar pom configuration

### ISSUE THREAD

**Issue by FaahdNoor** [SonarSource/SonarJS#998]
**I want to report a bug.**

**SonarJS version:** 4.1 (build 6085)<br>
**SonarQube version:** 6.7.3 (build 38370)<br>

**Rule key:** sonar.javascript.file.suffixes

**Expected behavior**

**.html files should supported when given configuration in pom.xml**

**Comment by saberduck** [comment]
@FaahdNoor what do you mean by supported? Do you want to detect issues inside `html` files?

**Comment by FaahdNoor** [comment]
this issue is still not addressed. @saberduck exactly, issues needs to be detected inside the html files as well. etc inline scripts
